// Code generated by ebigent generate; DO NOT EDIT.
//
// The delta half of concept:state-synchronization. tinybind-go generates
// the codecs for the world and wire types themselves; since v0.5.21 it
// generates no diff, patch, or delta encoding, so those are the
// framework's (decision:framework-side-delta-generation) and they are
// here.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// DecodeLimits bounds what a decoder in this file will read. They are
// resource limits rather than format rules, so they belong to the
// deployment and not to the protocol: two peers must agree on the shape
// of a message and need agree on nothing about how large one this process
// is willing to read (data:runtime-resource-budget). Startup may lower
// them; the values here suit a snapshot.
var DecodeLimits = cbor.DecoderOptions{
	MaxContainerItems:  1 << 16,
	MaxStringBytes:     4 << 20,
	MaxInputBytes:      64 << 20,
	MaxRawMessageBytes: 64 << 20,
	RejectFloats:       true,
}

// TTTWorldDelta is what changed between two TTTWorld values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful. The bit
// order is declaration order, so moving a field moves the wire.
type TTTWorldDelta struct {
	Present uint64
	// bit 0
	Cells []uint8
	// bit 1
	Turn uint16
	// bit 2
	Winner uint16
	// bit 3
	Line []uint8
	// bit 4
	Moves uint8
	// bit 5
	Over bool
}

// DiffTTTWorldInto fills d with what changed between baseline and
// current, and reports whether anything did.
func DiffTTTWorldInto(d *TTTWorldDelta, baseline, current TTTWorld) bool {
	d.Present = 0
	if string(baseline.Cells) != string(current.Cells) {
		d.Present |= 1 << 0
		d.Cells = current.Cells
	}
	if baseline.Turn != current.Turn {
		d.Present |= 1 << 1
		d.Turn = current.Turn
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 2
		d.Winner = current.Winner
	}
	if string(baseline.Line) != string(current.Line) {
		d.Present |= 1 << 3
		d.Line = current.Line
	}
	if baseline.Moves != current.Moves {
		d.Present |= 1 << 4
		d.Moves = current.Moves
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 5
		d.Over = current.Over
	}
	return d.Present != 0
}

// DiffTTTWorld returns what changed between baseline and current.
func DiffTTTWorld(baseline, current TTTWorld) TTTWorldDelta {
	var d TTTWorldDelta
	DiffTTTWorldInto(&d, baseline, current)
	return d
}

// ApplyTTTWorldDelta puts d back onto v. A bit Present does not name
// leaves that field as it stands, which is what makes a delta a delta.
func ApplyTTTWorldDelta(v *TTTWorld, d TTTWorldDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Cells = d.Cells
	}
	if d.Present&(1<<1) != 0 {
		v.Turn = d.Turn
	}
	if d.Present&(1<<2) != 0 {
		v.Winner = d.Winner
	}
	if d.Present&(1<<3) != 0 {
		v.Line = d.Line
	}
	if d.Present&(1<<4) != 0 {
		v.Moves = d.Moves
	}
	if d.Present&(1<<5) != 0 {
		v.Over = d.Over
	}
	return nil
}

// AppendCBORTo appends d as one CBOR array: the mask, then the values it
// names, in bit order. A field the mask omits costs nothing.
func (v TTTWorldDelta) AppendCBORTo(dst []byte) []byte {
	n := 1
	for bit := range 6 {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Cells))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Turn))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Line))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Moves))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	return dst
}

// DecodeCBORFrom reads one delta into v, and refuses anything after it:
// a trailing item means the sender and the receiver disagree about the
// shape, which concept:cbor-wire-profile cannot detect any other way.
func (v *TTTWorldDelta) DecodeCBORFrom(data []byte) error {
	r, err := cbor.NewReader(data, DecodeLimits)
	if err != nil {
		return err
	}
	if err := v.decodeFrom(r); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// decodeFrom reads one delta off r.
func (v *TTTWorldDelta) decodeFrom(r *cbor.Reader) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TTTWorldDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		x, err := r.ReadBytes()
		if err != nil {
			return err
		}
		// ReadBytes borrows from the input, so the value is copied into
		// whatever capacity the field already holds: it must outlive the
		// buffer it was read from, and reusing the capacity keeps the
		// steady state allocation-free.
		v.Cells = append(v.Cells[:0], x...)
		read++
	}
	if present&(1<<1) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Turn = uint16(x)
		read++
	}
	if present&(1<<2) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Winner = uint16(x)
		read++
	}
	if present&(1<<3) != 0 {
		x, err := r.ReadBytes()
		if err != nil {
			return err
		}
		// ReadBytes borrows from the input, so the value is copied into
		// whatever capacity the field already holds: it must outlive the
		// buffer it was read from, and reusing the capacity keeps the
		// steady state allocation-free.
		v.Line = append(v.Line[:0], x...)
		read++
	}
	if present&(1<<4) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Moves = uint8(x)
		read++
	}
	if present&(1<<5) != 0 {
		x, err := r.ReadBool()
		if err != nil {
			return err
		}
		v.Over = bool(x)
		read++
	}
	if read != n {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TTTWorldDelta", Err: cbor.ErrUnexpectedToken}
	}
	return nil
}
