// Code generated by configbind/codegen; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:b0b9195cc78560bd200a8733f6346db35d5723f4cd38a193a83ed2021c2fc766 self=sha256:6b202d35e78209fa3677baf293a9840e67db7161cfd5087d668f2a3fdabc3353 outputs=tinybind_gen.go,configbind_gen.go

package buildconf

import (
	"fmt"
	"strconv"
	"time"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerProjectDefinition0()
	registerBuildDefinition1()
	registerDevDefinition2()
	registerBehaviorDefinition3()
}

func registerProjectDefinition0() {
	configbind.Register[Project](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Project",
		Prefix:   "project",
		Doc:      "Project is the [project] table: what this repository is",
		KnownKeys: []string{
			"project.module",
			"project.go",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "project", Key: "module", Help: "go module path of this project"},
			{Prefix: "project", Key: "go", Help: "pinned go toolchain version; empty follows the host"},
		},
		Apply: applyProjectDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "module", Kind: configbind.ScaffoldString, Help: "go module path of this project"},
			{Key: "go", Kind: configbind.ScaffoldString, Help: "pinned go toolchain version; empty follows the host"},
		},
	})
}

func applyProjectDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Project)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Project: bad destination")
	}
	if v, ok := o.GetString("project.module"); ok {
		p.Module = v
	}
	if v, ok := o.GetString("project.go"); ok {
		p.GoToolchain = v
	}
	return nil
}

func registerBuildDefinition1() {
	configbind.Register[Build](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Build",
		Prefix:   "build",
		Doc:      "Build is the [build] table. Each [[build.target]] is one concept:build-target, realized as one entry point per decision:entry-points-over-build-tags",
		KnownKeys: []string{
			"build.target",
		},
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyBuildDefinition1,
		Scaffold: []configbind.ScaffoldField{
			{Key: "target", Kind: configbind.ScaffoldTableArray, Help: "Target is the declared artifact set. An array of tables, so the file is its only source", Nested: []configbind.ScaffoldField{
				{Key: "name", Kind: configbind.ScaffoldString, Help: "target name used by ebigent build and ebigent dev"},
				{Key: "kind", Kind: configbind.ScaffoldString, Default: "client", Help: "client, listen, dedicated, or simulation"},
				{Key: "entry", Kind: configbind.ScaffoldString, Help: "main package path, such as ./cmd/game"},
				{Key: "goos", Kind: configbind.ScaffoldString, Help: "target GOOS; empty follows the host"},
				{Key: "goarch", Kind: configbind.ScaffoldString, Help: "target GOARCH; empty follows the host"},
				{Key: "tags", Kind: configbind.ScaffoldStringSlice, Help: "Tags are build tags. Linkage only: rule:build-tag-only-for-linkage keeps behavior out of tags, so nothing here may select a game rule or a synchronization mode"},
				{Key: "dev", Kind: configbind.ScaffoldBool, Default: "false", Help: "this target links the dev debug endpoint and must not ship"},
			}},
		},
	})
}

func applyBuildDefinition1(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Build)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Build: bad destination")
	}
	if ta1, ok := o.Get("build.target"); ok {
		if !ta1.IsTables {
			return fmt.Errorf("configbind: build.target: expected an array of tables ([[build.target]])")
		}
		p.Target = make([]Target, len(ta1.Tables))
		for i1 := range ta1.Tables {
			if v, ok := ta1.Tables[i1].GetString("name"); ok {
				p.Target[i1].Name = v
			}
			if v, ok := ta1.Tables[i1].GetString("kind"); ok {
				p.Target[i1].Kind = v
			} else {
				p.Target[i1].Kind = "client"
			}
			if v, ok := ta1.Tables[i1].GetString("entry"); ok {
				p.Target[i1].Entry = v
			}
			if v, ok := ta1.Tables[i1].GetString("goos"); ok {
				p.Target[i1].GOOS = v
			}
			if v, ok := ta1.Tables[i1].GetString("goarch"); ok {
				p.Target[i1].GOARCH = v
			}
			if v, ok := ta1.Tables[i1].GetMulti("tags"); ok {
				p.Target[i1].Tags = v
			}
			if v, ok := ta1.Tables[i1].GetString("dev"); ok {
				bb, err := strconv.ParseBool(v)
				if err != nil {
					return fmt.Errorf("configbind: build.target[%d].dev: %w", i1, err)
				}
				p.Target[i1].Dev = bb
			} else {
				p.Target[i1].Dev = false
			}
		}
	}
	return nil
}

func registerDevDefinition2() {
	configbind.Register[Dev](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Dev",
		Prefix:   "dev",
		Doc:      "Dev is the [dev] table: how ebigent dev runs flow:dev-rebuild-loop",
		KnownKeys: []string{
			"dev.target",
			"dev.watch",
			"dev.ignore",
			"dev.debounce",
			"dev.console",
		},
		Defaults: map[string]string{
			"dev.debounce": "200ms",
			"dev.console":  "127.0.0.1:8930",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "dev", Key: "target", Help: "target ebigent dev builds and runs; empty requires exactly one declared target"},
			{Prefix: "dev", Key: "watch", Help: "source roots watched for changes; empty watches the project root", Kind: cliparser.KindArray},
			{Prefix: "dev", Key: "ignore", Help: "glob patterns never watched", Kind: cliparser.KindArray},
			{Prefix: "dev", Key: "debounce", Help: "quiet period before a rebuild"},
			{Prefix: "dev", Key: "console", Help: "dev console listen address; empty disables the console"},
		},
		Apply: applyDevDefinition2,
		Scaffold: []configbind.ScaffoldField{
			{Key: "target", Kind: configbind.ScaffoldString, Help: "target ebigent dev builds and runs; empty requires exactly one declared target"},
			{Key: "watch", Kind: configbind.ScaffoldStringSlice, Help: "source roots watched for changes; empty watches the project root"},
			{Key: "ignore", Kind: configbind.ScaffoldStringSlice, Help: "glob patterns never watched"},
			{Key: "debounce", Kind: configbind.ScaffoldDuration, Default: "200ms", Help: "quiet period before a rebuild"},
			{Key: "console", Kind: configbind.ScaffoldString, Default: "127.0.0.1:8930", Help: "dev console listen address; empty disables the console"},
		},
	})
}

func applyDevDefinition2(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Dev)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Dev: bad destination")
	}
	if v, ok := o.GetString("dev.target"); ok {
		p.Target = v
	}
	if v, ok := o.GetMulti("dev.watch"); ok {
		p.Watch = v
	}
	if v, ok := o.GetMulti("dev.ignore"); ok {
		p.Ignore = v
	}
	if v, ok := o.GetString("dev.debounce"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: dev.debounce: %w", err)
		}
		p.Debounce = d
	} else {
		p.Debounce = 200000000 // 200ms
	}
	if v, ok := o.GetString("dev.console"); ok {
		p.Console = v
	} else {
		p.Console = "127.0.0.1:8930"
	}
	return nil
}

func registerBehaviorDefinition3() {
	configbind.Register[Behavior](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Behavior",
		Prefix:   "behavior",
		Doc:      "Behavior is the [behavior] table: where the AI pipeline keeps its files. decision:ai-pipeline-always-scaffolded means these paths exist in every generated project, whether or not the pipeline is in use",
		KnownKeys: []string{
			"behavior.library",
			"behavior.corpus",
			"behavior.skill",
		},
		Defaults: map[string]string{
			"behavior.library": "behavior/chips.json",
			"behavior.corpus":  "corpus",
			"behavior.skill":   "skills/behavior-analyze",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "behavior", Key: "library", Help: "chip library file"},
			{Prefix: "behavior", Key: "corpus", Help: "episode corpus root"},
			{Prefix: "behavior", Key: "skill", Help: "analysis skill directory"},
		},
		Apply: applyBehaviorDefinition3,
		Scaffold: []configbind.ScaffoldField{
			{Key: "library", Kind: configbind.ScaffoldString, Default: "behavior/chips.json", Help: "chip library file"},
			{Key: "corpus", Kind: configbind.ScaffoldString, Default: "corpus", Help: "episode corpus root"},
			{Key: "skill", Kind: configbind.ScaffoldString, Default: "skills/behavior-analyze", Help: "analysis skill directory"},
		},
	})
}

func applyBehaviorDefinition3(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Behavior)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Behavior: bad destination")
	}
	if v, ok := o.GetString("behavior.library"); ok {
		p.Library = v
	} else {
		p.Library = "behavior/chips.json"
	}
	if v, ok := o.GetString("behavior.corpus"); ok {
		p.Corpus = v
	} else {
		p.Corpus = "corpus"
	}
	if v, ok := o.GetString("behavior.skill"); ok {
		p.Skill = v
	} else {
		p.Skill = "skills/behavior-analyze"
	}
	return nil
}
