// Code generated by configbind/codegen; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:f83c0d45c8905664b9dc3b088bcba90b74c05b5d4299d1a09e9f895c6baa64d9 self=sha256:0baa57cbc0593b6fc10e7c455cf5958a76ddb74df127afb22d902d3513e56cc9 outputs=tinybind_gen.go,configbind_gen.go

package buildconf

import (
	"fmt"
	"strconv"
	"time"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerProjectDefinition0()
	registerProtocolDefinition1()
	registerBuildDefinition2()
	registerDevDefinition3()
	registerBehaviorDefinition4()
}

func registerProjectDefinition0() {
	configbind.Register[Project](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Project",
		Prefix:   "project",
		Doc:      "Project is the [project] table: what this repository is",
		KnownKeys: []string{
			"project.module",
			"project.go",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "project", Key: "module", Help: "go module path of this project"},
			{Prefix: "project", Key: "go", Help: "pinned go toolchain version; empty follows the host"},
		},
		Apply: applyProjectDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "module", Kind: configbind.ScaffoldString, Help: "go module path of this project"},
			{Key: "go", Kind: configbind.ScaffoldString, Help: "pinned go toolchain version; empty follows the host"},
		},
	})
}

func applyProjectDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Project)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Project: bad destination")
	}
	if v, ok := o.GetString("project.module"); ok {
		p.Module = v
	}
	if v, ok := o.GetString("project.go"); ok {
		p.GoToolchain = v
	}
	return nil
}

func registerProtocolDefinition1() {
	configbind.Register[Protocol](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Protocol",
		Prefix:   "protocol",
		Doc:      "Protocol is the [protocol] table: the game's own contract, and the protocol level of concept:configuration-scope",
		KnownKeys: []string{
			"protocol.package",
			"protocol.title",
			"protocol.shape",
			"protocol.realtime",
			"protocol.view",
			"protocol.devices",
			"protocol.sync",
			"protocol.seats.count",
			"protocol.seats.fill",
			"protocol.seats.occupant",
			"protocol.team",
		},
		Defaults: map[string]string{
			"protocol.shape":          "solo",
			"protocol.realtime":       "paced",
			"protocol.view":           "shared",
			"protocol.sync":           "server_authoritative",
			"protocol.seats.count":    "1",
			"protocol.seats.fill":     "bots",
			"protocol.seats.occupant": "any",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "protocol", Key: "package", Help: "import path of the game, subpath included; empty takes project.module"},
			{Prefix: "protocol", Key: "title", Help: "display name; empty takes the last element of the package path"},
			{Prefix: "protocol", Key: "shape", Help: "solo, duo, or multi"},
			{Prefix: "protocol", Key: "realtime", Help: "turn_based, paced, or twitch"},
			{Prefix: "protocol", Key: "view", Help: "shared or per_agent"},
			{Prefix: "protocol", Key: "devices", Help: "accepted input devices: keyboard, mouse, gamepad", Kind: cliparser.KindArray},
			{Prefix: "protocol", Key: "sync", Help: "synchronization mode"},
			{Prefix: "protocol", Key: "seats.count", Help: "number of declared seats"},
			{Prefix: "protocol", Key: "seats.fill", Help: "fill an unclaimed seat with a bot, or start with it empty"},
			{Prefix: "protocol", Key: "seats.occupant", Help: "who may take a seat: any, human, or bot"},
		},
		Apply: applyProtocolDefinition1,
		Scaffold: []configbind.ScaffoldField{
			{Key: "package", Kind: configbind.ScaffoldString, Help: "import path of the game, subpath included; empty takes project.module"},
			{Key: "title", Kind: configbind.ScaffoldString, Help: "display name; empty takes the last element of the package path"},
			{Key: "shape", Kind: configbind.ScaffoldString, Default: "solo", Help: "solo, duo, or multi"},
			{Key: "realtime", Kind: configbind.ScaffoldString, Default: "paced", Help: "turn_based, paced, or twitch"},
			{Key: "view", Kind: configbind.ScaffoldString, Default: "shared", Help: "shared or per_agent"},
			{Key: "devices", Kind: configbind.ScaffoldStringSlice, Help: "accepted input devices: keyboard, mouse, gamepad"},
			{Key: "sync", Kind: configbind.ScaffoldString, Default: "server_authoritative", Help: "synchronization mode"},
			{Key: "seats.count", Kind: configbind.ScaffoldInt, Default: "1", Help: "number of declared seats"},
			{Key: "seats.fill", Kind: configbind.ScaffoldString, Default: "bots", Help: "fill an unclaimed seat with a bot, or start with it empty"},
			{Key: "seats.occupant", Kind: configbind.ScaffoldString, Default: "any", Help: "who may take a seat: any, human, or bot"},
			{Key: "team", Kind: configbind.ScaffoldTableArray, Help: "Team is the division of the seats. No entry means no teams; the seat counts must add up to Seats.Count when there are any", Nested: []configbind.ScaffoldField{
				{Key: "name", Kind: configbind.ScaffoldString, Help: "team name"},
				{Key: "seats", Kind: configbind.ScaffoldInt, Default: "0", Help: "seats on this team"},
				{Key: "occupant", Kind: configbind.ScaffoldString, Help: "who may take a seat on this team: any, human, or bot; empty takes protocol.seats.occupant"},
			}},
		},
	})
}

func applyProtocolDefinition1(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Protocol)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Protocol: bad destination")
	}
	if v, ok := o.GetString("protocol.package"); ok {
		p.Package = v
	}
	if v, ok := o.GetString("protocol.title"); ok {
		p.Title = v
	}
	if v, ok := o.GetString("protocol.shape"); ok {
		p.Shape = v
	} else {
		p.Shape = "solo"
	}
	if v, ok := o.GetString("protocol.realtime"); ok {
		p.Realtime = v
	} else {
		p.Realtime = "paced"
	}
	if v, ok := o.GetString("protocol.view"); ok {
		p.View = v
	} else {
		p.View = "shared"
	}
	if v, ok := o.GetMulti("protocol.devices"); ok {
		p.Devices = v
	}
	if v, ok := o.GetString("protocol.sync"); ok {
		p.Sync = v
	} else {
		p.Sync = "server_authoritative"
	}
	if v, ok := o.GetString("protocol.seats.count"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: protocol.seats.count: %w", err)
		}
		p.Seats.Count = int(n)
	} else {
		p.Seats.Count = 1
	}
	if v, ok := o.GetString("protocol.seats.fill"); ok {
		p.Seats.Fill = v
	} else {
		p.Seats.Fill = "bots"
	}
	if v, ok := o.GetString("protocol.seats.occupant"); ok {
		p.Seats.Occupant = v
	} else {
		p.Seats.Occupant = "any"
	}
	if ta1, ok := o.Get("protocol.team"); ok {
		if !ta1.IsTables {
			return fmt.Errorf("configbind: protocol.team: expected an array of tables ([[protocol.team]])")
		}
		p.Team = make([]Team, len(ta1.Tables))
		for i1 := range ta1.Tables {
			if v, ok := ta1.Tables[i1].GetString("name"); ok {
				p.Team[i1].Name = v
			}
			if v, ok := ta1.Tables[i1].GetString("seats"); ok {
				n, err := strconv.ParseInt(v, 10, 0)
				if err != nil {
					return fmt.Errorf("configbind: protocol.team[%d].seats: %w", i1, err)
				}
				p.Team[i1].Seats = int(n)
			} else {
				p.Team[i1].Seats = 0
			}
			if v, ok := ta1.Tables[i1].GetString("occupant"); ok {
				p.Team[i1].Occupant = v
			}
		}
	}
	return nil
}

func registerBuildDefinition2() {
	configbind.Register[Build](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Build",
		Prefix:   "build",
		Doc:      "Build is the [build] table. Each [[build.target]] is one concept:build-target, realized as one entry point per decision:entry-points-over-build-tags",
		KnownKeys: []string{
			"build.target",
		},
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyBuildDefinition2,
		Scaffold: []configbind.ScaffoldField{
			{Key: "target", Kind: configbind.ScaffoldTableArray, Help: "Target is the declared artifact set. An array of tables, so the file is its only source", Nested: []configbind.ScaffoldField{
				{Key: "name", Kind: configbind.ScaffoldString, Help: "target name used by ebigent build and ebigent dev"},
				{Key: "kind", Kind: configbind.ScaffoldString, Default: "client", Help: "client, listen, dedicated, or simulation"},
				{Key: "entry", Kind: configbind.ScaffoldString, Help: "main package path, such as ./cmd/game"},
				{Key: "goos", Kind: configbind.ScaffoldString, Help: "target GOOS; empty follows the host"},
				{Key: "goarch", Kind: configbind.ScaffoldString, Help: "target GOARCH; empty follows the host"},
				{Key: "tags", Kind: configbind.ScaffoldStringSlice, Help: "Tags are build tags. Linkage only: rule:build-tag-only-for-linkage keeps behavior out of tags, so nothing here may select a game rule or a synchronization mode"},
				{Key: "dev", Kind: configbind.ScaffoldBool, Default: "false", Help: "this target links the dev debug endpoint and must not ship"},
			}},
		},
	})
}

func applyBuildDefinition2(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Build)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Build: bad destination")
	}
	if ta1, ok := o.Get("build.target"); ok {
		if !ta1.IsTables {
			return fmt.Errorf("configbind: build.target: expected an array of tables ([[build.target]])")
		}
		p.Target = make([]Target, len(ta1.Tables))
		for i1 := range ta1.Tables {
			if v, ok := ta1.Tables[i1].GetString("name"); ok {
				p.Target[i1].Name = v
			}
			if v, ok := ta1.Tables[i1].GetString("kind"); ok {
				p.Target[i1].Kind = v
			} else {
				p.Target[i1].Kind = "client"
			}
			if v, ok := ta1.Tables[i1].GetString("entry"); ok {
				p.Target[i1].Entry = v
			}
			if v, ok := ta1.Tables[i1].GetString("goos"); ok {
				p.Target[i1].GOOS = v
			}
			if v, ok := ta1.Tables[i1].GetString("goarch"); ok {
				p.Target[i1].GOARCH = v
			}
			if v, ok := ta1.Tables[i1].GetMulti("tags"); ok {
				p.Target[i1].Tags = v
			}
			if v, ok := ta1.Tables[i1].GetString("dev"); ok {
				bb, err := strconv.ParseBool(v)
				if err != nil {
					return fmt.Errorf("configbind: build.target[%d].dev: %w", i1, err)
				}
				p.Target[i1].Dev = bb
			} else {
				p.Target[i1].Dev = false
			}
		}
	}
	return nil
}

func registerDevDefinition3() {
	configbind.Register[Dev](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Dev",
		Prefix:   "dev",
		Doc:      "Dev is the [dev] table: how ebigent dev runs flow:dev-rebuild-loop",
		KnownKeys: []string{
			"dev.target",
			"dev.watch",
			"dev.ignore",
			"dev.debounce",
			"dev.console",
		},
		Defaults: map[string]string{
			"dev.debounce": "200ms",
			"dev.console":  "127.0.0.1:8930",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "dev", Key: "target", Help: "target ebigent dev builds and runs; empty requires exactly one declared target"},
			{Prefix: "dev", Key: "watch", Help: "source roots watched for changes; empty watches the project root", Kind: cliparser.KindArray},
			{Prefix: "dev", Key: "ignore", Help: "glob patterns never watched", Kind: cliparser.KindArray},
			{Prefix: "dev", Key: "debounce", Help: "quiet period before a rebuild"},
			{Prefix: "dev", Key: "console", Help: "dev console listen address; empty disables the console"},
		},
		Apply: applyDevDefinition3,
		Scaffold: []configbind.ScaffoldField{
			{Key: "target", Kind: configbind.ScaffoldString, Help: "target ebigent dev builds and runs; empty requires exactly one declared target"},
			{Key: "watch", Kind: configbind.ScaffoldStringSlice, Help: "source roots watched for changes; empty watches the project root"},
			{Key: "ignore", Kind: configbind.ScaffoldStringSlice, Help: "glob patterns never watched"},
			{Key: "debounce", Kind: configbind.ScaffoldDuration, Default: "200ms", Help: "quiet period before a rebuild"},
			{Key: "console", Kind: configbind.ScaffoldString, Default: "127.0.0.1:8930", Help: "dev console listen address; empty disables the console"},
		},
	})
}

func applyDevDefinition3(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Dev)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Dev: bad destination")
	}
	if v, ok := o.GetString("dev.target"); ok {
		p.Target = v
	}
	if v, ok := o.GetMulti("dev.watch"); ok {
		p.Watch = v
	}
	if v, ok := o.GetMulti("dev.ignore"); ok {
		p.Ignore = v
	}
	if v, ok := o.GetString("dev.debounce"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("configbind: dev.debounce: %w", err)
		}
		p.Debounce = d
	} else {
		p.Debounce = 200000000 // 200ms
	}
	if v, ok := o.GetString("dev.console"); ok {
		p.Console = v
	} else {
		p.Console = "127.0.0.1:8930"
	}
	return nil
}

func registerBehaviorDefinition4() {
	configbind.Register[Behavior](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/buildconf.Behavior",
		Prefix:   "behavior",
		Doc:      "Behavior is the [behavior] table: where the AI pipeline keeps its files. decision:ai-pipeline-always-scaffolded means these paths exist in every generated project, whether or not the pipeline is in use",
		KnownKeys: []string{
			"behavior.library",
			"behavior.corpus",
		},
		Defaults: map[string]string{
			"behavior.library": "behavior/chips.json",
			"behavior.corpus":  "corpus",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "behavior", Key: "library", Help: "chip library file"},
			{Prefix: "behavior", Key: "corpus", Help: "episode corpus root"},
		},
		Apply: applyBehaviorDefinition4,
		Scaffold: []configbind.ScaffoldField{
			{Key: "library", Kind: configbind.ScaffoldString, Default: "behavior/chips.json", Help: "chip library file"},
			{Key: "corpus", Kind: configbind.ScaffoldString, Default: "corpus", Help: "episode corpus root"},
		},
	})
}

func applyBehaviorDefinition4(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Behavior)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Behavior: bad destination")
	}
	if v, ok := o.GetString("behavior.library"); ok {
		p.Library = v
	} else {
		p.Library = "behavior/chips.json"
	}
	if v, ok := o.GetString("behavior.corpus"); ok {
		p.Corpus = v
	} else {
		p.Corpus = "corpus"
	}
	return nil
}
