// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:b0b9195cc78560bd200a8733f6346db35d5723f4cd38a193a83ed2021c2fc766 self=sha256:dd94930ccc7445d59ae7091cd7a8fb8835d67a6eac8243502fdc86f87ce350a3 outputs=tinybind_gen.go,configbind_gen.go

package buildconf
