// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:dc744cae194d27a290421ad80463fa6702e7ed286e274a0a9ef9974e92d500e6 self=sha256:dd94930ccc7445d59ae7091cd7a8fb8835d67a6eac8243502fdc86f87ce350a3 outputs=tinybind_gen.go,configbind_gen.go

package buildconf
