// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:f83c0d45c8905664b9dc3b088bcba90b74c05b5d4299d1a09e9f895c6baa64d9 self=sha256:dd94930ccc7445d59ae7091cd7a8fb8835d67a6eac8243502fdc86f87ce350a3 outputs=tinybind_gen.go,configbind_gen.go

package buildconf
