// Code generated by tinybind; DO NOT EDIT.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// cborWireProfile is the profile the wire codecs below were generated
// for. It is pinned here rather than taken from the caller: the two ends of
// a connection must not disagree about which profile is in use.
var cborWireProfile = cbor.Wire()

// cborWorldProfile is the profile the world codecs below were generated for.
var cborWorldProfile = cbor.World()

// CBORProtocolVersion identifies the wire shape of every codec in this file.
// It is derived from CBORSchema and covers wire-observable shape alone, so
// regenerating with a newer tinybind that emits the same bytes leaves it
// unchanged, and any change that moves one byte moves it.
const CBORProtocolVersion = "0486c54a8e152e99"

// CBORSchema is the canonical description CBORProtocolVersion digests.
const CBORSchema = `type ActionInput wire
  uint32
  uint8
  uint8
  uint8
  uint8
type Adventurer world
keys int
  1 uint16
  2 uint8
  3 uint8
  4 uint8
  5 int8
  6 bool
  7 bool
type AdventurerView world
keys int
  1 uint64
  2 uint16
  3 uint8
  4 int8
  5 uint8
  6 uint8
  7 bool
  8 bytes
  9 bytes
  10 []struct PartyMate
  11 []struct Trap
  12 uint8
  13 uint8
  14 uint8
  15 uint8
  16 bool
  17 uint8
type DMView world
keys int
  1 uint64
  2 bytes
  3 bytes
  4 []struct Adventurer
  5 []struct Trap
  6 uint8
  7 uint8
  8 uint8
  9 uint8
  10 uint8
  11 bool
  12 uint8
type DungeonState world
keys int
  1 uint64
  2 bytes
  3 bytes
  4 []struct Adventurer
  5 []struct Trap
  6 uint8
  7 uint8
  8 uint8
  9 uint8
  10 uint8
  11 uint32
  12 bool
  13 uint8
type PartyMate world
keys int
  1 uint16
  2 uint8
  3 uint8
  4 uint8
  5 bool
  6 bool
type Trap world
keys int
  1 uint32
  2 uint8
  3 uint8
  4 bool
  5 bool
`

// appendActionInputCBORWire appends v as one wire-profile CBOR item.
//
// The array is 5 long and its order is the declaration order of ActionInput.
// Both are part of the protocol: a reader counts on the position.
func appendActionInputCBORWire(dst []byte, v ActionInput) []byte {
	dst = cbor.AppendArrayHeader(dst, 5)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, uint64(v.Kind))
	dst = cbor.AppendUint(dst, uint64(v.Dir))
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, uint64(v.Y))
	return dst
}

// decodeActionInputCBORWire decodes one wire-profile CBOR item into v.
//
// The array must be exactly 5 long. Under the wire profile a field the
// schema does not know cannot exist, so a count that disagrees is refused
// rather than read past: the two ends are running different protocols.
func decodeActionInputCBORWire(r *cbor.Reader, v *ActionInput) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n != 5 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "ActionInput", Err: cbor.ErrUnexpectedToken}
	}
	{
		x, err := r.ReadUint32()
		if err != nil {
			return err
		}
		v.Tick = x
	}
	{
		x, err := r.ReadUint8()
		if err != nil {
			return err
		}
		v.Kind = x
	}
	{
		x, err := r.ReadUint8()
		if err != nil {
			return err
		}
		v.Dir = x
	}
	{
		x, err := r.ReadUint8()
		if err != nil {
			return err
		}
		v.X = x
	}
	{
		x, err := r.ReadUint8()
		if err != nil {
			return err
		}
		v.Y = x
	}
	return nil
}

// AppendCBORTo appends v as one wire-profile CBOR item, satisfying cbor.Appender.
func (v ActionInput) AppendCBORTo(dst []byte) []byte {
	return appendActionInputCBORWire(dst, v)
}

// DecodeCBORFrom decodes one wire-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *ActionInput) DecodeCBORFrom(data []byte) error {
	r := cborWireProfile.ReaderOver(data)
	if err := decodeActionInputCBORWire(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// appendAdventurerCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendAdventurerCBORWorld(dst []byte, v Adventurer) []byte {
	dst = cbor.AppendMapHeader(dst, 7)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.Role))
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendInt(dst, int64(v.HP))
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendBool(dst, bool(v.Alive))
	dst = cbor.AppendUint(dst, 7)
	dst = cbor.AppendBool(dst, bool(v.Carrying))
	return dst
}

// decodeAdventurerCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeAdventurerCBORWorld(r *cbor.Reader, v *Adventurer) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "Adventurer", Err: cbor.ErrUnexpectedToken}
	}
	*v = Adventurer{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.X = x
			}
		case 3:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Y = x
			}
		case 4:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Role = x
			}
		case 5:
			{
				x, err := r.ReadInt8()
				if err != nil {
					return err
				}
				v.HP = x
			}
		case 6:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Alive = x
			}
		case 7:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Carrying = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// appendAdventurerViewCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendAdventurerViewCBORWorld(dst []byte, v AdventurerView) []byte {
	dst = cbor.AppendMapHeader(dst, 17)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendUint(dst, uint64(v.You))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Role))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendInt(dst, int64(v.HP))
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendUint(dst, 7)
	dst = cbor.AppendBool(dst, bool(v.Carrying))
	dst = cbor.AppendUint(dst, 8)
	dst = cbor.AppendBytes(dst, []byte(v.Explored))
	dst = cbor.AppendUint(dst, 9)
	dst = cbor.AppendBytes(dst, []byte(v.KnownWalls))
	dst = cbor.AppendUint(dst, 10)
	dst = cbor.AppendArrayHeader(dst, len(v.Party))
	for i0 := range v.Party {
		dst = appendPartyMateCBORWorld(dst, v.Party[i0])
	}
	dst = cbor.AppendUint(dst, 11)
	dst = cbor.AppendArrayHeader(dst, len(v.KnownTraps))
	for i0 := range v.KnownTraps {
		dst = appendTrapCBORWorld(dst, v.KnownTraps[i0])
	}
	dst = cbor.AppendUint(dst, 12)
	dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	dst = cbor.AppendUint(dst, 13)
	dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	dst = cbor.AppendUint(dst, 14)
	dst = cbor.AppendUint(dst, uint64(v.ExitX))
	dst = cbor.AppendUint(dst, 15)
	dst = cbor.AppendUint(dst, uint64(v.ExitY))
	dst = cbor.AppendUint(dst, 16)
	dst = cbor.AppendBool(dst, bool(v.Over))
	dst = cbor.AppendUint(dst, 17)
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	return dst
}

// decodeAdventurerViewCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeAdventurerViewCBORWorld(r *cbor.Reader, v *AdventurerView) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerView", Err: cbor.ErrUnexpectedToken}
	}
	*v = AdventurerView{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint64()
				if err != nil {
					return err
				}
				v.Tick = x
			}
		case 2:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.You = x
			}
		case 3:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Role = x
			}
		case 4:
			{
				x, err := r.ReadInt8()
				if err != nil {
					return err
				}
				v.HP = x
			}
		case 5:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.X = x
			}
		case 6:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Y = x
			}
		case 7:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Carrying = x
			}
		case 8:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.Explored = append(v.Explored[:0], x...)
			}
		case 9:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.KnownWalls = append(v.KnownWalls[:0], x...)
			}
		case 10:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerView.Party", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Party) >= n0 {
					v.Party = v.Party[:n0]
				} else {
					v.Party = make([]PartyMate, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodePartyMateCBORWorld(r, &v.Party[i0]); err != nil {
						return err
					}
				}
			}
		case 11:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerView.KnownTraps", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.KnownTraps) >= n0 {
					v.KnownTraps = v.KnownTraps[:n0]
				} else {
					v.KnownTraps = make([]Trap, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodeTrapCBORWorld(r, &v.KnownTraps[i0]); err != nil {
						return err
					}
				}
			}
		case 12:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TreasureX = x
			}
		case 13:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TreasureY = x
			}
		case 14:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.ExitX = x
			}
		case 15:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.ExitY = x
			}
		case 16:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Over = x
			}
		case 17:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Winner = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// AppendCBORTo appends v as one world-profile CBOR item, satisfying cbor.Appender.
func (v AdventurerView) AppendCBORTo(dst []byte) []byte {
	return appendAdventurerViewCBORWorld(dst, v)
}

// DecodeCBORFrom decodes one world-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *AdventurerView) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeAdventurerViewCBORWorld(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// appendDMViewCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendDMViewCBORWorld(dst []byte, v DMView) []byte {
	dst = cbor.AppendMapHeader(dst, 12)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendBytes(dst, []byte(v.Walls))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendBytes(dst, []byte(v.Explored))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendArrayHeader(dst, len(v.Adventurers))
	for i0 := range v.Adventurers {
		dst = appendAdventurerCBORWorld(dst, v.Adventurers[i0])
	}
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendArrayHeader(dst, len(v.Traps))
	for i0 := range v.Traps {
		dst = appendTrapCBORWorld(dst, v.Traps[i0])
	}
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendUint(dst, uint64(v.TrapBudget))
	dst = cbor.AppendUint(dst, 7)
	dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	dst = cbor.AppendUint(dst, 8)
	dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	dst = cbor.AppendUint(dst, 9)
	dst = cbor.AppendUint(dst, uint64(v.ExitX))
	dst = cbor.AppendUint(dst, 10)
	dst = cbor.AppendUint(dst, uint64(v.ExitY))
	dst = cbor.AppendUint(dst, 11)
	dst = cbor.AppendBool(dst, bool(v.Over))
	dst = cbor.AppendUint(dst, 12)
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	return dst
}

// decodeDMViewCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeDMViewCBORWorld(r *cbor.Reader, v *DMView) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "DMView", Err: cbor.ErrUnexpectedToken}
	}
	*v = DMView{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint64()
				if err != nil {
					return err
				}
				v.Tick = x
			}
		case 2:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.Walls = append(v.Walls[:0], x...)
			}
		case 3:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.Explored = append(v.Explored[:0], x...)
			}
		case 4:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "DMView.Adventurers", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Adventurers) >= n0 {
					v.Adventurers = v.Adventurers[:n0]
				} else {
					v.Adventurers = make([]Adventurer, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodeAdventurerCBORWorld(r, &v.Adventurers[i0]); err != nil {
						return err
					}
				}
			}
		case 5:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "DMView.Traps", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Traps) >= n0 {
					v.Traps = v.Traps[:n0]
				} else {
					v.Traps = make([]Trap, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodeTrapCBORWorld(r, &v.Traps[i0]); err != nil {
						return err
					}
				}
			}
		case 6:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TrapBudget = x
			}
		case 7:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TreasureX = x
			}
		case 8:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TreasureY = x
			}
		case 9:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.ExitX = x
			}
		case 10:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.ExitY = x
			}
		case 11:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Over = x
			}
		case 12:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Winner = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// AppendCBORTo appends v as one world-profile CBOR item, satisfying cbor.Appender.
func (v DMView) AppendCBORTo(dst []byte) []byte {
	return appendDMViewCBORWorld(dst, v)
}

// DecodeCBORFrom decodes one world-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *DMView) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeDMViewCBORWorld(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// appendDungeonStateCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendDungeonStateCBORWorld(dst []byte, v DungeonState) []byte {
	dst = cbor.AppendMapHeader(dst, 13)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendBytes(dst, []byte(v.Walls))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendBytes(dst, []byte(v.Explored))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendArrayHeader(dst, len(v.Adventurers))
	for i0 := range v.Adventurers {
		dst = appendAdventurerCBORWorld(dst, v.Adventurers[i0])
	}
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendArrayHeader(dst, len(v.Traps))
	for i0 := range v.Traps {
		dst = appendTrapCBORWorld(dst, v.Traps[i0])
	}
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendUint(dst, uint64(v.TrapBudget))
	dst = cbor.AppendUint(dst, 7)
	dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	dst = cbor.AppendUint(dst, 8)
	dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	dst = cbor.AppendUint(dst, 9)
	dst = cbor.AppendUint(dst, uint64(v.ExitX))
	dst = cbor.AppendUint(dst, 10)
	dst = cbor.AppendUint(dst, uint64(v.ExitY))
	dst = cbor.AppendUint(dst, 11)
	dst = cbor.AppendUint(dst, uint64(v.TickLimit))
	dst = cbor.AppendUint(dst, 12)
	dst = cbor.AppendBool(dst, bool(v.Over))
	dst = cbor.AppendUint(dst, 13)
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	return dst
}

// decodeDungeonStateCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeDungeonStateCBORWorld(r *cbor.Reader, v *DungeonState) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "DungeonState", Err: cbor.ErrUnexpectedToken}
	}
	*v = DungeonState{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint64()
				if err != nil {
					return err
				}
				v.Tick = x
			}
		case 2:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.Walls = append(v.Walls[:0], x...)
			}
		case 3:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.Explored = append(v.Explored[:0], x...)
			}
		case 4:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "DungeonState.Adventurers", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Adventurers) >= n0 {
					v.Adventurers = v.Adventurers[:n0]
				} else {
					v.Adventurers = make([]Adventurer, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodeAdventurerCBORWorld(r, &v.Adventurers[i0]); err != nil {
						return err
					}
				}
			}
		case 5:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "DungeonState.Traps", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Traps) >= n0 {
					v.Traps = v.Traps[:n0]
				} else {
					v.Traps = make([]Trap, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodeTrapCBORWorld(r, &v.Traps[i0]); err != nil {
						return err
					}
				}
			}
		case 6:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TrapBudget = x
			}
		case 7:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TreasureX = x
			}
		case 8:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.TreasureY = x
			}
		case 9:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.ExitX = x
			}
		case 10:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.ExitY = x
			}
		case 11:
			{
				x, err := r.ReadUint32()
				if err != nil {
					return err
				}
				v.TickLimit = x
			}
		case 12:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Over = x
			}
		case 13:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Winner = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// AppendCBORTo appends v as one world-profile CBOR item, satisfying cbor.Appender.
func (v DungeonState) AppendCBORTo(dst []byte) []byte {
	return appendDungeonStateCBORWorld(dst, v)
}

// DecodeCBORFrom decodes one world-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *DungeonState) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeDungeonStateCBORWorld(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// appendPartyMateCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendPartyMateCBORWorld(dst []byte, v PartyMate) []byte {
	dst = cbor.AppendMapHeader(dst, 6)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.Role))
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendBool(dst, bool(v.Alive))
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendBool(dst, bool(v.Carrying))
	return dst
}

// decodePartyMateCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodePartyMateCBORWorld(r *cbor.Reader, v *PartyMate) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PartyMate", Err: cbor.ErrUnexpectedToken}
	}
	*v = PartyMate{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.X = x
			}
		case 3:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Y = x
			}
		case 4:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Role = x
			}
		case 5:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Alive = x
			}
		case 6:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Carrying = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// appendTrapCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendTrapCBORWorld(dst []byte, v Trap) []byte {
	dst = cbor.AppendMapHeader(dst, 5)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendBool(dst, bool(v.Armed))
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendBool(dst, bool(v.Discovered))
	return dst
}

// decodeTrapCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeTrapCBORWorld(r *cbor.Reader, v *Trap) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "Trap", Err: cbor.ErrUnexpectedToken}
	}
	*v = Trap{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint32()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.X = x
			}
		case 3:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Y = x
			}
		case 4:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Armed = x
			}
		case 5:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Discovered = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// AdventurerDelta is what changed between two Adventurer values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type AdventurerDelta struct {
	Present uint64
	// bit 0
	X uint8
	// bit 1
	Y uint8
	// bit 2
	Role uint8
	// bit 3
	HP int8
	// bit 4
	Alive bool
	// bit 5
	Carrying bool
}

// diffAdventurerInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffAdventurerInto(d *AdventurerDelta, baseline, current Adventurer) bool {
	d.Present = 0
	if baseline.X != current.X {
		d.Present |= 1 << 0
		d.X = current.X
	}
	if baseline.Y != current.Y {
		d.Present |= 1 << 1
		d.Y = current.Y
	}
	if baseline.Role != current.Role {
		d.Present |= 1 << 2
		d.Role = current.Role
	}
	if baseline.HP != current.HP {
		d.Present |= 1 << 3
		d.HP = current.HP
	}
	if baseline.Alive != current.Alive {
		d.Present |= 1 << 4
		d.Alive = current.Alive
	}
	if baseline.Carrying != current.Carrying {
		d.Present |= 1 << 5
		d.Carrying = current.Carrying
	}
	return d.Present != 0
}

// applyAdventurerDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyAdventurerDelta(v *Adventurer, d AdventurerDelta) error {
	if d.Present&(1<<0) != 0 {
		v.X = d.X
	}
	if d.Present&(1<<1) != 0 {
		v.Y = d.Y
	}
	if d.Present&(1<<2) != 0 {
		v.Role = d.Role
	}
	if d.Present&(1<<3) != 0 {
		v.HP = d.HP
	}
	if d.Present&(1<<4) != 0 {
		v.Alive = d.Alive
	}
	if d.Present&(1<<5) != 0 {
		v.Carrying = d.Carrying
	}
	return nil
}

// appendAdventurerDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendAdventurerDeltaCBOR(dst []byte, v AdventurerDelta) []byte {
	n := 1
	for bit := 0; bit < 6; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.X))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Y))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Role))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendInt(dst, int64(v.HP))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Alive))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Carrying))
	}
	return dst
}

// decodeAdventurerDeltaCBOR reads one delta into v.
func decodeAdventurerDeltaCBOR(r *cbor.Reader, v *AdventurerDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.X = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Y = x
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Role = x
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadInt8()
			if err != nil {
				return err
			}
			v.HP = x
		}
		read++
	}
	if present&(1<<4) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Alive = x
		}
		read++
	}
	if present&(1<<5) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Carrying = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// AdventurerViewDelta is what changed between two AdventurerView values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type AdventurerViewDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	You uint16
	// bit 2
	Role uint8
	// bit 3
	HP int8
	// bit 4
	X uint8
	// bit 5
	Y uint8
	// bit 6
	Carrying bool
	// bit 7
	Explored []uint8
	// bit 8
	KnownWalls []uint8
	// bit 9
	Party PartyMateListDelta
	// bit 10
	KnownTraps TrapListDelta
	// bit 11
	TreasureX uint8
	// bit 12
	TreasureY uint8
	// bit 13
	ExitX uint8
	// bit 14
	ExitY uint8
	// bit 15
	Over bool
	// bit 16
	Winner uint8
}

// diffAdventurerViewInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffAdventurerViewInto(d *AdventurerViewDelta, baseline, current AdventurerView) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if baseline.You != current.You {
		d.Present |= 1 << 1
		d.You = current.You
	}
	if baseline.Role != current.Role {
		d.Present |= 1 << 2
		d.Role = current.Role
	}
	if baseline.HP != current.HP {
		d.Present |= 1 << 3
		d.HP = current.HP
	}
	if baseline.X != current.X {
		d.Present |= 1 << 4
		d.X = current.X
	}
	if baseline.Y != current.Y {
		d.Present |= 1 << 5
		d.Y = current.Y
	}
	if baseline.Carrying != current.Carrying {
		d.Present |= 1 << 6
		d.Carrying = current.Carrying
	}
	if string(baseline.Explored) != string(current.Explored) {
		d.Present |= 1 << 7
		d.Explored = current.Explored
	}
	if string(baseline.KnownWalls) != string(current.KnownWalls) {
		d.Present |= 1 << 8
		d.KnownWalls = current.KnownWalls
	}
	if diffPartyMateListInto(&d.Party, baseline.Party, current.Party) {
		d.Present |= 1 << 9
	}
	if diffTrapListInto(&d.KnownTraps, baseline.KnownTraps, current.KnownTraps) {
		d.Present |= 1 << 10
	}
	if baseline.TreasureX != current.TreasureX {
		d.Present |= 1 << 11
		d.TreasureX = current.TreasureX
	}
	if baseline.TreasureY != current.TreasureY {
		d.Present |= 1 << 12
		d.TreasureY = current.TreasureY
	}
	if baseline.ExitX != current.ExitX {
		d.Present |= 1 << 13
		d.ExitX = current.ExitX
	}
	if baseline.ExitY != current.ExitY {
		d.Present |= 1 << 14
		d.ExitY = current.ExitY
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 15
		d.Over = current.Over
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 16
		d.Winner = current.Winner
	}
	return d.Present != 0
}

// applyAdventurerViewDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyAdventurerViewDelta(v *AdventurerView, d AdventurerViewDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.You = d.You
	}
	if d.Present&(1<<2) != 0 {
		v.Role = d.Role
	}
	if d.Present&(1<<3) != 0 {
		v.HP = d.HP
	}
	if d.Present&(1<<4) != 0 {
		v.X = d.X
	}
	if d.Present&(1<<5) != 0 {
		v.Y = d.Y
	}
	if d.Present&(1<<6) != 0 {
		v.Carrying = d.Carrying
	}
	if d.Present&(1<<7) != 0 {
		v.Explored = d.Explored
	}
	if d.Present&(1<<8) != 0 {
		v.KnownWalls = d.KnownWalls
	}
	if d.Present&(1<<9) != 0 {
		if err := applyPartyMateListDelta(&v.Party, d.Party); err != nil {
			return err
		}
	}
	if d.Present&(1<<10) != 0 {
		if err := applyTrapListDelta(&v.KnownTraps, d.KnownTraps); err != nil {
			return err
		}
	}
	if d.Present&(1<<11) != 0 {
		v.TreasureX = d.TreasureX
	}
	if d.Present&(1<<12) != 0 {
		v.TreasureY = d.TreasureY
	}
	if d.Present&(1<<13) != 0 {
		v.ExitX = d.ExitX
	}
	if d.Present&(1<<14) != 0 {
		v.ExitY = d.ExitY
	}
	if d.Present&(1<<15) != 0 {
		v.Over = d.Over
	}
	if d.Present&(1<<16) != 0 {
		v.Winner = d.Winner
	}
	return nil
}

// appendAdventurerViewDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendAdventurerViewDeltaCBOR(dst []byte, v AdventurerViewDelta) []byte {
	n := 1
	for bit := 0; bit < 17; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.You))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Role))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendInt(dst, int64(v.HP))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.X))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Y))
	}
	if v.Present&(1<<6) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Carrying))
	}
	if v.Present&(1<<7) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Explored))
	}
	if v.Present&(1<<8) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.KnownWalls))
	}
	if v.Present&(1<<9) != 0 {
		dst = appendPartyMateListDeltaCBOR(dst, v.Party)
	}
	if v.Present&(1<<10) != 0 {
		dst = appendTrapListDeltaCBOR(dst, v.KnownTraps)
	}
	if v.Present&(1<<11) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	}
	if v.Present&(1<<12) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	}
	if v.Present&(1<<13) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ExitX))
	}
	if v.Present&(1<<14) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ExitY))
	}
	if v.Present&(1<<15) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	if v.Present&(1<<16) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	return dst
}

// decodeAdventurerViewDeltaCBOR reads one delta into v.
func decodeAdventurerViewDeltaCBOR(r *cbor.Reader, v *AdventurerViewDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerViewDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint64()
			if err != nil {
				return err
			}
			v.Tick = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadUint16()
			if err != nil {
				return err
			}
			v.You = x
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Role = x
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadInt8()
			if err != nil {
				return err
			}
			v.HP = x
		}
		read++
	}
	if present&(1<<4) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.X = x
		}
		read++
	}
	if present&(1<<5) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Y = x
		}
		read++
	}
	if present&(1<<6) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Carrying = x
		}
		read++
	}
	if present&(1<<7) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.Explored = append(v.Explored[:0], x...)
		}
		read++
	}
	if present&(1<<8) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.KnownWalls = append(v.KnownWalls[:0], x...)
		}
		read++
	}
	if present&(1<<9) != 0 {
		if err := decodePartyMateListDeltaCBOR(r, &v.Party); err != nil {
			return err
		}
		read++
	}
	if present&(1<<10) != 0 {
		if err := decodeTrapListDeltaCBOR(r, &v.KnownTraps); err != nil {
			return err
		}
		read++
	}
	if present&(1<<11) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TreasureX = x
		}
		read++
	}
	if present&(1<<12) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TreasureY = x
		}
		read++
	}
	if present&(1<<13) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.ExitX = x
		}
		read++
	}
	if present&(1<<14) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.ExitY = x
		}
		read++
	}
	if present&(1<<15) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Over = x
		}
		read++
	}
	if present&(1<<16) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Winner = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// DiffAdventurerView reports what changed between baseline and current.
//
// Use DiffAdventurerViewInto in a loop that runs per tick: it fills a delta the caller
// retains, and reuses its collection capacity, so the steady state allocates
// nothing.
func DiffAdventurerView(baseline, current AdventurerView) AdventurerViewDelta {
	var d AdventurerViewDelta
	diffAdventurerViewInto(&d, baseline, current)
	return d
}

// DiffAdventurerViewInto is DiffAdventurerView into a delta the caller owns and reuses.
func DiffAdventurerViewInto(d *AdventurerViewDelta, baseline, current AdventurerView) {
	diffAdventurerViewInto(d, baseline, current)
}

// ApplyAdventurerViewDelta puts d back onto v.
//
// It reports an error when the delta names an entity v does not hold, which
// means v is not the baseline the delta was diffed against.
func ApplyAdventurerViewDelta(v *AdventurerView, d AdventurerViewDelta) error {
	return applyAdventurerViewDelta(v, d)
}

// AppendCBORTo appends the delta as one CBOR item, satisfying cbor.Appender.
func (v AdventurerViewDelta) AppendCBORTo(dst []byte) []byte {
	return appendAdventurerViewDeltaCBOR(dst, v)
}

// DecodeCBORFrom reads one delta into v, satisfying cbor.Decodable.
func (v *AdventurerViewDelta) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeAdventurerViewDeltaCBOR(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// DMViewDelta is what changed between two DMView values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type DMViewDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	Walls []uint8
	// bit 2
	Explored []uint8
	// bit 3
	Adventurers AdventurerListDelta
	// bit 4
	Traps TrapListDelta
	// bit 5
	TrapBudget uint8
	// bit 6
	TreasureX uint8
	// bit 7
	TreasureY uint8
	// bit 8
	ExitX uint8
	// bit 9
	ExitY uint8
	// bit 10
	Over bool
	// bit 11
	Winner uint8
}

// diffDMViewInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffDMViewInto(d *DMViewDelta, baseline, current DMView) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if string(baseline.Walls) != string(current.Walls) {
		d.Present |= 1 << 1
		d.Walls = current.Walls
	}
	if string(baseline.Explored) != string(current.Explored) {
		d.Present |= 1 << 2
		d.Explored = current.Explored
	}
	if diffAdventurerListInto(&d.Adventurers, baseline.Adventurers, current.Adventurers) {
		d.Present |= 1 << 3
	}
	if diffTrapListInto(&d.Traps, baseline.Traps, current.Traps) {
		d.Present |= 1 << 4
	}
	if baseline.TrapBudget != current.TrapBudget {
		d.Present |= 1 << 5
		d.TrapBudget = current.TrapBudget
	}
	if baseline.TreasureX != current.TreasureX {
		d.Present |= 1 << 6
		d.TreasureX = current.TreasureX
	}
	if baseline.TreasureY != current.TreasureY {
		d.Present |= 1 << 7
		d.TreasureY = current.TreasureY
	}
	if baseline.ExitX != current.ExitX {
		d.Present |= 1 << 8
		d.ExitX = current.ExitX
	}
	if baseline.ExitY != current.ExitY {
		d.Present |= 1 << 9
		d.ExitY = current.ExitY
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 10
		d.Over = current.Over
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 11
		d.Winner = current.Winner
	}
	return d.Present != 0
}

// applyDMViewDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyDMViewDelta(v *DMView, d DMViewDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.Walls = d.Walls
	}
	if d.Present&(1<<2) != 0 {
		v.Explored = d.Explored
	}
	if d.Present&(1<<3) != 0 {
		if err := applyAdventurerListDelta(&v.Adventurers, d.Adventurers); err != nil {
			return err
		}
	}
	if d.Present&(1<<4) != 0 {
		if err := applyTrapListDelta(&v.Traps, d.Traps); err != nil {
			return err
		}
	}
	if d.Present&(1<<5) != 0 {
		v.TrapBudget = d.TrapBudget
	}
	if d.Present&(1<<6) != 0 {
		v.TreasureX = d.TreasureX
	}
	if d.Present&(1<<7) != 0 {
		v.TreasureY = d.TreasureY
	}
	if d.Present&(1<<8) != 0 {
		v.ExitX = d.ExitX
	}
	if d.Present&(1<<9) != 0 {
		v.ExitY = d.ExitY
	}
	if d.Present&(1<<10) != 0 {
		v.Over = d.Over
	}
	if d.Present&(1<<11) != 0 {
		v.Winner = d.Winner
	}
	return nil
}

// appendDMViewDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendDMViewDeltaCBOR(dst []byte, v DMViewDelta) []byte {
	n := 1
	for bit := 0; bit < 12; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Walls))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Explored))
	}
	if v.Present&(1<<3) != 0 {
		dst = appendAdventurerListDeltaCBOR(dst, v.Adventurers)
	}
	if v.Present&(1<<4) != 0 {
		dst = appendTrapListDeltaCBOR(dst, v.Traps)
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TrapBudget))
	}
	if v.Present&(1<<6) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	}
	if v.Present&(1<<7) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	}
	if v.Present&(1<<8) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ExitX))
	}
	if v.Present&(1<<9) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ExitY))
	}
	if v.Present&(1<<10) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	if v.Present&(1<<11) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	return dst
}

// decodeDMViewDeltaCBOR reads one delta into v.
func decodeDMViewDeltaCBOR(r *cbor.Reader, v *DMViewDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "DMViewDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint64()
			if err != nil {
				return err
			}
			v.Tick = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.Walls = append(v.Walls[:0], x...)
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.Explored = append(v.Explored[:0], x...)
		}
		read++
	}
	if present&(1<<3) != 0 {
		if err := decodeAdventurerListDeltaCBOR(r, &v.Adventurers); err != nil {
			return err
		}
		read++
	}
	if present&(1<<4) != 0 {
		if err := decodeTrapListDeltaCBOR(r, &v.Traps); err != nil {
			return err
		}
		read++
	}
	if present&(1<<5) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TrapBudget = x
		}
		read++
	}
	if present&(1<<6) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TreasureX = x
		}
		read++
	}
	if present&(1<<7) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TreasureY = x
		}
		read++
	}
	if present&(1<<8) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.ExitX = x
		}
		read++
	}
	if present&(1<<9) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.ExitY = x
		}
		read++
	}
	if present&(1<<10) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Over = x
		}
		read++
	}
	if present&(1<<11) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Winner = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// DiffDMView reports what changed between baseline and current.
//
// Use DiffDMViewInto in a loop that runs per tick: it fills a delta the caller
// retains, and reuses its collection capacity, so the steady state allocates
// nothing.
func DiffDMView(baseline, current DMView) DMViewDelta {
	var d DMViewDelta
	diffDMViewInto(&d, baseline, current)
	return d
}

// DiffDMViewInto is DiffDMView into a delta the caller owns and reuses.
func DiffDMViewInto(d *DMViewDelta, baseline, current DMView) {
	diffDMViewInto(d, baseline, current)
}

// ApplyDMViewDelta puts d back onto v.
//
// It reports an error when the delta names an entity v does not hold, which
// means v is not the baseline the delta was diffed against.
func ApplyDMViewDelta(v *DMView, d DMViewDelta) error {
	return applyDMViewDelta(v, d)
}

// AppendCBORTo appends the delta as one CBOR item, satisfying cbor.Appender.
func (v DMViewDelta) AppendCBORTo(dst []byte) []byte {
	return appendDMViewDeltaCBOR(dst, v)
}

// DecodeCBORFrom reads one delta into v, satisfying cbor.Decodable.
func (v *DMViewDelta) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeDMViewDeltaCBOR(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// DungeonStateDelta is what changed between two DungeonState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type DungeonStateDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	Walls []uint8
	// bit 2
	Explored []uint8
	// bit 3
	Adventurers AdventurerListDelta
	// bit 4
	Traps TrapListDelta
	// bit 5
	TrapBudget uint8
	// bit 6
	TreasureX uint8
	// bit 7
	TreasureY uint8
	// bit 8
	ExitX uint8
	// bit 9
	ExitY uint8
	// bit 10
	TickLimit uint32
	// bit 11
	Over bool
	// bit 12
	Winner uint8
}

// diffDungeonStateInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffDungeonStateInto(d *DungeonStateDelta, baseline, current DungeonState) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if string(baseline.Walls) != string(current.Walls) {
		d.Present |= 1 << 1
		d.Walls = current.Walls
	}
	if string(baseline.Explored) != string(current.Explored) {
		d.Present |= 1 << 2
		d.Explored = current.Explored
	}
	if diffAdventurerListInto(&d.Adventurers, baseline.Adventurers, current.Adventurers) {
		d.Present |= 1 << 3
	}
	if diffTrapListInto(&d.Traps, baseline.Traps, current.Traps) {
		d.Present |= 1 << 4
	}
	if baseline.TrapBudget != current.TrapBudget {
		d.Present |= 1 << 5
		d.TrapBudget = current.TrapBudget
	}
	if baseline.TreasureX != current.TreasureX {
		d.Present |= 1 << 6
		d.TreasureX = current.TreasureX
	}
	if baseline.TreasureY != current.TreasureY {
		d.Present |= 1 << 7
		d.TreasureY = current.TreasureY
	}
	if baseline.ExitX != current.ExitX {
		d.Present |= 1 << 8
		d.ExitX = current.ExitX
	}
	if baseline.ExitY != current.ExitY {
		d.Present |= 1 << 9
		d.ExitY = current.ExitY
	}
	if baseline.TickLimit != current.TickLimit {
		d.Present |= 1 << 10
		d.TickLimit = current.TickLimit
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 11
		d.Over = current.Over
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 12
		d.Winner = current.Winner
	}
	return d.Present != 0
}

// applyDungeonStateDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyDungeonStateDelta(v *DungeonState, d DungeonStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.Walls = d.Walls
	}
	if d.Present&(1<<2) != 0 {
		v.Explored = d.Explored
	}
	if d.Present&(1<<3) != 0 {
		if err := applyAdventurerListDelta(&v.Adventurers, d.Adventurers); err != nil {
			return err
		}
	}
	if d.Present&(1<<4) != 0 {
		if err := applyTrapListDelta(&v.Traps, d.Traps); err != nil {
			return err
		}
	}
	if d.Present&(1<<5) != 0 {
		v.TrapBudget = d.TrapBudget
	}
	if d.Present&(1<<6) != 0 {
		v.TreasureX = d.TreasureX
	}
	if d.Present&(1<<7) != 0 {
		v.TreasureY = d.TreasureY
	}
	if d.Present&(1<<8) != 0 {
		v.ExitX = d.ExitX
	}
	if d.Present&(1<<9) != 0 {
		v.ExitY = d.ExitY
	}
	if d.Present&(1<<10) != 0 {
		v.TickLimit = d.TickLimit
	}
	if d.Present&(1<<11) != 0 {
		v.Over = d.Over
	}
	if d.Present&(1<<12) != 0 {
		v.Winner = d.Winner
	}
	return nil
}

// appendDungeonStateDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendDungeonStateDeltaCBOR(dst []byte, v DungeonStateDelta) []byte {
	n := 1
	for bit := 0; bit < 13; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Walls))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Explored))
	}
	if v.Present&(1<<3) != 0 {
		dst = appendAdventurerListDeltaCBOR(dst, v.Adventurers)
	}
	if v.Present&(1<<4) != 0 {
		dst = appendTrapListDeltaCBOR(dst, v.Traps)
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TrapBudget))
	}
	if v.Present&(1<<6) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	}
	if v.Present&(1<<7) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	}
	if v.Present&(1<<8) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ExitX))
	}
	if v.Present&(1<<9) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ExitY))
	}
	if v.Present&(1<<10) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TickLimit))
	}
	if v.Present&(1<<11) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	if v.Present&(1<<12) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	return dst
}

// decodeDungeonStateDeltaCBOR reads one delta into v.
func decodeDungeonStateDeltaCBOR(r *cbor.Reader, v *DungeonStateDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "DungeonStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint64()
			if err != nil {
				return err
			}
			v.Tick = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.Walls = append(v.Walls[:0], x...)
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.Explored = append(v.Explored[:0], x...)
		}
		read++
	}
	if present&(1<<3) != 0 {
		if err := decodeAdventurerListDeltaCBOR(r, &v.Adventurers); err != nil {
			return err
		}
		read++
	}
	if present&(1<<4) != 0 {
		if err := decodeTrapListDeltaCBOR(r, &v.Traps); err != nil {
			return err
		}
		read++
	}
	if present&(1<<5) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TrapBudget = x
		}
		read++
	}
	if present&(1<<6) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TreasureX = x
		}
		read++
	}
	if present&(1<<7) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.TreasureY = x
		}
		read++
	}
	if present&(1<<8) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.ExitX = x
		}
		read++
	}
	if present&(1<<9) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.ExitY = x
		}
		read++
	}
	if present&(1<<10) != 0 {
		{
			x, err := r.ReadUint32()
			if err != nil {
				return err
			}
			v.TickLimit = x
		}
		read++
	}
	if present&(1<<11) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Over = x
		}
		read++
	}
	if present&(1<<12) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Winner = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// DiffDungeonState reports what changed between baseline and current.
//
// Use DiffDungeonStateInto in a loop that runs per tick: it fills a delta the caller
// retains, and reuses its collection capacity, so the steady state allocates
// nothing.
func DiffDungeonState(baseline, current DungeonState) DungeonStateDelta {
	var d DungeonStateDelta
	diffDungeonStateInto(&d, baseline, current)
	return d
}

// DiffDungeonStateInto is DiffDungeonState into a delta the caller owns and reuses.
func DiffDungeonStateInto(d *DungeonStateDelta, baseline, current DungeonState) {
	diffDungeonStateInto(d, baseline, current)
}

// ApplyDungeonStateDelta puts d back onto v.
//
// It reports an error when the delta names an entity v does not hold, which
// means v is not the baseline the delta was diffed against.
func ApplyDungeonStateDelta(v *DungeonState, d DungeonStateDelta) error {
	return applyDungeonStateDelta(v, d)
}

// AppendCBORTo appends the delta as one CBOR item, satisfying cbor.Appender.
func (v DungeonStateDelta) AppendCBORTo(dst []byte) []byte {
	return appendDungeonStateDeltaCBOR(dst, v)
}

// DecodeCBORFrom reads one delta into v, satisfying cbor.Decodable.
func (v *DungeonStateDelta) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeDungeonStateDeltaCBOR(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// PartyMateDelta is what changed between two PartyMate values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type PartyMateDelta struct {
	Present uint64
	// bit 0
	X uint8
	// bit 1
	Y uint8
	// bit 2
	Role uint8
	// bit 3
	Alive bool
	// bit 4
	Carrying bool
}

// diffPartyMateInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffPartyMateInto(d *PartyMateDelta, baseline, current PartyMate) bool {
	d.Present = 0
	if baseline.X != current.X {
		d.Present |= 1 << 0
		d.X = current.X
	}
	if baseline.Y != current.Y {
		d.Present |= 1 << 1
		d.Y = current.Y
	}
	if baseline.Role != current.Role {
		d.Present |= 1 << 2
		d.Role = current.Role
	}
	if baseline.Alive != current.Alive {
		d.Present |= 1 << 3
		d.Alive = current.Alive
	}
	if baseline.Carrying != current.Carrying {
		d.Present |= 1 << 4
		d.Carrying = current.Carrying
	}
	return d.Present != 0
}

// applyPartyMateDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyPartyMateDelta(v *PartyMate, d PartyMateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.X = d.X
	}
	if d.Present&(1<<1) != 0 {
		v.Y = d.Y
	}
	if d.Present&(1<<2) != 0 {
		v.Role = d.Role
	}
	if d.Present&(1<<3) != 0 {
		v.Alive = d.Alive
	}
	if d.Present&(1<<4) != 0 {
		v.Carrying = d.Carrying
	}
	return nil
}

// appendPartyMateDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendPartyMateDeltaCBOR(dst []byte, v PartyMateDelta) []byte {
	n := 1
	for bit := 0; bit < 5; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.X))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Y))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Role))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Alive))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Carrying))
	}
	return dst
}

// decodePartyMateDeltaCBOR reads one delta into v.
func decodePartyMateDeltaCBOR(r *cbor.Reader, v *PartyMateDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PartyMateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.X = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Y = x
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Role = x
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Alive = x
		}
		read++
	}
	if present&(1<<4) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Carrying = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// TrapDelta is what changed between two Trap values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type TrapDelta struct {
	Present uint64
	// bit 0
	X uint8
	// bit 1
	Y uint8
	// bit 2
	Armed bool
	// bit 3
	Discovered bool
}

// diffTrapInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffTrapInto(d *TrapDelta, baseline, current Trap) bool {
	d.Present = 0
	if baseline.X != current.X {
		d.Present |= 1 << 0
		d.X = current.X
	}
	if baseline.Y != current.Y {
		d.Present |= 1 << 1
		d.Y = current.Y
	}
	if baseline.Armed != current.Armed {
		d.Present |= 1 << 2
		d.Armed = current.Armed
	}
	if baseline.Discovered != current.Discovered {
		d.Present |= 1 << 3
		d.Discovered = current.Discovered
	}
	return d.Present != 0
}

// applyTrapDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyTrapDelta(v *Trap, d TrapDelta) error {
	if d.Present&(1<<0) != 0 {
		v.X = d.X
	}
	if d.Present&(1<<1) != 0 {
		v.Y = d.Y
	}
	if d.Present&(1<<2) != 0 {
		v.Armed = d.Armed
	}
	if d.Present&(1<<3) != 0 {
		v.Discovered = d.Discovered
	}
	return nil
}

// appendTrapDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendTrapDeltaCBOR(dst []byte, v TrapDelta) []byte {
	n := 1
	for bit := 0; bit < 4; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.X))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Y))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Armed))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Discovered))
	}
	return dst
}

// decodeTrapDeltaCBOR reads one delta into v.
func decodeTrapDeltaCBOR(r *cbor.Reader, v *TrapDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TrapDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.X = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Y = x
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Armed = x
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Discovered = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// AdventurerListDelta is what changed in a collection of Adventurer, keyed by ID.
//
// Present names the groups carried: bit 0 Set, bit 1 Removed, bit 2 Patched.
// The ordinary tick carries Patched alone, so an unchanged group costs a bit
// rather than an empty array.
type AdventurerListDelta struct {
	Present uint64
	// Set carries an entity that arrived, or one replaced outright.
	Set []Adventurer
	// Removed carries the identity of an entity that left.
	Removed []uint16
	// Patched carries an entity that changed, as its identity and its delta.
	Patched []AdventurerPatch
	// index is scratch the diff reuses across ticks, so a steady state
	// allocates nothing after the first call. It is never encoded and never
	// ranged: every loop below walks a slice, which is what keeps the output
	// the same on two runs.
	index map[uint16]int32
}

// AdventurerPatch is one changed Adventurer: its identity, and what changed in it.
type AdventurerPatch struct {
	ID    uint16
	Delta AdventurerDelta
}

// diffAdventurerListInto fills d with what changed between two collections of Adventurer,
// and reports whether anything did.
//
// The order of the two slices is not compared: an entity is found by its
// identity, so a collection the game keeps in spawn order diffs the same as
// one it keeps sorted.
func diffAdventurerListInto(d *AdventurerListDelta, baseline, current []Adventurer) bool {
	d.Present = 0
	d.Set = d.Set[:0]
	d.Removed = d.Removed[:0]
	d.Patched = d.Patched[:0]
	if d.index == nil {
		d.index = make(map[uint16]int32, len(baseline))
	} else {
		clear(d.index)
	}
	for i := range baseline {
		d.index[baseline[i].ID] = int32(i)
	}
	for j := range current {
		i, ok := d.index[current[j].ID]
		if !ok {
			d.Set = append(d.Set, current[j])
			continue
		}
		// Marked seen, so the sweep below reports only what did not arrive.
		d.index[current[j].ID] = -1
		// The slot is grown into rather than appended to, so the delta nested
		// inside it -- and the scratch index inside that -- is the one the last
		// tick used. Appending a fresh value here would allocate a new index map
		// per changed entity per tick, which is the whole steady state.
		if len(d.Patched) < cap(d.Patched) {
			d.Patched = d.Patched[:len(d.Patched)+1]
		} else {
			d.Patched = append(d.Patched, AdventurerPatch{})
		}
		p := &d.Patched[len(d.Patched)-1]
		p.ID = current[j].ID
		if !diffAdventurerInto(&p.Delta, baseline[i], current[j]) {
			d.Patched = d.Patched[:len(d.Patched)-1]
		}
	}
	for i := range baseline {
		if d.index[baseline[i].ID] >= 0 {
			d.Removed = append(d.Removed, baseline[i].ID)
		}
	}
	if len(d.Set) > 0 {
		d.Present |= 1 << 0
	}
	if len(d.Removed) > 0 {
		d.Present |= 1 << 1
	}
	if len(d.Patched) > 0 {
		d.Present |= 1 << 2
	}
	return d.Present != 0
}

// cborIndexOfAdventurer finds an entity by identity, and reports -1 for one the
// collection does not hold.
func cborIndexOfAdventurer(s []Adventurer, id uint16) int {
	for i := range s {
		if s[i].ID == id {
			return i
		}
	}
	return -1
}

// cborSortAdventurer puts a collection in identity order.
//
// An insertion sort, because a collection is nearly sorted already after a
// tick that changed a few entities, and because it allocates nothing and
// pulls in no import on a wasm target.
func cborSortAdventurer(s []Adventurer) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j].ID < s[j-1].ID; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// applyAdventurerListDelta puts a collection delta back.
//
// Removals first, then patches, then arrivals: a patch names an entity the
// baseline held, and applying it after an arrival of the same identity would
// patch the wrong value. An identity a patch or a removal names and the
// collection does not hold means the baseline is not the one the sender
// diffed against, which is reported rather than ignored.
func applyAdventurerListDelta(v *[]Adventurer, d AdventurerListDelta) error {
	if d.Present&(1<<1) != 0 {
		for _, id := range d.Removed {
			k := cborIndexOfAdventurer(*v, id)
			if k < 0 {
				return &cbor.Error{Path: "Adventurer: the delta removes an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			*v = append((*v)[:k], (*v)[k+1:]...)
		}
	}
	if d.Present&(1<<2) != 0 {
		for i := range d.Patched {
			k := cborIndexOfAdventurer(*v, d.Patched[i].ID)
			if k < 0 {
				return &cbor.Error{Path: "Adventurer: the delta patches an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			if err := applyAdventurerDelta(&(*v)[k], d.Patched[i].Delta); err != nil {
				return err
			}
		}
	}
	if d.Present&(1<<0) != 0 {
		for i := range d.Set {
			k := cborIndexOfAdventurer(*v, d.Set[i].ID)
			if k < 0 {
				*v = append(*v, d.Set[i])
			} else {
				(*v)[k] = d.Set[i]
			}
		}
	}
	// Identity order, so a receiver fed deltas and a sender holding the same
	// entities encode to the same bytes, which is what a replay compares.
	cborSortAdventurer(*v)
	return nil
}

// appendAdventurerListDeltaCBOR appends a collection delta.
//
// Only the groups Present names are written, and Patched alternates identity
// and payload in one array rather than pairing them: a byte per element, and
// a nesting level per hierarchy level.
func appendAdventurerListDeltaCBOR(dst []byte, v AdventurerListDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Set))
		for i := range v.Set {
			dst = appendAdventurerCBORWorld(dst, v.Set[i])
		}
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Removed))
		for i := range v.Removed {
			dst = cbor.AppendUint(dst, uint64(v.Removed[i]))
		}
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Patched)*2)
		for i := range v.Patched {
			dst = cbor.AppendUint(dst, uint64(v.Patched[i].ID))
			dst = appendAdventurerDeltaCBOR(dst, v.Patched[i].Delta)
		}
	}
	return dst
}

// decodeAdventurerListDeltaCBOR reads a collection delta.
func decodeAdventurerListDeltaCBOR(r *cbor.Reader, v *AdventurerListDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerListDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	v.Set = v.Set[:0]
	v.Removed = v.Removed[:0]
	v.Patched = v.Patched[:0]
	read := 1
	if present&(1<<0) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			var x Adventurer
			if err := decodeAdventurerCBORWorld(r, &x); err != nil {
				return err
			}
			v.Set = append(v.Set, x)
		}
		read++
	}
	if present&(1<<1) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint16(rawid)
			v.Removed = append(v.Removed, id)
		}
		read++
	}
	if present&(1<<2) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite || count%2 != 0 {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "AdventurerListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k += 2 {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint16(rawid)
			var p AdventurerPatch
			p.ID = id
			if err := decodeAdventurerDeltaCBOR(r, &p.Delta); err != nil {
				return err
			}
			v.Patched = append(v.Patched, p)
		}
		read++
	}
	// A group this schema does not know: one item per remaining slot, which
	// is what keeps an older reader aligned when a group was appended.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// PartyMateListDelta is what changed in a collection of PartyMate, keyed by ID.
//
// Present names the groups carried: bit 0 Set, bit 1 Removed, bit 2 Patched.
// The ordinary tick carries Patched alone, so an unchanged group costs a bit
// rather than an empty array.
type PartyMateListDelta struct {
	Present uint64
	// Set carries an entity that arrived, or one replaced outright.
	Set []PartyMate
	// Removed carries the identity of an entity that left.
	Removed []uint16
	// Patched carries an entity that changed, as its identity and its delta.
	Patched []PartyMatePatch
	// index is scratch the diff reuses across ticks, so a steady state
	// allocates nothing after the first call. It is never encoded and never
	// ranged: every loop below walks a slice, which is what keeps the output
	// the same on two runs.
	index map[uint16]int32
}

// PartyMatePatch is one changed PartyMate: its identity, and what changed in it.
type PartyMatePatch struct {
	ID    uint16
	Delta PartyMateDelta
}

// diffPartyMateListInto fills d with what changed between two collections of PartyMate,
// and reports whether anything did.
//
// The order of the two slices is not compared: an entity is found by its
// identity, so a collection the game keeps in spawn order diffs the same as
// one it keeps sorted.
func diffPartyMateListInto(d *PartyMateListDelta, baseline, current []PartyMate) bool {
	d.Present = 0
	d.Set = d.Set[:0]
	d.Removed = d.Removed[:0]
	d.Patched = d.Patched[:0]
	if d.index == nil {
		d.index = make(map[uint16]int32, len(baseline))
	} else {
		clear(d.index)
	}
	for i := range baseline {
		d.index[baseline[i].ID] = int32(i)
	}
	for j := range current {
		i, ok := d.index[current[j].ID]
		if !ok {
			d.Set = append(d.Set, current[j])
			continue
		}
		// Marked seen, so the sweep below reports only what did not arrive.
		d.index[current[j].ID] = -1
		// The slot is grown into rather than appended to, so the delta nested
		// inside it -- and the scratch index inside that -- is the one the last
		// tick used. Appending a fresh value here would allocate a new index map
		// per changed entity per tick, which is the whole steady state.
		if len(d.Patched) < cap(d.Patched) {
			d.Patched = d.Patched[:len(d.Patched)+1]
		} else {
			d.Patched = append(d.Patched, PartyMatePatch{})
		}
		p := &d.Patched[len(d.Patched)-1]
		p.ID = current[j].ID
		if !diffPartyMateInto(&p.Delta, baseline[i], current[j]) {
			d.Patched = d.Patched[:len(d.Patched)-1]
		}
	}
	for i := range baseline {
		if d.index[baseline[i].ID] >= 0 {
			d.Removed = append(d.Removed, baseline[i].ID)
		}
	}
	if len(d.Set) > 0 {
		d.Present |= 1 << 0
	}
	if len(d.Removed) > 0 {
		d.Present |= 1 << 1
	}
	if len(d.Patched) > 0 {
		d.Present |= 1 << 2
	}
	return d.Present != 0
}

// cborIndexOfPartyMate finds an entity by identity, and reports -1 for one the
// collection does not hold.
func cborIndexOfPartyMate(s []PartyMate, id uint16) int {
	for i := range s {
		if s[i].ID == id {
			return i
		}
	}
	return -1
}

// cborSortPartyMate puts a collection in identity order.
//
// An insertion sort, because a collection is nearly sorted already after a
// tick that changed a few entities, and because it allocates nothing and
// pulls in no import on a wasm target.
func cborSortPartyMate(s []PartyMate) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j].ID < s[j-1].ID; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// applyPartyMateListDelta puts a collection delta back.
//
// Removals first, then patches, then arrivals: a patch names an entity the
// baseline held, and applying it after an arrival of the same identity would
// patch the wrong value. An identity a patch or a removal names and the
// collection does not hold means the baseline is not the one the sender
// diffed against, which is reported rather than ignored.
func applyPartyMateListDelta(v *[]PartyMate, d PartyMateListDelta) error {
	if d.Present&(1<<1) != 0 {
		for _, id := range d.Removed {
			k := cborIndexOfPartyMate(*v, id)
			if k < 0 {
				return &cbor.Error{Path: "PartyMate: the delta removes an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			*v = append((*v)[:k], (*v)[k+1:]...)
		}
	}
	if d.Present&(1<<2) != 0 {
		for i := range d.Patched {
			k := cborIndexOfPartyMate(*v, d.Patched[i].ID)
			if k < 0 {
				return &cbor.Error{Path: "PartyMate: the delta patches an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			if err := applyPartyMateDelta(&(*v)[k], d.Patched[i].Delta); err != nil {
				return err
			}
		}
	}
	if d.Present&(1<<0) != 0 {
		for i := range d.Set {
			k := cborIndexOfPartyMate(*v, d.Set[i].ID)
			if k < 0 {
				*v = append(*v, d.Set[i])
			} else {
				(*v)[k] = d.Set[i]
			}
		}
	}
	// Identity order, so a receiver fed deltas and a sender holding the same
	// entities encode to the same bytes, which is what a replay compares.
	cborSortPartyMate(*v)
	return nil
}

// appendPartyMateListDeltaCBOR appends a collection delta.
//
// Only the groups Present names are written, and Patched alternates identity
// and payload in one array rather than pairing them: a byte per element, and
// a nesting level per hierarchy level.
func appendPartyMateListDeltaCBOR(dst []byte, v PartyMateListDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Set))
		for i := range v.Set {
			dst = appendPartyMateCBORWorld(dst, v.Set[i])
		}
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Removed))
		for i := range v.Removed {
			dst = cbor.AppendUint(dst, uint64(v.Removed[i]))
		}
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Patched)*2)
		for i := range v.Patched {
			dst = cbor.AppendUint(dst, uint64(v.Patched[i].ID))
			dst = appendPartyMateDeltaCBOR(dst, v.Patched[i].Delta)
		}
	}
	return dst
}

// decodePartyMateListDeltaCBOR reads a collection delta.
func decodePartyMateListDeltaCBOR(r *cbor.Reader, v *PartyMateListDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PartyMateListDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	v.Set = v.Set[:0]
	v.Removed = v.Removed[:0]
	v.Patched = v.Patched[:0]
	read := 1
	if present&(1<<0) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "PartyMateListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			var x PartyMate
			if err := decodePartyMateCBORWorld(r, &x); err != nil {
				return err
			}
			v.Set = append(v.Set, x)
		}
		read++
	}
	if present&(1<<1) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "PartyMateListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint16(rawid)
			v.Removed = append(v.Removed, id)
		}
		read++
	}
	if present&(1<<2) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite || count%2 != 0 {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "PartyMateListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k += 2 {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint16(rawid)
			var p PartyMatePatch
			p.ID = id
			if err := decodePartyMateDeltaCBOR(r, &p.Delta); err != nil {
				return err
			}
			v.Patched = append(v.Patched, p)
		}
		read++
	}
	// A group this schema does not know: one item per remaining slot, which
	// is what keeps an older reader aligned when a group was appended.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// TrapListDelta is what changed in a collection of Trap, keyed by ID.
//
// Present names the groups carried: bit 0 Set, bit 1 Removed, bit 2 Patched.
// The ordinary tick carries Patched alone, so an unchanged group costs a bit
// rather than an empty array.
type TrapListDelta struct {
	Present uint64
	// Set carries an entity that arrived, or one replaced outright.
	Set []Trap
	// Removed carries the identity of an entity that left.
	Removed []uint32
	// Patched carries an entity that changed, as its identity and its delta.
	Patched []TrapPatch
	// index is scratch the diff reuses across ticks, so a steady state
	// allocates nothing after the first call. It is never encoded and never
	// ranged: every loop below walks a slice, which is what keeps the output
	// the same on two runs.
	index map[uint32]int32
}

// TrapPatch is one changed Trap: its identity, and what changed in it.
type TrapPatch struct {
	ID    uint32
	Delta TrapDelta
}

// diffTrapListInto fills d with what changed between two collections of Trap,
// and reports whether anything did.
//
// The order of the two slices is not compared: an entity is found by its
// identity, so a collection the game keeps in spawn order diffs the same as
// one it keeps sorted.
func diffTrapListInto(d *TrapListDelta, baseline, current []Trap) bool {
	d.Present = 0
	d.Set = d.Set[:0]
	d.Removed = d.Removed[:0]
	d.Patched = d.Patched[:0]
	if d.index == nil {
		d.index = make(map[uint32]int32, len(baseline))
	} else {
		clear(d.index)
	}
	for i := range baseline {
		d.index[baseline[i].ID] = int32(i)
	}
	for j := range current {
		i, ok := d.index[current[j].ID]
		if !ok {
			d.Set = append(d.Set, current[j])
			continue
		}
		// Marked seen, so the sweep below reports only what did not arrive.
		d.index[current[j].ID] = -1
		// The slot is grown into rather than appended to, so the delta nested
		// inside it -- and the scratch index inside that -- is the one the last
		// tick used. Appending a fresh value here would allocate a new index map
		// per changed entity per tick, which is the whole steady state.
		if len(d.Patched) < cap(d.Patched) {
			d.Patched = d.Patched[:len(d.Patched)+1]
		} else {
			d.Patched = append(d.Patched, TrapPatch{})
		}
		p := &d.Patched[len(d.Patched)-1]
		p.ID = current[j].ID
		if !diffTrapInto(&p.Delta, baseline[i], current[j]) {
			d.Patched = d.Patched[:len(d.Patched)-1]
		}
	}
	for i := range baseline {
		if d.index[baseline[i].ID] >= 0 {
			d.Removed = append(d.Removed, baseline[i].ID)
		}
	}
	if len(d.Set) > 0 {
		d.Present |= 1 << 0
	}
	if len(d.Removed) > 0 {
		d.Present |= 1 << 1
	}
	if len(d.Patched) > 0 {
		d.Present |= 1 << 2
	}
	return d.Present != 0
}

// cborIndexOfTrap finds an entity by identity, and reports -1 for one the
// collection does not hold.
func cborIndexOfTrap(s []Trap, id uint32) int {
	for i := range s {
		if s[i].ID == id {
			return i
		}
	}
	return -1
}

// cborSortTrap puts a collection in identity order.
//
// An insertion sort, because a collection is nearly sorted already after a
// tick that changed a few entities, and because it allocates nothing and
// pulls in no import on a wasm target.
func cborSortTrap(s []Trap) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j].ID < s[j-1].ID; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// applyTrapListDelta puts a collection delta back.
//
// Removals first, then patches, then arrivals: a patch names an entity the
// baseline held, and applying it after an arrival of the same identity would
// patch the wrong value. An identity a patch or a removal names and the
// collection does not hold means the baseline is not the one the sender
// diffed against, which is reported rather than ignored.
func applyTrapListDelta(v *[]Trap, d TrapListDelta) error {
	if d.Present&(1<<1) != 0 {
		for _, id := range d.Removed {
			k := cborIndexOfTrap(*v, id)
			if k < 0 {
				return &cbor.Error{Path: "Trap: the delta removes an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			*v = append((*v)[:k], (*v)[k+1:]...)
		}
	}
	if d.Present&(1<<2) != 0 {
		for i := range d.Patched {
			k := cborIndexOfTrap(*v, d.Patched[i].ID)
			if k < 0 {
				return &cbor.Error{Path: "Trap: the delta patches an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			if err := applyTrapDelta(&(*v)[k], d.Patched[i].Delta); err != nil {
				return err
			}
		}
	}
	if d.Present&(1<<0) != 0 {
		for i := range d.Set {
			k := cborIndexOfTrap(*v, d.Set[i].ID)
			if k < 0 {
				*v = append(*v, d.Set[i])
			} else {
				(*v)[k] = d.Set[i]
			}
		}
	}
	// Identity order, so a receiver fed deltas and a sender holding the same
	// entities encode to the same bytes, which is what a replay compares.
	cborSortTrap(*v)
	return nil
}

// appendTrapListDeltaCBOR appends a collection delta.
//
// Only the groups Present names are written, and Patched alternates identity
// and payload in one array rather than pairing them: a byte per element, and
// a nesting level per hierarchy level.
func appendTrapListDeltaCBOR(dst []byte, v TrapListDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Set))
		for i := range v.Set {
			dst = appendTrapCBORWorld(dst, v.Set[i])
		}
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Removed))
		for i := range v.Removed {
			dst = cbor.AppendUint(dst, uint64(v.Removed[i]))
		}
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Patched)*2)
		for i := range v.Patched {
			dst = cbor.AppendUint(dst, uint64(v.Patched[i].ID))
			dst = appendTrapDeltaCBOR(dst, v.Patched[i].Delta)
		}
	}
	return dst
}

// decodeTrapListDeltaCBOR reads a collection delta.
func decodeTrapListDeltaCBOR(r *cbor.Reader, v *TrapListDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TrapListDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	v.Set = v.Set[:0]
	v.Removed = v.Removed[:0]
	v.Patched = v.Patched[:0]
	read := 1
	if present&(1<<0) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "TrapListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			var x Trap
			if err := decodeTrapCBORWorld(r, &x); err != nil {
				return err
			}
			v.Set = append(v.Set, x)
		}
		read++
	}
	if present&(1<<1) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "TrapListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint32(rawid)
			v.Removed = append(v.Removed, id)
		}
		read++
	}
	if present&(1<<2) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite || count%2 != 0 {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "TrapListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k += 2 {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint32(rawid)
			var p TrapPatch
			p.ID = id
			if err := decodeTrapDeltaCBOR(r, &p.Delta); err != nil {
				return err
			}
			v.Patched = append(v.Patched, p)
		}
		read++
	}
	// A group this schema does not know: one item per remaining slot, which
	// is what keeps an older reader aligned when a group was appended.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}
