// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:1c163850fbffc42ec49f2f439ce6a4ae3099d6aa2f04161e785582b5a973f491 self=sha256:0ad2f9597e89aabe17fdc8ff7b248eeca08c03384a6ad946dd5ce90077ea4ffe outputs=tinybind_gen.go

package msg

import (
	"github.com/shibukawa/tinybind-go/cborbind"
	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

func appendActionInputCBORArray(dst []byte, v ActionInput) []byte {
	dst = cbor.AppendArrayHeader(dst, 5)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, uint64(v.Kind))
	dst = cbor.AppendUint(dst, uint64(v.Dir))
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, uint64(v.Y))
	return dst
}

func decodeActionInputCBORArray(cr *cbor.Reader) (ActionInput, error) {
	var out ActionInput
	n, indefinite, err := cr.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite || n != 5 {
		return out, cborbind.ErrShape
	}
	{
		v, err := cr.ReadUint32()
		if err != nil {
			return out, err
		}
		out.Tick = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.Kind = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.Dir = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.X = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.Y = v
	}
	return out, nil
}

// AppendCBORInArrayTo appends v as CBOR, for cborbind.AppendCBORInArrayTo.
func (v ActionInput) AppendCBORInArrayTo(dst []byte) []byte {
	return appendActionInputCBORArray(dst, v)
}

// DecodeCBORInArrayFrom decodes one CBOR value into v, for cborbind.DecodeCBORInArrayFrom.
func (v *ActionInput) DecodeCBORInArrayFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeActionInputCBORArray(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape ActionInput declares.
func (v ActionInput) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInArrayTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape ActionInput declares.
func (v *ActionInput) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInArrayFrom(data)
}

func appendAdventurerCBORMap(dst []byte, v Adventurer) []byte {
	dst = cbor.AppendMapHeader(dst, 7)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "hp")
	dst = cbor.AppendInt(dst, int64(v.HP))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "role")
	dst = cbor.AppendUint(dst, uint64(v.Role))
	dst = cbor.AppendText(dst, "alive")
	dst = cbor.AppendBool(dst, v.Alive)
	dst = cbor.AppendText(dst, "carrying")
	dst = cbor.AppendBool(dst, v.Carrying)
	return dst
}

func decodeAdventurerCBORMap(cr *cbor.Reader) (Adventurer, error) {
	var out Adventurer
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "hp":
			v, err := cr.ReadInt8()
			if err != nil {
				return out, err
			}
			out.HP = v
		case "id":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "role":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Role = v
		case "alive":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Alive = v
		case "carrying":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Carrying = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v Adventurer) AppendCBORInMapTo(dst []byte) []byte {
	return appendAdventurerCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *Adventurer) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeAdventurerCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Adventurer declares.
func (v Adventurer) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Adventurer declares.
func (v *Adventurer) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendTrapCBORMap(dst []byte, v Trap) []byte {
	dst = cbor.AppendMapHeader(dst, 5)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "disc")
	dst = cbor.AppendBool(dst, v.Discovered)
	dst = cbor.AppendText(dst, "armed")
	dst = cbor.AppendBool(dst, v.Armed)
	return dst
}

func decodeTrapCBORMap(cr *cbor.Reader) (Trap, error) {
	var out Trap
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "id":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "disc":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Discovered = v
		case "armed":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Armed = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v Trap) AppendCBORInMapTo(dst []byte) []byte {
	return appendTrapCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *Trap) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeTrapCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Trap declares.
func (v Trap) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Trap declares.
func (v *Trap) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendDungeonStateCBORMap(dst []byte, v DungeonState) []byte {
	dst = cbor.AppendMapHeader(dst, 13)
	dst = cbor.AppendText(dst, "ex")
	dst = cbor.AppendUint(dst, uint64(v.ExitX))
	dst = cbor.AppendText(dst, "ey")
	dst = cbor.AppendUint(dst, uint64(v.ExitY))
	dst = cbor.AppendText(dst, "tx")
	dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	dst = cbor.AppendText(dst, "ty")
	dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	dst = cbor.AppendText(dst, "advs")
	dst = cbor.AppendArrayHeader(dst, len(v.Adventurers))
	for i := range v.Adventurers {
		dst = appendAdventurerCBORMap(dst, v.Adventurers[i])
	}
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendText(dst, "limit")
	dst = cbor.AppendUint(dst, uint64(v.TickLimit))
	dst = cbor.AppendText(dst, "traps")
	dst = cbor.AppendArrayHeader(dst, len(v.Traps))
	for i := range v.Traps {
		dst = appendTrapCBORMap(dst, v.Traps[i])
	}
	dst = cbor.AppendText(dst, "walls")
	dst = cbor.AppendArrayHeader(dst, len(v.Walls))
	for i := range v.Walls {
		dst = cbor.AppendUint(dst, uint64(v.Walls[i]))
	}
	dst = cbor.AppendText(dst, "budget")
	dst = cbor.AppendUint(dst, uint64(v.TrapBudget))
	dst = cbor.AppendText(dst, "winner")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendText(dst, "explored")
	dst = cbor.AppendArrayHeader(dst, len(v.Explored))
	for i := range v.Explored {
		dst = cbor.AppendUint(dst, uint64(v.Explored[i]))
	}
	return dst
}

func decodeDungeonStateCBORMap(cr *cbor.Reader) (DungeonState, error) {
	var out DungeonState
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "ex":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ExitX = v
		case "ey":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ExitY = v
		case "tx":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TreasureX = v
		case "ty":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TreasureY = v
		case "advs":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Adventurer, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeAdventurerCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Adventurers = slice
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		case "limit":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.TickLimit = v
		case "traps":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Trap, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeTrapCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Traps = slice
		case "walls":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.Walls = slice
		case "budget":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TrapBudget = v
		case "winner":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Winner = v
		case "explored":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.Explored = slice
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v DungeonState) AppendCBORInMapTo(dst []byte) []byte {
	return appendDungeonStateCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *DungeonState) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeDungeonStateCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape DungeonState declares.
func (v DungeonState) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape DungeonState declares.
func (v *DungeonState) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendPartyMateCBORMap(dst []byte, v PartyMate) []byte {
	dst = cbor.AppendMapHeader(dst, 6)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "role")
	dst = cbor.AppendUint(dst, uint64(v.Role))
	dst = cbor.AppendText(dst, "alive")
	dst = cbor.AppendBool(dst, v.Alive)
	dst = cbor.AppendText(dst, "carrying")
	dst = cbor.AppendBool(dst, v.Carrying)
	return dst
}

func decodePartyMateCBORMap(cr *cbor.Reader) (PartyMate, error) {
	var out PartyMate
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "id":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "role":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Role = v
		case "alive":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Alive = v
		case "carrying":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Carrying = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v PartyMate) AppendCBORInMapTo(dst []byte) []byte {
	return appendPartyMateCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *PartyMate) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodePartyMateCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape PartyMate declares.
func (v PartyMate) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape PartyMate declares.
func (v *PartyMate) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendAdventurerViewCBORMap(dst []byte, v AdventurerView) []byte {
	dst = cbor.AppendMapHeader(dst, 17)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "ex")
	dst = cbor.AppendUint(dst, uint64(v.ExitX))
	dst = cbor.AppendText(dst, "ey")
	dst = cbor.AppendUint(dst, uint64(v.ExitY))
	dst = cbor.AppendText(dst, "hp")
	dst = cbor.AppendInt(dst, int64(v.HP))
	dst = cbor.AppendText(dst, "tx")
	dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	dst = cbor.AppendText(dst, "ty")
	dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	dst = cbor.AppendText(dst, "you")
	dst = cbor.AppendUint(dst, uint64(v.You))
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "role")
	dst = cbor.AppendUint(dst, uint64(v.Role))
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendText(dst, "party")
	dst = cbor.AppendArrayHeader(dst, len(v.Party))
	for i := range v.Party {
		dst = appendPartyMateCBORMap(dst, v.Party[i])
	}
	dst = cbor.AppendText(dst, "traps")
	dst = cbor.AppendArrayHeader(dst, len(v.KnownTraps))
	for i := range v.KnownTraps {
		dst = appendTrapCBORMap(dst, v.KnownTraps[i])
	}
	dst = cbor.AppendText(dst, "walls")
	dst = cbor.AppendArrayHeader(dst, len(v.KnownWalls))
	for i := range v.KnownWalls {
		dst = cbor.AppendUint(dst, uint64(v.KnownWalls[i]))
	}
	dst = cbor.AppendText(dst, "winner")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendText(dst, "carrying")
	dst = cbor.AppendBool(dst, v.Carrying)
	dst = cbor.AppendText(dst, "explored")
	dst = cbor.AppendArrayHeader(dst, len(v.Explored))
	for i := range v.Explored {
		dst = cbor.AppendUint(dst, uint64(v.Explored[i]))
	}
	return dst
}

func decodeAdventurerViewCBORMap(cr *cbor.Reader) (AdventurerView, error) {
	var out AdventurerView
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "ex":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ExitX = v
		case "ey":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ExitY = v
		case "hp":
			v, err := cr.ReadInt8()
			if err != nil {
				return out, err
			}
			out.HP = v
		case "tx":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TreasureX = v
		case "ty":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TreasureY = v
		case "you":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.You = v
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "role":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Role = v
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		case "party":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]PartyMate, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodePartyMateCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Party = slice
		case "traps":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Trap, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeTrapCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.KnownTraps = slice
		case "walls":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.KnownWalls = slice
		case "winner":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Winner = v
		case "carrying":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Carrying = v
		case "explored":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.Explored = slice
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v AdventurerView) AppendCBORInMapTo(dst []byte) []byte {
	return appendAdventurerViewCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *AdventurerView) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeAdventurerViewCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape AdventurerView declares.
func (v AdventurerView) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape AdventurerView declares.
func (v *AdventurerView) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendDMViewCBORMap(dst []byte, v DMView) []byte {
	dst = cbor.AppendMapHeader(dst, 12)
	dst = cbor.AppendText(dst, "ex")
	dst = cbor.AppendUint(dst, uint64(v.ExitX))
	dst = cbor.AppendText(dst, "ey")
	dst = cbor.AppendUint(dst, uint64(v.ExitY))
	dst = cbor.AppendText(dst, "tx")
	dst = cbor.AppendUint(dst, uint64(v.TreasureX))
	dst = cbor.AppendText(dst, "ty")
	dst = cbor.AppendUint(dst, uint64(v.TreasureY))
	dst = cbor.AppendText(dst, "advs")
	dst = cbor.AppendArrayHeader(dst, len(v.Adventurers))
	for i := range v.Adventurers {
		dst = appendAdventurerCBORMap(dst, v.Adventurers[i])
	}
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendText(dst, "traps")
	dst = cbor.AppendArrayHeader(dst, len(v.Traps))
	for i := range v.Traps {
		dst = appendTrapCBORMap(dst, v.Traps[i])
	}
	dst = cbor.AppendText(dst, "walls")
	dst = cbor.AppendArrayHeader(dst, len(v.Walls))
	for i := range v.Walls {
		dst = cbor.AppendUint(dst, uint64(v.Walls[i]))
	}
	dst = cbor.AppendText(dst, "budget")
	dst = cbor.AppendUint(dst, uint64(v.TrapBudget))
	dst = cbor.AppendText(dst, "winner")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendText(dst, "explored")
	dst = cbor.AppendArrayHeader(dst, len(v.Explored))
	for i := range v.Explored {
		dst = cbor.AppendUint(dst, uint64(v.Explored[i]))
	}
	return dst
}

func decodeDMViewCBORMap(cr *cbor.Reader) (DMView, error) {
	var out DMView
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "ex":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ExitX = v
		case "ey":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ExitY = v
		case "tx":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TreasureX = v
		case "ty":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TreasureY = v
		case "advs":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Adventurer, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeAdventurerCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Adventurers = slice
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		case "traps":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Trap, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeTrapCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Traps = slice
		case "walls":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.Walls = slice
		case "budget":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TrapBudget = v
		case "winner":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Winner = v
		case "explored":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.Explored = slice
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v DMView) AppendCBORInMapTo(dst []byte) []byte {
	return appendDMViewCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *DMView) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeDMViewCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape DMView declares.
func (v DMView) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape DMView declares.
func (v *DMView) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}
