// Code generated by ebigent generate; DO NOT EDIT.
//
// These are the codecs this package's types were asked for, and the ask
// is the call: since tinybind v0.5.23 there is no declaration to write,
// and the entry point named decides the container
// (requirement:cborbind-migration).
//
// What is asked for comes from the rule set declaration and nowhere else
// (requirement:stage-declares-its-wire). A world is a map, because only a
// map can be diffed and because the two ends may ship apart. An action is
// an array, because it is one small message with no baseline to diff
// against and both ends are rebuilt together.
//
// Nothing calls these. They are what the codec generator reads, and the
// linker drops them.

package msg

import "github.com/shibukawa/tinybind-go/cborbind"

// askActionInput is the action position of a rule set: the whole value in the
// array shape.
func askActionInput(dst []byte, v ActionInput) []byte { return cborbind.AppendCBORInArrayTo(dst, v) }

func askDecodeActionInput(data []byte) (ActionInput, error) { return cborbind.DecodeCBORInArrayFrom[ActionInput](data) }

// askDungeonState is the world position of a rule set: the whole value in the
// map shape.
func askDungeonState(dst []byte, v DungeonState) []byte { return cborbind.AppendCBORInMapTo(dst, v) }

func askDecodeDungeonState(data []byte) (DungeonState, error) { return cborbind.DecodeCBORInMapFrom[DungeonState](data) }
