// Code generated by ebigent generate; DO NOT EDIT.
//
// These are the protocol level of concept:configuration-scope: the game's
// own contract, settled in ebigent.toml before this artifact existed. They
// are constants rather than settings because nothing here can differ
// between two launches of one build — reading them at startup would only
// pretend the answer were still open (rule:config-tier-placement).
//
// Edit [protocol] in ebigent.toml and run ebigent generate.

package ebigentgen

// Package is the import path identifying this game, subpath included —
// half of the pair two peers compare before they play
// (decision:module-path-is-game-identity).
const Package = "github.com/shibukawa/ebigentserver/tutorial/step2-lobby"

// Title is what a browse list and a window caption show. It identifies
// nothing, so it may be reworded or localized freely.
const Title = "tictactoe"

// Shape is concept:participant-shape, Realtime is
// concept:realtime-intensity, and View is concept:view-arrangement.
const (
	Shape    = "duo"
	Realtime = "turn_based"
	View     = "shared"
)

// Sync is concept:synchronization-mode. It is settled here rather than per
// launch because a mode is a property of the game, and offering it at
// startup is the mistake rule:build-tag-only-for-linkage names in its own
// domain.
const Sync = "server_authoritative"

// Devices are the input devices this build accepts. A game cannot accept
// one it never wrote an api:input-adapter for.
var Devices = []string{"keyboard"}

// SeatCount is how many concept:player-slot entries the rules declare.
const SeatCount = 2

// FillUnclaimedSeats reports what a match does with a seat nobody took:
// true completes the roster with a bot so play can start, false starts
// short.
const FillUnclaimedSeats = true

// Teamed reports whether the game divides its seats at all.
const Teamed = false

// Seat is one declared seat, with the team division already resolved.
type Seat struct {
	// Slot is the concept:player-slot id, counting from one.
	Slot uint16
	// Team is the team it belongs to, empty when the game has none.
	Team string
	// Occupant bounds who may take it: any, human, or bot.
	Occupant string
}

// Seats is the declared seat composition. api:roster fills these and
// never invents one.
var Seats = []Seat{
	{Slot: 1, Team: "", Occupant: "any"},
	{Slot: 2, Team: "", Occupant: "any"},
}

// Axis is one term matchmaking may filter on. Band marks the asymmetric
// comparison: the room states a range and a joiner brings their own
// value, since a rank is something a player has rather than something
// they pick.
type Axis struct {
	Name string
	Band bool
}

// Axes is the condition set this game declares
// (requirement:conditional-matchmaking). Both ends compare the same axes
// because both were built from this table, which is what lets a refusal
// name the term it failed.
var Axes = []Axis{}
