// Package genrotated is generated by ebigentserver/behavior from the approved
// chip library. It is source on purpose — read it, diff it, review it —
// but edits belong upstream in the chips or predicates
// (rule:regeneration-preserves-approved-nodes).
package genrotated

import (
	"context"

	"github.com/shibukawa/ebigentserver/session"
	"github.com/shibukawa/ebigentserver/tutorial/step5-simulate/distill/pred"
	"github.com/shibukawa/ebigentserver/tutorial/step5-simulate/game"
	"github.com/shibukawa/ebigentserver/tutorial/step5-simulate/msg"
)

// Decide is the compiled decision list. Earlier cases take precedence,
// exactly as the chips were mined and approved.
func Decide(obs game.Sight) (msg.Move, bool) {
	switch {
	case pred.PreferredCellIs(obs, 4):
		// chip preferred_cell_is_4 → play_4 (coverage 400, counterexamples 0)
		return msg.Move{Cell: 4}, true
	case pred.BlockingMoveIs(obs, 3):
		// chip blocking_move_is_3 → play_3 (coverage 271, counterexamples 0)
		return msg.Move{Cell: 3}, true
	case pred.PreferredCellIs(obs, 7):
		// chip preferred_cell_is_7 → play_7 (coverage 268, counterexamples 0)
		return msg.Move{Cell: 7}, true
	case pred.PreferredCellIs(obs, 0):
		// chip preferred_cell_is_0 → play_0 (coverage 116, counterexamples 0)
		return msg.Move{Cell: 0}, true
	case pred.WinningMoveIs(obs, 8):
		// chip winning_move_is_8 → play_8 (coverage 77, counterexamples 0)
		return msg.Move{Cell: 8}, true
	case pred.WinningMoveIs(obs, 6):
		// chip winning_move_is_6 → play_6 (coverage 20, counterexamples 0)
		return msg.Move{Cell: 6}, true
	case pred.WinningMoveIs(obs, 1):
		// chip winning_move_is_1 → play_1 (coverage 15, counterexamples 0)
		return msg.Move{Cell: 1}, true
	case pred.WinningMoveIs(obs, 3):
		// chip winning_move_is_3 → play_3 (coverage 8, counterexamples 0)
		return msg.Move{Cell: 3}, true
	case pred.BlockingMoveIs(obs, 2):
		// chip blocking_move_is_2 → play_2 (coverage 8, counterexamples 0)
		return msg.Move{Cell: 2}, true
	case pred.BlockingMoveIs(obs, 6):
		// chip blocking_move_is_6 → play_6 (coverage 8, counterexamples 0)
		return msg.Move{Cell: 6}, true
	case pred.WinningMoveIs(obs, 5):
		// chip winning_move_is_5 → play_5 (coverage 4, counterexamples 0)
		return msg.Move{Cell: 5}, true
	case pred.PreferredCellIs(obs, 8):
		// chip preferred_cell_is_8 → play_8 (coverage 267, counterexamples 0)
		return msg.Move{Cell: 8}, true
	case pred.BlockingMoveIs(obs, 7):
		// chip blocking_move_is_7 → play_7 (coverage 11, counterexamples 0)
		return msg.Move{Cell: 7}, true
	case pred.PreferredCellIs(obs, 2):
		// chip preferred_cell_is_2 → play_2 (coverage 299, counterexamples 0)
		return msg.Move{Cell: 2}, true
	case pred.BlockingMoveIs(obs, 5):
		// chip blocking_move_is_5 → play_5 (coverage 4, counterexamples 0)
		return msg.Move{Cell: 5}, true
	case pred.PreferredCellIs(obs, 3):
		// chip preferred_cell_is_3 → play_3 (coverage 3, counterexamples 0)
		return msg.Move{Cell: 3}, true
	case pred.PreferredCellIs(obs, 5):
		// chip preferred_cell_is_5 → play_5 (coverage 2, counterexamples 0)
		return msg.Move{Cell: 5}, true
	case pred.PreferredCellIs(obs, 6):
		// chip preferred_cell_is_6 → play_6 (coverage 2, counterexamples 0)
		return msg.Move{Cell: 6}, true
	case pred.PreferredCellIs(obs, 1):
		// chip preferred_cell_is_1 → play_1 (coverage 1, counterexamples 0)
		return msg.Move{Cell: 1}, true
	}
	var zero msg.Move
	return zero, false
}

// Rotated seats the compiled policy behind api:agent-interface: an
// ordinary agent, indistinguishable from a hand-written bot.
type Rotated struct {
	last game.Sight
	has  bool
}

func (*Rotated) Joined(session.SlotID) {}

func (a *Rotated) Observe(obs game.Sight) { a.last, a.has = obs, true }

func (a *Rotated) Decide(context.Context) (msg.Move, bool) {
	if !a.has {
		var zero msg.Move
		return zero, false
	}
	return Decide(a.last)
}

func (*Rotated) Ended(session.Result) {}

// actionName maps a decided action back to its vocabulary term, for
// the generated episode-fixture tests.
func actionName(a msg.Move) string {
	switch a {
	case msg.Move{Cell: 0}:
		return "play_0"
	case msg.Move{Cell: 1}:
		return "play_1"
	case msg.Move{Cell: 2}:
		return "play_2"
	case msg.Move{Cell: 3}:
		return "play_3"
	case msg.Move{Cell: 4}:
		return "play_4"
	case msg.Move{Cell: 5}:
		return "play_5"
	case msg.Move{Cell: 6}:
		return "play_6"
	case msg.Move{Cell: 7}:
		return "play_7"
	case msg.Move{Cell: 8}:
		return "play_8"
	}
	return ""
}
