package behavior

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// CodegenSpec targets one game's types.
type CodegenSpec struct {
	// Package is the generated package name.
	Package string
	// Imports are the import paths the expressions need.
	Imports []string
	// ObsType and ActionType are the game's sight and action
	// types as written in code, e.g. "ttt.Sight".
	ObsType    string
	ActionType string
	// AgentName names the generated agent type.
	AgentName string
	// SessionImport is the session package path (for the Agent
	// implementation).
	SessionImport string
}

// GenerateAgent emits the approved chips as plain Go
// (decision:behavior-tree-compiled-to-go): a Decide function whose switch
// IS the decision list, and an api:agent-interface implementation around
// it. The output is source a developer may read and diff; edits belong
// upstream in the chip library (rule:regeneration-preserves-approved-nodes).
//
// Determinism (rule:generated-agent-code-is-deterministic) holds because
// every emitted expression comes from the vocabulary's GoExpr strings,
// which judge the sight with the same integer math the simulation
// uses — no clock, no randomness, no float enters here.
func GenerateAgent(spec CodegenSpec, v *Vocabulary, lib *Library) ([]byte, error) {
	features := map[string]Feature{}
	for _, f := range v.Features {
		features[f.Name] = f
	}
	actions := map[string]ActionDef{}
	for _, a := range v.Actions {
		actions[a.Name] = a
	}
	chips := lib.Approved()
	sort.SliceStable(chips, func(i, j int) bool { return chips[i].Priority < chips[j].Priority })
	if len(chips) == 0 {
		return nil, fmt.Errorf("behavior: no approved chips to generate from")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Package %s is generated by ebigentserver/behavior from the approved\n", spec.Package)
	b.WriteString("// chip library. It is source on purpose — read it, diff it, review it —\n")
	b.WriteString("// but edits belong upstream in the chips or predicates\n")
	b.WriteString("// (rule:regeneration-preserves-approved-nodes).\n")
	fmt.Fprintf(&b, "package %s\n\nimport (\n\t\"context\"\n\n", spec.Package)
	fmt.Fprintf(&b, "\t%q\n", spec.SessionImport)
	for _, imp := range spec.Imports {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Decide is the compiled decision list. Earlier cases take precedence,\n")
	b.WriteString("// exactly as the chips were mined and approved.\n")
	fmt.Fprintf(&b, "func Decide(obs %s) (%s, bool) {\n\tswitch {\n", spec.ObsType, spec.ActionType)
	for _, chip := range chips {
		f, ok := features[chip.Condition]
		if !ok {
			return nil, fmt.Errorf("behavior: chip %q names unknown predicate %q (stale vocabulary fails the build, as it should)", chip.Key(), chip.Condition)
		}
		a, ok := actions[chip.Action]
		if !ok {
			return nil, fmt.Errorf("behavior: chip %q names unknown action %q", chip.Key(), chip.Action)
		}
		fmt.Fprintf(&b, "\tcase %s:\n\t\t// chip %s → %s (coverage %d, counterexamples %d)\n\t\treturn %s, true\n",
			f.GoExpr, chip.Condition, chip.Action, chip.Coverage, chip.Counterexamples, a.GoExpr)
	}
	fmt.Fprintf(&b, "\t}\n\tvar zero %s\n\treturn zero, false\n}\n\n", spec.ActionType)

	fmt.Fprintf(&b, "// %s seats the compiled policy behind api:agent-interface: an\n", spec.AgentName)
	b.WriteString("// ordinary agent, indistinguishable from a hand-written bot.\n")
	fmt.Fprintf(&b, "type %s struct {\n\tlast %s\n\thas  bool\n}\n\n", spec.AgentName, spec.ObsType)
	fmt.Fprintf(&b, "func (*%s) Joined(session.SlotID) {}\n\n", spec.AgentName)
	fmt.Fprintf(&b, "func (a *%s) Observe(obs %s) { a.last, a.has = obs, true }\n\n", spec.AgentName, spec.ObsType)
	fmt.Fprintf(&b, "func (a *%s) Decide(context.Context) (%s, bool) {\n\tif !a.has {\n\t\tvar zero %s\n\t\treturn zero, false\n\t}\n\treturn Decide(a.last)\n}\n\n",
		spec.AgentName, spec.ActionType, spec.ActionType)
	fmt.Fprintf(&b, "func (*%s) Ended(session.Result) {}\n\n", spec.AgentName)

	b.WriteString("// actionName maps a decided action back to its vocabulary term, for\n")
	b.WriteString("// the generated episode-fixture tests.\n")
	fmt.Fprintf(&b, "func actionName(a %s) string {\n\tswitch a {\n", spec.ActionType)
	for _, a := range v.Actions {
		fmt.Fprintf(&b, "\tcase %s:\n\t\treturn %q\n", a.GoExpr, a.Name)
	}
	b.WriteString("\t}\n\treturn \"\"\n}\n")

	return format.Source([]byte(b.String()))
}

// GenerateTests emits a test file whose fixtures are recorded situations
// (rule:predicate-tests-generated-from-episodes): each case replays one
// evidence moment and asserts the compiled Decide reproduces the recorded
// action. A regenerated or hand-edited predicate that changes meaning
// fails here immediately, pointing at a replayable episode and tick.
func GenerateTests(spec CodegenSpec, records []Record, maxCases int) ([]byte, error) {
	if maxCases <= 0 {
		maxCases = 32
	}
	if len(records) == 0 {
		return nil, ErrEmptyCorpus
	}
	stride := len(records)/maxCases + 1

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by ebigentserver/behavior: fixtures are real recorded\n")
	b.WriteString("// situations (rule:predicate-tests-generated-from-episodes), pinned to\n")
	b.WriteString("// their episode and tick so a failure names a replayable moment.\n")
	fmt.Fprintf(&b, "package %s\n\nimport (\n\t\"encoding/json\"\n\t\"testing\"\n\n", spec.Package)
	for _, imp := range spec.Imports {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")
	b.WriteString("func TestCompiledPolicyReproducesRecordedDecisions(t *testing.T) {\n")
	b.WriteString("\tcases := []struct {\n\t\tname string\n\t\tobs  string\n\t\twant string\n\t}{\n")
	n := 0
	for i := 0; i < len(records); i += stride {
		r := records[i]
		fmt.Fprintf(&b, "\t\t{name: %q, obs: %q, want: %q},\n",
			fmt.Sprintf("%s_tick%d_slot%d", r.Episode, r.Tick, r.Slot), string(r.Obs), r.Action)
		n++
	}
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\tfor _, c := range cases {\n\t\tt.Run(c.name, func(t *testing.T) {\n")
	fmt.Fprintf(&b, "\t\t\tvar obs %s\n\t\t\tif err := json.Unmarshal([]byte(c.obs), &obs); err != nil {\n\t\t\t\tt.Fatal(err)\n\t\t\t}\n", spec.ObsType)
	b.WriteString("\t\t\tgot, ok := Decide(obs)\n\t\t\tif !ok {\n\t\t\t\tt.Fatalf(\"no decision for a recorded decision point\")\n\t\t\t}\n")
	b.WriteString("\t\t\tif name := actionName(got); name != c.want {\n\t\t\t\tt.Fatalf(\"decided %s, recorded %s\", name, c.want)\n\t\t\t}\n")
	b.WriteString("\t\t})\n\t}\n}\n")
	if n == 0 {
		return nil, ErrEmptyCorpus
	}
	return format.Source([]byte(b.String()))
}
