// Code generated by ebigent generate; DO NOT EDIT.
//
// The delta half of concept:state-synchronization. tinybind-go generates
// the codecs for the world and wire types themselves; since v0.5.21 it
// generates no diff, patch, or delta encoding, so those are the
// framework's (decision:framework-side-delta-generation) and they are
// here.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// DecodeLimits bounds what a decoder in this file will read. They are
// resource limits rather than format rules, so they belong to the
// deployment and not to the protocol: two peers must agree on the shape
// of a message and need agree on nothing about how large one this process
// is willing to read (data:runtime-resource-budget). Startup may lower
// them; the values here suit a snapshot.
var DecodeLimits = cbor.DecoderOptions{
	MaxContainerItems:  1 << 16,
	MaxStringBytes:     4 << 20,
	MaxInputBytes:      64 << 20,
	MaxRawMessageBytes: 64 << 20,
	RejectFloats:       true,
}

// equalUnit compares two slices element by element. A delta asks whether
// a field changed, and for a slice that is a question about contents.
func equalUnit(a, b []Unit) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// appendUnitSlice writes the slice as one CBOR array, each element
// through its own generated codec.
func appendUnitSlice(dst []byte, v []Unit) []byte {
	dst = cbor.AppendArrayHeader(dst, len(v))
	for i := range v {
		dst = v[i].AppendCBORTo(dst)
	}
	return dst
}

// readUnitSlice reads one CBOR array of elements into out, reusing its
// capacity so a steady state allocates nothing.
func readUnitSlice(r *cbor.Reader, out []Unit) ([]Unit, error) {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, &cbor.Error{Offset: int64(r.Offset()), Path: "Unit", Err: cbor.ErrUnexpectedToken}
	}
	out = out[:0]
	for range n {
		var e Unit
		raw, err := r.ReadRaw()
		if err != nil {
			return out, err
		}
		if err := e.DecodeCBORFrom(raw); err != nil {
			return out, err
		}
		out = append(out, e)
	}
	return out, nil
}

// equalGlimpse compares two slices element by element. A delta asks whether
// a field changed, and for a slice that is a question about contents.
func equalGlimpse(a, b []Glimpse) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// appendGlimpseSlice writes the slice as one CBOR array, each element
// through its own generated codec.
func appendGlimpseSlice(dst []byte, v []Glimpse) []byte {
	dst = cbor.AppendArrayHeader(dst, len(v))
	for i := range v {
		dst = v[i].AppendCBORTo(dst)
	}
	return dst
}

// readGlimpseSlice reads one CBOR array of elements into out, reusing its
// capacity so a steady state allocates nothing.
func readGlimpseSlice(r *cbor.Reader, out []Glimpse) ([]Glimpse, error) {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, &cbor.Error{Offset: int64(r.Offset()), Path: "Glimpse", Err: cbor.ErrUnexpectedToken}
	}
	out = out[:0]
	for range n {
		var e Glimpse
		raw, err := r.ReadRaw()
		if err != nil {
			return out, err
		}
		if err := e.DecodeCBORFrom(raw); err != nil {
			return out, err
		}
		out = append(out, e)
	}
	return out, nil
}

// RTSStateDelta is what changed between two RTSState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful. The bit
// order is declaration order, so moving a field moves the wire.
type RTSStateDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	Units []Unit
	// bit 2
	NextSeq uint32
	// bit 3
	TickLimit uint32
	// bit 4
	Over bool
	// bit 5
	Winner uint16
}

// DiffRTSStateInto fills d with what changed between baseline and
// current, and reports whether anything did.
func DiffRTSStateInto(d *RTSStateDelta, baseline, current RTSState) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if !equalUnit(baseline.Units, current.Units) {
		d.Present |= 1 << 1
		d.Units = current.Units
	}
	if baseline.NextSeq != current.NextSeq {
		d.Present |= 1 << 2
		d.NextSeq = current.NextSeq
	}
	if baseline.TickLimit != current.TickLimit {
		d.Present |= 1 << 3
		d.TickLimit = current.TickLimit
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 4
		d.Over = current.Over
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 5
		d.Winner = current.Winner
	}
	return d.Present != 0
}

// DiffRTSState returns what changed between baseline and current.
func DiffRTSState(baseline, current RTSState) RTSStateDelta {
	var d RTSStateDelta
	DiffRTSStateInto(&d, baseline, current)
	return d
}

// ApplyRTSStateDelta puts d back onto v. A bit Present does not name
// leaves that field as it stands, which is what makes a delta a delta.
func ApplyRTSStateDelta(v *RTSState, d RTSStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.Units = d.Units
	}
	if d.Present&(1<<2) != 0 {
		v.NextSeq = d.NextSeq
	}
	if d.Present&(1<<3) != 0 {
		v.TickLimit = d.TickLimit
	}
	if d.Present&(1<<4) != 0 {
		v.Over = d.Over
	}
	if d.Present&(1<<5) != 0 {
		v.Winner = d.Winner
	}
	return nil
}

// AppendCBORTo appends d as one CBOR array: the mask, then the values it
// names, in bit order. A field the mask omits costs nothing.
func (v RTSStateDelta) AppendCBORTo(dst []byte) []byte {
	n := 1
	for bit := range 6 {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = appendUnitSlice(dst, v.Units)
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.NextSeq))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.TickLimit))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	return dst
}

// DecodeCBORFrom reads one delta into v, and refuses anything after it:
// a trailing item means the sender and the receiver disagree about the
// shape, which concept:cbor-wire-profile cannot detect any other way.
func (v *RTSStateDelta) DecodeCBORFrom(data []byte) error {
	r, err := cbor.NewReader(data, DecodeLimits)
	if err != nil {
		return err
	}
	if err := v.decodeFrom(r); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// decodeFrom reads one delta off r.
func (v *RTSStateDelta) decodeFrom(r *cbor.Reader) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "RTSStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Tick = uint64(x)
		read++
	}
	if present&(1<<1) != 0 {
		xs, err := readUnitSlice(r, v.Units)
		if err != nil {
			return err
		}
		v.Units = xs
		read++
	}
	if present&(1<<2) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.NextSeq = uint32(x)
		read++
	}
	if present&(1<<3) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.TickLimit = uint32(x)
		read++
	}
	if present&(1<<4) != 0 {
		x, err := r.ReadBool()
		if err != nil {
			return err
		}
		v.Over = bool(x)
		read++
	}
	if present&(1<<5) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Winner = uint16(x)
		read++
	}
	if read != n {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "RTSStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	return nil
}

// PlayerViewDelta is what changed between two PlayerView values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful. The bit
// order is declaration order, so moving a field moves the wire.
type PlayerViewDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	You uint16
	// bit 2
	Own []Unit
	// bit 3
	Visible []Glimpse
	// bit 4
	OwnAlive uint16
	// bit 5
	EnemyAlive uint16
	// bit 6
	Over bool
	// bit 7
	Winner uint16
}

// DiffPlayerViewInto fills d with what changed between baseline and
// current, and reports whether anything did.
func DiffPlayerViewInto(d *PlayerViewDelta, baseline, current PlayerView) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if baseline.You != current.You {
		d.Present |= 1 << 1
		d.You = current.You
	}
	if !equalUnit(baseline.Own, current.Own) {
		d.Present |= 1 << 2
		d.Own = current.Own
	}
	if !equalGlimpse(baseline.Visible, current.Visible) {
		d.Present |= 1 << 3
		d.Visible = current.Visible
	}
	if baseline.OwnAlive != current.OwnAlive {
		d.Present |= 1 << 4
		d.OwnAlive = current.OwnAlive
	}
	if baseline.EnemyAlive != current.EnemyAlive {
		d.Present |= 1 << 5
		d.EnemyAlive = current.EnemyAlive
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 6
		d.Over = current.Over
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 7
		d.Winner = current.Winner
	}
	return d.Present != 0
}

// DiffPlayerView returns what changed between baseline and current.
func DiffPlayerView(baseline, current PlayerView) PlayerViewDelta {
	var d PlayerViewDelta
	DiffPlayerViewInto(&d, baseline, current)
	return d
}

// ApplyPlayerViewDelta puts d back onto v. A bit Present does not name
// leaves that field as it stands, which is what makes a delta a delta.
func ApplyPlayerViewDelta(v *PlayerView, d PlayerViewDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.You = d.You
	}
	if d.Present&(1<<2) != 0 {
		v.Own = d.Own
	}
	if d.Present&(1<<3) != 0 {
		v.Visible = d.Visible
	}
	if d.Present&(1<<4) != 0 {
		v.OwnAlive = d.OwnAlive
	}
	if d.Present&(1<<5) != 0 {
		v.EnemyAlive = d.EnemyAlive
	}
	if d.Present&(1<<6) != 0 {
		v.Over = d.Over
	}
	if d.Present&(1<<7) != 0 {
		v.Winner = d.Winner
	}
	return nil
}

// AppendCBORTo appends d as one CBOR array: the mask, then the values it
// names, in bit order. A field the mask omits costs nothing.
func (v PlayerViewDelta) AppendCBORTo(dst []byte) []byte {
	n := 1
	for bit := range 8 {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.You))
	}
	if v.Present&(1<<2) != 0 {
		dst = appendUnitSlice(dst, v.Own)
	}
	if v.Present&(1<<3) != 0 {
		dst = appendGlimpseSlice(dst, v.Visible)
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.OwnAlive))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.EnemyAlive))
	}
	if v.Present&(1<<6) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	if v.Present&(1<<7) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	return dst
}

// DecodeCBORFrom reads one delta into v, and refuses anything after it:
// a trailing item means the sender and the receiver disagree about the
// shape, which concept:cbor-wire-profile cannot detect any other way.
func (v *PlayerViewDelta) DecodeCBORFrom(data []byte) error {
	r, err := cbor.NewReader(data, DecodeLimits)
	if err != nil {
		return err
	}
	if err := v.decodeFrom(r); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// decodeFrom reads one delta off r.
func (v *PlayerViewDelta) decodeFrom(r *cbor.Reader) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerViewDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Tick = uint64(x)
		read++
	}
	if present&(1<<1) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.You = uint16(x)
		read++
	}
	if present&(1<<2) != 0 {
		xs, err := readUnitSlice(r, v.Own)
		if err != nil {
			return err
		}
		v.Own = xs
		read++
	}
	if present&(1<<3) != 0 {
		xs, err := readGlimpseSlice(r, v.Visible)
		if err != nil {
			return err
		}
		v.Visible = xs
		read++
	}
	if present&(1<<4) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.OwnAlive = uint16(x)
		read++
	}
	if present&(1<<5) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.EnemyAlive = uint16(x)
		read++
	}
	if present&(1<<6) != 0 {
		x, err := r.ReadBool()
		if err != nil {
			return err
		}
		v.Over = bool(x)
		read++
	}
	if present&(1<<7) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Winner = uint16(x)
		read++
	}
	if read != n {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerViewDelta", Err: cbor.ErrUnexpectedToken}
	}
	return nil
}
