// Code generated by ebigent generate; DO NOT EDIT.

package msg

// SchemaVersion is the wire fingerprint of every type in this package —
// the half of data:game-version that moves when the bytes move.
//
// It is derived from the shapes below and covers wire-observable shape
// alone, so regenerating with a newer toolchain that emits the same bytes
// leaves it unchanged. It is compared for equality and nothing else: there
// is no ordering here and no partial compatibility to negotiate, because
// concept:cbor-wire-profile puts no field names on the wire for a
// mismatch to be noticed in (rule:game-version-must-match).
const SchemaVersion = "46544ad4b4f8b5ff"
