// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:c56506f3c032fd9bf93b5de81e06cb305e88d4ab0730ad2c4cb825e4a0fc7810 self=sha256:982865e2816df2bb4547de028340550b2742b9692e73a43642f1eea1529bda66 outputs=tinybind_gen.go

package msg

import (
	"github.com/shibukawa/tinybind-go/cborbind"
	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

func appendCommandCBORArray(dst []byte, v Command) []byte {
	dst = cbor.AppendArrayHeader(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, uint64(v.Unit))
	dst = cbor.AppendUint(dst, uint64(v.TargetX))
	dst = cbor.AppendUint(dst, uint64(v.TargetY))
	return dst
}

func decodeCommandCBORArray(cr *cbor.Reader) (Command, error) {
	var out Command
	n, indefinite, err := cr.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite || n != 4 {
		return out, cborbind.ErrShape
	}
	{
		v, err := cr.ReadUint32()
		if err != nil {
			return out, err
		}
		out.Tick = v
	}
	{
		v, err := cr.ReadUint32()
		if err != nil {
			return out, err
		}
		out.Unit = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.TargetX = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.TargetY = v
	}
	return out, nil
}

// AppendCBORInArrayTo appends v as CBOR, for cborbind.AppendCBORInArrayTo.
func (v Command) AppendCBORInArrayTo(dst []byte) []byte {
	return appendCommandCBORArray(dst, v)
}

// DecodeCBORInArrayFrom decodes one CBOR value into v, for cborbind.DecodeCBORInArrayFrom.
func (v *Command) DecodeCBORInArrayFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeCommandCBORArray(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Command declares.
func (v Command) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInArrayTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Command declares.
func (v *Command) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInArrayFrom(data)
}

func appendUnitCBORMap(dst []byte, v Unit) []byte {
	dst = cbor.AppendMapHeader(dst, 7)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "hp")
	dst = cbor.AppendInt(dst, int64(v.HP))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "tx")
	dst = cbor.AppendUint(dst, uint64(v.TX))
	dst = cbor.AppendText(dst, "ty")
	dst = cbor.AppendUint(dst, uint64(v.TY))
	dst = cbor.AppendText(dst, "alive")
	dst = cbor.AppendBool(dst, v.Alive)
	return dst
}

func decodeUnitCBORMap(cr *cbor.Reader) (Unit, error) {
	var out Unit
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "hp":
			v, err := cr.ReadInt8()
			if err != nil {
				return out, err
			}
			out.HP = v
		case "id":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "tx":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TX = v
		case "ty":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.TY = v
		case "alive":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Alive = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v Unit) AppendCBORInMapTo(dst []byte) []byte {
	return appendUnitCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *Unit) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeUnitCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Unit declares.
func (v Unit) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Unit declares.
func (v *Unit) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendRTSStateCBORMap(dst []byte, v RTSState) []byte {
	dst = cbor.AppendMapHeader(dst, 6)
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendText(dst, "limit")
	dst = cbor.AppendUint(dst, uint64(v.TickLimit))
	dst = cbor.AppendText(dst, "units")
	dst = cbor.AppendArrayHeader(dst, len(v.Units))
	for i := range v.Units {
		dst = appendUnitCBORMap(dst, v.Units[i])
	}
	dst = cbor.AppendText(dst, "winner")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendText(dst, "next_seq")
	dst = cbor.AppendUint(dst, uint64(v.NextSeq))
	return dst
}

func decodeRTSStateCBORMap(cr *cbor.Reader) (RTSState, error) {
	var out RTSState
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		case "limit":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.TickLimit = v
		case "units":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Unit, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeUnitCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Units = slice
		case "winner":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Winner = v
		case "next_seq":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.NextSeq = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v RTSState) AppendCBORInMapTo(dst []byte) []byte {
	return appendRTSStateCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *RTSState) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeRTSStateCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape RTSState declares.
func (v RTSState) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape RTSState declares.
func (v *RTSState) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendGlimpseCBORMap(dst []byte, v Glimpse) []byte {
	dst = cbor.AppendMapHeader(dst, 4)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "owner")
	dst = cbor.AppendUint(dst, uint64(v.Owner))
	return dst
}

func decodeGlimpseCBORMap(cr *cbor.Reader) (Glimpse, error) {
	var out Glimpse
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "id":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "owner":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Owner = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v Glimpse) AppendCBORInMapTo(dst []byte) []byte {
	return appendGlimpseCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *Glimpse) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeGlimpseCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Glimpse declares.
func (v Glimpse) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Glimpse declares.
func (v *Glimpse) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendPlayerViewCBORMap(dst []byte, v PlayerView) []byte {
	dst = cbor.AppendMapHeader(dst, 8)
	dst = cbor.AppendText(dst, "own")
	dst = cbor.AppendArrayHeader(dst, len(v.Own))
	for i := range v.Own {
		dst = appendUnitCBORMap(dst, v.Own[i])
	}
	dst = cbor.AppendText(dst, "you")
	dst = cbor.AppendUint(dst, uint64(v.You))
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendText(dst, "winner")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendText(dst, "visible")
	dst = cbor.AppendArrayHeader(dst, len(v.Visible))
	for i := range v.Visible {
		dst = appendGlimpseCBORMap(dst, v.Visible[i])
	}
	dst = cbor.AppendText(dst, "own_alive")
	dst = cbor.AppendUint(dst, uint64(v.OwnAlive))
	dst = cbor.AppendText(dst, "enemy_alive")
	dst = cbor.AppendUint(dst, uint64(v.EnemyAlive))
	return dst
}

func decodePlayerViewCBORMap(cr *cbor.Reader) (PlayerView, error) {
	var out PlayerView
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "own":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Unit, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeUnitCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Own = slice
		case "you":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.You = v
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		case "winner":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Winner = v
		case "visible":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Glimpse, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeGlimpseCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Visible = slice
		case "own_alive":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.OwnAlive = v
		case "enemy_alive":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.EnemyAlive = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v PlayerView) AppendCBORInMapTo(dst []byte) []byte {
	return appendPlayerViewCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *PlayerView) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodePlayerViewCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape PlayerView declares.
func (v PlayerView) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape PlayerView declares.
func (v *PlayerView) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}
