// Code generated by ebigent generate; DO NOT EDIT.
//
// The delta half of concept:state-synchronization. tinybind-go generates
// the codecs for the world and wire types themselves; since v0.5.21 it
// generates no diff, patch, or delta encoding, so those are the
// framework's (decision:framework-side-delta-generation) and they are
// here.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// DecodeLimits bounds what a decoder in this file will read. They are
// resource limits rather than format rules, so they belong to the
// deployment and not to the protocol: two peers must agree on the shape
// of a message and need agree on nothing about how large one this process
// is willing to read (data:runtime-resource-budget). Startup may lower
// them; the values here suit a snapshot.
var DecodeLimits = cbor.DecoderOptions{
	MaxContainerItems:  1 << 16,
	MaxStringBytes:     4 << 20,
	MaxInputBytes:      64 << 20,
	MaxRawMessageBytes: 64 << 20,
	RejectFloats:       true,
}

// PongStateDelta is what changed between two PongState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful. The bit
// order is declaration order, so moving a field moves the wire.
type PongStateDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	BallX Fixed1024
	// bit 2
	BallY Fixed1024
	// bit 3
	VelX Fixed65536
	// bit 4
	VelY Fixed65536
	// bit 5
	LeftY Fixed1024
	// bit 6
	RightY Fixed1024
	// bit 7
	ScoreL uint8
	// bit 8
	ScoreR uint8
	// bit 9
	Winner uint16
	// bit 10
	Over bool
}

// DiffPongStateInto fills d with what changed between baseline and
// current, and reports whether anything did.
func DiffPongStateInto(d *PongStateDelta, baseline, current PongState) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if baseline.BallX != current.BallX {
		d.Present |= 1 << 1
		d.BallX = current.BallX
	}
	if baseline.BallY != current.BallY {
		d.Present |= 1 << 2
		d.BallY = current.BallY
	}
	if baseline.VelX != current.VelX {
		d.Present |= 1 << 3
		d.VelX = current.VelX
	}
	if baseline.VelY != current.VelY {
		d.Present |= 1 << 4
		d.VelY = current.VelY
	}
	if baseline.LeftY != current.LeftY {
		d.Present |= 1 << 5
		d.LeftY = current.LeftY
	}
	if baseline.RightY != current.RightY {
		d.Present |= 1 << 6
		d.RightY = current.RightY
	}
	if baseline.ScoreL != current.ScoreL {
		d.Present |= 1 << 7
		d.ScoreL = current.ScoreL
	}
	if baseline.ScoreR != current.ScoreR {
		d.Present |= 1 << 8
		d.ScoreR = current.ScoreR
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 9
		d.Winner = current.Winner
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 10
		d.Over = current.Over
	}
	return d.Present != 0
}

// DiffPongState returns what changed between baseline and current.
func DiffPongState(baseline, current PongState) PongStateDelta {
	var d PongStateDelta
	DiffPongStateInto(&d, baseline, current)
	return d
}

// ApplyPongStateDelta puts d back onto v. A bit Present does not name
// leaves that field as it stands, which is what makes a delta a delta.
func ApplyPongStateDelta(v *PongState, d PongStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.BallX = d.BallX
	}
	if d.Present&(1<<2) != 0 {
		v.BallY = d.BallY
	}
	if d.Present&(1<<3) != 0 {
		v.VelX = d.VelX
	}
	if d.Present&(1<<4) != 0 {
		v.VelY = d.VelY
	}
	if d.Present&(1<<5) != 0 {
		v.LeftY = d.LeftY
	}
	if d.Present&(1<<6) != 0 {
		v.RightY = d.RightY
	}
	if d.Present&(1<<7) != 0 {
		v.ScoreL = d.ScoreL
	}
	if d.Present&(1<<8) != 0 {
		v.ScoreR = d.ScoreR
	}
	if d.Present&(1<<9) != 0 {
		v.Winner = d.Winner
	}
	if d.Present&(1<<10) != 0 {
		v.Over = d.Over
	}
	return nil
}

// AppendCBORTo appends d as one CBOR array: the mask, then the values it
// names, in bit order. A field the mask omits costs nothing.
func (v PongStateDelta) AppendCBORTo(dst []byte) []byte {
	n := 1
	for bit := range 11 {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendInt(dst, int64(v.BallX))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendInt(dst, int64(v.BallY))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendInt(dst, int64(v.VelX))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendInt(dst, int64(v.VelY))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendInt(dst, int64(v.LeftY))
	}
	if v.Present&(1<<6) != 0 {
		dst = cbor.AppendInt(dst, int64(v.RightY))
	}
	if v.Present&(1<<7) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ScoreL))
	}
	if v.Present&(1<<8) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.ScoreR))
	}
	if v.Present&(1<<9) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	if v.Present&(1<<10) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	return dst
}

// DecodeCBORFrom reads one delta into v, and refuses anything after it:
// a trailing item means the sender and the receiver disagree about the
// shape, which concept:cbor-wire-profile cannot detect any other way.
func (v *PongStateDelta) DecodeCBORFrom(data []byte) error {
	r, err := cbor.NewReader(data, DecodeLimits)
	if err != nil {
		return err
	}
	if err := v.decodeFrom(r); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// decodeFrom reads one delta off r.
func (v *PongStateDelta) decodeFrom(r *cbor.Reader) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PongStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Tick = uint64(x)
		read++
	}
	if present&(1<<1) != 0 {
		x, err := r.ReadInt64()
		if err != nil {
			return err
		}
		v.BallX = Fixed1024(x)
		read++
	}
	if present&(1<<2) != 0 {
		x, err := r.ReadInt64()
		if err != nil {
			return err
		}
		v.BallY = Fixed1024(x)
		read++
	}
	if present&(1<<3) != 0 {
		x, err := r.ReadInt64()
		if err != nil {
			return err
		}
		v.VelX = Fixed65536(x)
		read++
	}
	if present&(1<<4) != 0 {
		x, err := r.ReadInt64()
		if err != nil {
			return err
		}
		v.VelY = Fixed65536(x)
		read++
	}
	if present&(1<<5) != 0 {
		x, err := r.ReadInt64()
		if err != nil {
			return err
		}
		v.LeftY = Fixed1024(x)
		read++
	}
	if present&(1<<6) != 0 {
		x, err := r.ReadInt64()
		if err != nil {
			return err
		}
		v.RightY = Fixed1024(x)
		read++
	}
	if present&(1<<7) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.ScoreL = uint8(x)
		read++
	}
	if present&(1<<8) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.ScoreR = uint8(x)
		read++
	}
	if present&(1<<9) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Winner = uint16(x)
		read++
	}
	if present&(1<<10) != 0 {
		x, err := r.ReadBool()
		if err != nil {
			return err
		}
		v.Over = bool(x)
		read++
	}
	if read != n {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PongStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	return nil
}
