// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:80ddf8cffa86010a97ddc21658cb55b7b17d0785087c0c8a5b3f07676e119a20 self=sha256:054453152587298d72408dfbfee24f40a6eed3add38f1908e00d105c98c4010e outputs=tinybind_gen.go

package msg

import (
	"github.com/shibukawa/tinybind-go/cborbind"
	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

func appendPaddleInputCBORArray(dst []byte, v PaddleInput) []byte {
	dst = cbor.AppendArrayHeader(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendInt(dst, int64(v.MoveY))
	dst = cbor.AppendUint(dst, uint64(v.Buttons))
	return dst
}

func decodePaddleInputCBORArray(cr *cbor.Reader) (PaddleInput, error) {
	var out PaddleInput
	n, indefinite, err := cr.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite || n != 3 {
		return out, cborbind.ErrShape
	}
	{
		v, err := cr.ReadUint32()
		if err != nil {
			return out, err
		}
		out.Tick = v
	}
	{
		v, err := cr.ReadInt8()
		if err != nil {
			return out, err
		}
		out.MoveY = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.Buttons = v
	}
	return out, nil
}

// AppendCBORInArrayTo appends v as CBOR, for cborbind.AppendCBORInArrayTo.
func (v PaddleInput) AppendCBORInArrayTo(dst []byte) []byte {
	return appendPaddleInputCBORArray(dst, v)
}

// DecodeCBORInArrayFrom decodes one CBOR value into v, for cborbind.DecodeCBORInArrayFrom.
func (v *PaddleInput) DecodeCBORInArrayFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodePaddleInputCBORArray(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape PaddleInput declares.
func (v PaddleInput) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInArrayTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape PaddleInput declares.
func (v *PaddleInput) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInArrayFrom(data)
}

func appendPongStateCBORMap(dst []byte, v PongState) []byte {
	dst = cbor.AppendMapHeader(dst, 11)
	dst = cbor.AppendText(dst, "bx")
	dst = cbor.AppendInt(dst, int64(v.BallX))
	dst = cbor.AppendText(dst, "by")
	dst = cbor.AppendInt(dst, int64(v.BallY))
	dst = cbor.AppendText(dst, "ly")
	dst = cbor.AppendInt(dst, int64(v.LeftY))
	dst = cbor.AppendText(dst, "ry")
	dst = cbor.AppendInt(dst, int64(v.RightY))
	dst = cbor.AppendText(dst, "sl")
	dst = cbor.AppendUint(dst, uint64(v.ScoreL))
	dst = cbor.AppendText(dst, "sr")
	dst = cbor.AppendUint(dst, uint64(v.ScoreR))
	dst = cbor.AppendText(dst, "vx")
	dst = cbor.AppendInt(dst, int64(v.VelX))
	dst = cbor.AppendText(dst, "vy")
	dst = cbor.AppendInt(dst, int64(v.VelY))
	dst = cbor.AppendText(dst, "win")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	return dst
}

func decodePongStateCBORMap(cr *cbor.Reader) (PongState, error) {
	var out PongState
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "bx":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.BallX = Fixed1024(v)
		case "by":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.BallY = Fixed1024(v)
		case "ly":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.LeftY = Fixed1024(v)
		case "ry":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.RightY = Fixed1024(v)
		case "sl":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ScoreL = v
		case "sr":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.ScoreR = v
		case "vx":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.VelX = Fixed65536(v)
		case "vy":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.VelY = Fixed65536(v)
		case "win":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Winner = v
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v PongState) AppendCBORInMapTo(dst []byte) []byte {
	return appendPongStateCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *PongState) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodePongStateCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape PongState declares.
func (v PongState) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape PongState declares.
func (v *PongState) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}
