// Code generated by configbind/codegen; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:1b5acca445852a8be885a63a6260cf72a4c66b7159275fd31f4b1a4916d57055 self=sha256:0e45c5da7875451a20705cc5662c867d9e5f8640021b8915b760b3de19481593 outputs=tinybind_gen.go,configbind_gen.go

package cli

import (
	"fmt"
	"strconv"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerInitOptionsDefinition0()
	registerBuildOptionsDefinition1()
	registerConfigOptionsDefinition2()
	registerGenerateOptionsDefinition3()
	registerAnalyzeOptionsDefinition4()
	registerMergeOptionsDefinition5()
	registerDoctorOptionsDefinition6()
	registerVersionOptionsDefinition7()
	registerDevOptionsDefinition8()
	registerRunOptionsDefinition9()
	registerSimulateOptionsDefinition10()
	registerReplayOptionsDefinition11()
	registerEditOptionsDefinition12()
}

func registerInitOptionsDefinition0() {
	configbind.RegisterSubCommand[InitOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.InitOptions",
		Name:     "init",
		Help:     "scaffold a new project",
		Defaults: map[string]string{
			"seats":     "0",
			"yes":       "false",
			"skip_tidy": "false",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Key: "module", Env: "-", Help: "go module path"},
			{Key: "name", Env: "-", Help: "game name; defaults to the directory name"},
			{Key: "style", Env: "-", Help: "play style: solo, duo, or multi"},
			{Key: "agent", Env: "-", Help: "agentic environment: claude or other; decides where the analysis skill is written"},
			{Key: "seats", Env: "-", Help: "maximum players, for the multi style; 0 asks"},
			{Key: "shared_screen", Env: "-", Help: "do all players read the same screen content: yes or no; empty asks"},
			{Key: "sync", Env: "-", Help: "synchronization mode; a shared surface has none"},
			{Key: "yes", Env: "-", Help: "take the default for every unanswered question instead of prompting", Kind: cliparser.KindBool},
			{Key: "framework_path", Env: "-", Help: "path to a local framework checkout, added as a replace directive"},
			{Key: "skip_tidy", Env: "-", Help: "do not run go mod tidy or the verification build", Kind: cliparser.KindBool},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "dir", Name: "dir", Role: configbind.PositionalOptional, Help: "project directory, created if missing (default: the current directory)"},
		},
		Apply: applyInitOptionsDefinition0,
	})
}

func applyInitOptionsDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*InitOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply InitOptions: bad destination")
	}
	if v, ok := o.GetString("dir"); ok {
		p.Dir = v
	}
	if v, ok := o.GetString("module"); ok {
		p.Module = v
	}
	if v, ok := o.GetString("name"); ok {
		p.Name = v
	}
	if v, ok := o.GetString("style"); ok {
		p.Style = v
	}
	if v, ok := o.GetString("agent"); ok {
		p.Agent = v
	}
	if v, ok := o.GetString("seats"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: seats: %w", err)
		}
		p.Seats = int(n)
	} else {
		p.Seats = 0
	}
	if v, ok := o.GetString("shared_screen"); ok {
		p.SharedScreen = v
	}
	if v, ok := o.GetString("sync"); ok {
		p.Sync = v
	}
	if v, ok := o.GetString("yes"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: yes: %w", err)
		}
		p.Yes = bb
	} else {
		p.Yes = false
	}
	if v, ok := o.GetString("framework_path"); ok {
		p.FrameworkPath = v
	}
	if v, ok := o.GetString("skip_tidy"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: skip_tidy: %w", err)
		}
		p.SkipTidy = bb
	} else {
		p.SkipTidy = false
	}
	return nil
}

func registerBuildOptionsDefinition1() {
	configbind.RegisterSubCommand[BuildOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.BuildOptions",
		Name:     "build",
		Help:     "compile a declared build target",
		FlagMetas: []cliparser.FieldMeta{
			{Key: "output", Env: "-", Help: "output path; defaults to ./bin/<target>"},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "target", Name: "target", Role: configbind.PositionalOptional, Help: "target name from ebigent.toml; defaults to the dev target"},
		},
		Apply: applyBuildOptionsDefinition1,
	})
}

func applyBuildOptionsDefinition1(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*BuildOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply BuildOptions: bad destination")
	}
	if v, ok := o.GetString("target"); ok {
		p.Target = v
	}
	if v, ok := o.GetString("output"); ok {
		p.Output = v
	}
	return nil
}

func registerConfigOptionsDefinition2() {
	configbind.RegisterSubCommand[ConfigOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.ConfigOptions",
		Name:     "config",
		Help:     "render or explain the configuration",
		Defaults: map[string]string{
			"action": "show",
		},
		FlagMetas: []cliparser.FieldMeta{},
		Positionals: []configbind.Positional{
			{ConfigKey: "action", Name: "action", Role: configbind.PositionalOptional, Help: "scaffold, env, or show"},
		},
		Apply: applyConfigOptionsDefinition2,
	})
}

func applyConfigOptionsDefinition2(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*ConfigOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply ConfigOptions: bad destination")
	}
	if v, ok := o.GetString("action"); ok {
		p.Action = v
	} else {
		p.Action = "show"
	}
	return nil
}

func registerGenerateOptionsDefinition3() {
	configbind.RegisterSubCommand[GenerateOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.GenerateOptions",
		Name:      "generate",
		Help:      "emit the code the configuration settles",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyGenerateOptionsDefinition3,
	})
}

func applyGenerateOptionsDefinition3(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*GenerateOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply GenerateOptions: bad destination")
	}
	return nil
}

func registerAnalyzeOptionsDefinition4() {
	configbind.RegisterSubCommand[AnalyzeOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.AnalyzeOptions",
		Name:     "analyze",
		Help:     "aggregate a recorded episode corpus",
		FlagMetas: []cliparser.FieldMeta{
			{Key: "corpus", Env: "-", Help: "corpus root; defaults to the behavior.corpus setting"},
			{Key: "sql", Env: "-", Help: "also write a DuckDB report script to this path"},
		},
		Apply: applyAnalyzeOptionsDefinition4,
	})
}

func applyAnalyzeOptionsDefinition4(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*AnalyzeOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply AnalyzeOptions: bad destination")
	}
	if v, ok := o.GetString("corpus"); ok {
		p.Corpus = v
	}
	if v, ok := o.GetString("sql"); ok {
		p.SQL = v
	}
	return nil
}

func registerMergeOptionsDefinition5() {
	configbind.RegisterSubCommand[MergeOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.MergeOptions",
		Name:     "merge",
		Help:     "fold analyzer proposals into a chip library",
		FlagMetas: []cliparser.FieldMeta{
			{Key: "library", Env: "-", Help: "chip library; defaults to the behavior.library setting"},
			{Key: "diff", Env: "-", Help: "write the reviewable diff JSON to this path"},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "request", Name: "request", Role: configbind.PositionalRequired, Help: "analysis-request.json the proposals answer"},
			{ConfigKey: "proposals", Name: "proposals", Role: configbind.PositionalRequired, Help: "proposals JSON from the analyzer"},
		},
		Apply: applyMergeOptionsDefinition5,
	})
}

func applyMergeOptionsDefinition5(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*MergeOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply MergeOptions: bad destination")
	}
	if v, ok := o.GetString("request"); ok {
		p.Request = v
	}
	if v, ok := o.GetString("proposals"); ok {
		p.Proposals = v
	}
	if v, ok := o.GetString("library"); ok {
		p.Library = v
	}
	if v, ok := o.GetString("diff"); ok {
		p.Diff = v
	}
	return nil
}

func registerDoctorOptionsDefinition6() {
	configbind.RegisterSubCommand[DoctorOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.DoctorOptions",
		Name:      "doctor",
		Help:      "report environment problems",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyDoctorOptionsDefinition6,
	})
}

func applyDoctorOptionsDefinition6(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*DoctorOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply DoctorOptions: bad destination")
	}
	return nil
}

func registerVersionOptionsDefinition7() {
	configbind.RegisterSubCommand[VersionOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.VersionOptions",
		Name:      "version",
		Help:      "print the toolchain version",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyVersionOptionsDefinition7,
	})
}

func applyVersionOptionsDefinition7(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*VersionOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply VersionOptions: bad destination")
	}
	return nil
}

func registerDevOptionsDefinition8() {
	configbind.RegisterSubCommand[DevOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.DevOptions",
		Name:      "dev",
		Help:      "build, run, and restart on change, with the dev console",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyDevOptionsDefinition8,
	})
}

func applyDevOptionsDefinition8(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*DevOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply DevOptions: bad destination")
	}
	return nil
}

func registerRunOptionsDefinition9() {
	configbind.RegisterSubCommand[RunOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.RunOptions",
		Name:      "run",
		Help:      "start a built target",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyRunOptionsDefinition9,
	})
}

func applyRunOptionsDefinition9(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*RunOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply RunOptions: bad destination")
	}
	return nil
}

func registerSimulateOptionsDefinition10() {
	configbind.RegisterSubCommand[SimulateOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.SimulateOptions",
		Name:      "simulate",
		Help:      "run headless simulation workloads",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applySimulateOptionsDefinition10,
	})
}

func applySimulateOptionsDefinition10(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*SimulateOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply SimulateOptions: bad destination")
	}
	return nil
}

func registerReplayOptionsDefinition11() {
	configbind.RegisterSubCommand[ReplayOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.ReplayOptions",
		Name:      "replay",
		Help:      "play back a recorded episode",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyReplayOptionsDefinition11,
	})
}

func applyReplayOptionsDefinition11(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*ReplayOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply ReplayOptions: bad destination")
	}
	return nil
}

func registerEditOptionsDefinition12() {
	configbind.RegisterSubCommand[EditOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.EditOptions",
		Name:      "edit",
		Help:      "open the behavior authoring tabs",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyEditOptionsDefinition12,
	})
}

func applyEditOptionsDefinition12(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*EditOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply EditOptions: bad destination")
	}
	return nil
}
