// Code generated by configbind/codegen; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:e391e47eec3e58914c6db5fe1e4c8d0a58bf62e2da1c40ada600f24b9e4b22d1 self=sha256:104aaef9226187c981a5abd2cf07d434908ab36c5e1fb14f94e7d537b4000aef outputs=tinybind_gen.go,configbind_gen.go

package cli

import (
	"fmt"
	"strconv"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerInitOptionsDefinition0()
	registerBuildOptionsDefinition1()
	registerConfigOptionsDefinition2()
	registerGenerateOptionsDefinition3()
	registerAnalyzeOptionsDefinition4()
	registerAddOptionsDefinition5()
	registerDistillOptionsDefinition6()
	registerMergeOptionsDefinition7()
	registerDoctorOptionsDefinition8()
	registerVersionOptionsDefinition9()
	registerDevOptionsDefinition10()
	registerRunOptionsDefinition11()
	registerSimulateOptionsDefinition12()
	registerReplayOptionsDefinition13()
	registerEditOptionsDefinition14()
}

func registerInitOptionsDefinition0() {
	configbind.RegisterSubCommand[InitOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.InitOptions",
		Name:     "init",
		Help:     "scaffold a new project",
		Defaults: map[string]string{
			"seats":     "0",
			"yes":       "false",
			"skip_tidy": "false",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Key: "module", Env: "-", Help: "go module path"},
			{Key: "name", Env: "-", Help: "game name; defaults to the directory name"},
			{Key: "style", Env: "-", Help: "play style: solo, duo, or multi"},
			{Key: "agent", Env: "-", Help: "agentic environment: claude or other; decides where the analysis skill is written"},
			{Key: "seats", Env: "-", Help: "maximum players, for the multi style; 0 asks"},
			{Key: "shared_screen", Env: "-", Help: "do all players read the same screen content: yes or no; empty asks"},
			{Key: "sync", Env: "-", Help: "synchronization mode; a shared surface has none"},
			{Key: "yes", Env: "-", Help: "take the default for every unanswered question instead of prompting", Kind: cliparser.KindBool},
			{Key: "framework_path", Env: "-", Help: "path to a local framework checkout, added as a replace directive"},
			{Key: "skip_tidy", Env: "-", Help: "do not run go mod tidy or the verification build", Kind: cliparser.KindBool},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "dir", Name: "dir", Role: configbind.PositionalOptional, Help: "project directory, created if missing (default: the current directory)"},
		},
		Apply: applyInitOptionsDefinition0,
	})
}

func applyInitOptionsDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*InitOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply InitOptions: bad destination")
	}
	if v, ok := o.GetString("dir"); ok {
		p.Dir = v
	}
	if v, ok := o.GetString("module"); ok {
		p.Module = v
	}
	if v, ok := o.GetString("name"); ok {
		p.Name = v
	}
	if v, ok := o.GetString("style"); ok {
		p.Style = v
	}
	if v, ok := o.GetString("agent"); ok {
		p.Agent = v
	}
	if v, ok := o.GetString("seats"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: seats: %w", err)
		}
		p.Seats = int(n)
	} else {
		p.Seats = 0
	}
	if v, ok := o.GetString("shared_screen"); ok {
		p.SharedScreen = v
	}
	if v, ok := o.GetString("sync"); ok {
		p.Sync = v
	}
	if v, ok := o.GetString("yes"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: yes: %w", err)
		}
		p.Yes = bb
	} else {
		p.Yes = false
	}
	if v, ok := o.GetString("framework_path"); ok {
		p.FrameworkPath = v
	}
	if v, ok := o.GetString("skip_tidy"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: skip_tidy: %w", err)
		}
		p.SkipTidy = bb
	} else {
		p.SkipTidy = false
	}
	return nil
}

func registerBuildOptionsDefinition1() {
	configbind.RegisterSubCommand[BuildOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.BuildOptions",
		Name:     "build",
		Help:     "compile a declared build target",
		FlagMetas: []cliparser.FieldMeta{
			{Key: "output", Env: "-", Help: "output path; defaults to ./bin/<target>"},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "target", Name: "target", Role: configbind.PositionalOptional, Help: "target name from ebigent.toml; defaults to the dev target"},
		},
		Apply: applyBuildOptionsDefinition1,
	})
}

func applyBuildOptionsDefinition1(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*BuildOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply BuildOptions: bad destination")
	}
	if v, ok := o.GetString("target"); ok {
		p.Target = v
	}
	if v, ok := o.GetString("output"); ok {
		p.Output = v
	}
	return nil
}

func registerConfigOptionsDefinition2() {
	configbind.RegisterSubCommand[ConfigOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.ConfigOptions",
		Name:     "config",
		Help:     "render or explain the configuration",
		Defaults: map[string]string{
			"action": "show",
		},
		FlagMetas: []cliparser.FieldMeta{},
		Positionals: []configbind.Positional{
			{ConfigKey: "action", Name: "action", Role: configbind.PositionalOptional, Help: "scaffold, env, or show"},
		},
		Apply: applyConfigOptionsDefinition2,
	})
}

func applyConfigOptionsDefinition2(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*ConfigOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply ConfigOptions: bad destination")
	}
	if v, ok := o.GetString("action"); ok {
		p.Action = v
	} else {
		p.Action = "show"
	}
	return nil
}

func registerGenerateOptionsDefinition3() {
	configbind.RegisterSubCommand[GenerateOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.GenerateOptions",
		Name:      "generate",
		Help:      "emit the code the configuration settles",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyGenerateOptionsDefinition3,
	})
}

func applyGenerateOptionsDefinition3(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*GenerateOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply GenerateOptions: bad destination")
	}
	return nil
}

func registerAnalyzeOptionsDefinition4() {
	configbind.RegisterSubCommand[AnalyzeOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.AnalyzeOptions",
		Name:     "analyze",
		Help:     "aggregate a recorded episode corpus",
		FlagMetas: []cliparser.FieldMeta{
			{Key: "corpus", Env: "-", Help: "corpus root; defaults to the behavior.corpus setting"},
			{Key: "sql", Env: "-", Help: "also write a DuckDB report script to this path"},
		},
		Apply: applyAnalyzeOptionsDefinition4,
	})
}

func applyAnalyzeOptionsDefinition4(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*AnalyzeOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply AnalyzeOptions: bad destination")
	}
	if v, ok := o.GetString("corpus"); ok {
		p.Corpus = v
	}
	if v, ok := o.GetString("sql"); ok {
		p.SQL = v
	}
	return nil
}

func registerAddOptionsDefinition5() {
	configbind.RegisterSubCommand[AddOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.AddOptions",
		Name:     "add",
		Help:     "write a stage's rule set, or an agent for one",
		Defaults: map[string]string{
			"seats": "0",
			"yes":   "false",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Key: "package", Env: "-", Help: "agent: directory of the rule set to write against. stage: directory the new package goes in"},
			{Key: "type", Env: "-", Help: "agent: Go type name; defaults to the name in upper camel case"},
			{Key: "file", Env: "-", Help: "agent: file name; defaults to agent_<name>.go"},
			{Key: "seats", Env: "-", Help: "stage: declared seats; defaults to protocol.seats.count"},
			{Key: "realtime", Env: "-", Help: "stage: does the world move on its own every step: yes or no; empty follows protocol.realtime"},
			{Key: "yes", Env: "-", Help: "take the default for every question instead of prompting", Kind: cliparser.KindBool},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "kind", Name: "kind", Role: configbind.PositionalRequired, Help: "what to add: stage writes a rule set, agent writes a controller for one"},
			{ConfigKey: "name", Name: "name", Role: configbind.PositionalOptional, Help: "agent: the policy name, which is the id the factory returns. stage: the name of the rules"},
		},
		Apply: applyAddOptionsDefinition5,
	})
}

func applyAddOptionsDefinition5(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*AddOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply AddOptions: bad destination")
	}
	if v, ok := o.GetString("kind"); ok {
		p.Kind = v
	}
	if v, ok := o.GetString("name"); ok {
		p.Name = v
	}
	if v, ok := o.GetString("package"); ok {
		p.Package = v
	}
	if v, ok := o.GetString("type"); ok {
		p.Type = v
	}
	if v, ok := o.GetString("file"); ok {
		p.File = v
	}
	if v, ok := o.GetString("seats"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: seats: %w", err)
		}
		p.Seats = int(n)
	} else {
		p.Seats = 0
	}
	if v, ok := o.GetString("realtime"); ok {
		p.Realtime = v
	}
	if v, ok := o.GetString("yes"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: yes: %w", err)
		}
		p.Yes = bb
	} else {
		p.Yes = false
	}
	return nil
}

func registerDistillOptionsDefinition6() {
	configbind.RegisterSubCommand[DistillOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.DistillOptions",
		Name:     "distill",
		Help:     "mine the corpus into behavior candidates and regenerate the agent",
		FlagMetas: []cliparser.FieldMeta{
			{Key: "entry", Env: "-", Help: "package to run; defaults to the behavior.distill setting"},
			{Key: "corpus", Env: "-", Help: "corpus root passed to the entry; defaults to the behavior.corpus setting"},
			{Key: "library", Env: "-", Help: "chip library passed to the entry; defaults to the behavior.library setting"},
		},
		Apply: applyDistillOptionsDefinition6,
	})
}

func applyDistillOptionsDefinition6(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*DistillOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply DistillOptions: bad destination")
	}
	if v, ok := o.GetString("entry"); ok {
		p.Entry = v
	}
	if v, ok := o.GetString("corpus"); ok {
		p.Corpus = v
	}
	if v, ok := o.GetString("library"); ok {
		p.Library = v
	}
	return nil
}

func registerMergeOptionsDefinition7() {
	configbind.RegisterSubCommand[MergeOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.MergeOptions",
		Name:     "merge",
		Help:     "fold analyzer proposals into a chip library",
		FlagMetas: []cliparser.FieldMeta{
			{Key: "library", Env: "-", Help: "chip library; defaults to the behavior.library setting"},
			{Key: "diff", Env: "-", Help: "write the reviewable diff JSON to this path"},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "request", Name: "request", Role: configbind.PositionalRequired, Help: "analysis-request.json the proposals answer"},
			{ConfigKey: "proposals", Name: "proposals", Role: configbind.PositionalRequired, Help: "proposals JSON from the analyzer"},
		},
		Apply: applyMergeOptionsDefinition7,
	})
}

func applyMergeOptionsDefinition7(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*MergeOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply MergeOptions: bad destination")
	}
	if v, ok := o.GetString("request"); ok {
		p.Request = v
	}
	if v, ok := o.GetString("proposals"); ok {
		p.Proposals = v
	}
	if v, ok := o.GetString("library"); ok {
		p.Library = v
	}
	if v, ok := o.GetString("diff"); ok {
		p.Diff = v
	}
	return nil
}

func registerDoctorOptionsDefinition8() {
	configbind.RegisterSubCommand[DoctorOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.DoctorOptions",
		Name:      "doctor",
		Help:      "report environment problems",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyDoctorOptionsDefinition8,
	})
}

func applyDoctorOptionsDefinition8(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*DoctorOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply DoctorOptions: bad destination")
	}
	return nil
}

func registerVersionOptionsDefinition9() {
	configbind.RegisterSubCommand[VersionOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.VersionOptions",
		Name:      "version",
		Help:      "print the toolchain version",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyVersionOptionsDefinition9,
	})
}

func applyVersionOptionsDefinition9(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*VersionOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply VersionOptions: bad destination")
	}
	return nil
}

func registerDevOptionsDefinition10() {
	configbind.RegisterSubCommand[DevOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.DevOptions",
		Name:      "dev",
		Help:      "build, run, and restart on change, with the dev console",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyDevOptionsDefinition10,
	})
}

func applyDevOptionsDefinition10(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*DevOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply DevOptions: bad destination")
	}
	return nil
}

func registerRunOptionsDefinition11() {
	configbind.RegisterSubCommand[RunOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.RunOptions",
		Name:      "run",
		Help:      "start a built target",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyRunOptionsDefinition11,
	})
}

func applyRunOptionsDefinition11(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*RunOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply RunOptions: bad destination")
	}
	return nil
}

func registerSimulateOptionsDefinition12() {
	configbind.RegisterSubCommand[SimulateOptions](configbind.SubCommandDefinition{
		TypeName: "github.com/shibukawa/ebigentserver/cli.SimulateOptions",
		Name:     "simulate",
		Help:     "play matches headless and record them into the corpus",
		Defaults: map[string]string{
			"matches": "0",
			"seed":    "0",
			"build":   "true",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Key: "matches", Env: "-", Help: "matches to play; 0 uses run.episode.matches"},
			{Key: "seed", Env: "-", Help: "seed of the first match; 0 uses run.episode.seed"},
			{Key: "corpus", Env: "-", Help: "corpus root; defaults to the behavior.corpus setting"},
			{Key: "agents", Env: "-", Help: "named controller per seat: a name for every bot seat, or slot=name pairs; empty uses run.episode.agents"},
			{Key: "build", Env: "-", Help: "compile before running; --build=false runs the binary already in bin/", Kind: cliparser.KindBool},
		},
		Positionals: []configbind.Positional{
			{ConfigKey: "target", Name: "target", Role: configbind.PositionalOptional, Help: "target name from ebigent.toml; defaults to the only simulation target"},
		},
		Apply: applySimulateOptionsDefinition12,
	})
}

func applySimulateOptionsDefinition12(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*SimulateOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply SimulateOptions: bad destination")
	}
	if v, ok := o.GetString("target"); ok {
		p.Target = v
	}
	if v, ok := o.GetString("matches"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: matches: %w", err)
		}
		p.Matches = int(n)
	} else {
		p.Matches = 0
	}
	if v, ok := o.GetString("seed"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: seed: %w", err)
		}
		p.Seed = int(n)
	} else {
		p.Seed = 0
	}
	if v, ok := o.GetString("corpus"); ok {
		p.Corpus = v
	}
	if v, ok := o.GetString("agents"); ok {
		p.Agents = v
	}
	if v, ok := o.GetString("build"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: build: %w", err)
		}
		p.Build = bb
	} else {
		p.Build = true
	}
	return nil
}

func registerReplayOptionsDefinition13() {
	configbind.RegisterSubCommand[ReplayOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.ReplayOptions",
		Name:      "replay",
		Help:      "play back a recorded episode",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyReplayOptionsDefinition13,
	})
}

func applyReplayOptionsDefinition13(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*ReplayOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply ReplayOptions: bad destination")
	}
	return nil
}

func registerEditOptionsDefinition14() {
	configbind.RegisterSubCommand[EditOptions](configbind.SubCommandDefinition{
		TypeName:  "github.com/shibukawa/ebigentserver/cli.EditOptions",
		Name:      "edit",
		Help:      "open the behavior authoring tabs",
		FlagMetas: []cliparser.FieldMeta{},
		Apply:     applyEditOptionsDefinition14,
	})
}

func applyEditOptionsDefinition14(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*EditOptions)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply EditOptions: bad destination")
	}
	return nil
}
