// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:42f0bdb0034f7a981f6e5a5cef5a4ac364c728541481d70d57a0d3a000502c7f self=sha256:0b51ca92031947b17b77a1e61ad83d418d51522396ac7308933a64ee2ad12bb1 outputs=tinybind_gen.go,configbind_gen.go

package cli
