// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:78858b2fecf7c0acbd9d75bbf661451567d39c53c03e146ca10ecaee157431df self=sha256:0b51ca92031947b17b77a1e61ad83d418d51522396ac7308933a64ee2ad12bb1 outputs=tinybind_gen.go,configbind_gen.go

package cli
