// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:0234d265dc958cf217ff56266545c63c7e6b6ca5abc271686e14f35eade9e423 self=sha256:0b51ca92031947b17b77a1e61ad83d418d51522396ac7308933a64ee2ad12bb1 outputs=tinybind_gen.go,configbind_gen.go

package cli
