package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

// Emit writes the delta half of concept:state-synchronization for every
// struct given: the type carrying what changed, the diff that fills it,
// the patch that puts it back, and the encoding that carries only the
// fields it names.
//
// The presence mask is one uint64 and the bit order is field declaration
// order, so moving a field moves the wire. Nothing here is optional:
// rule:delta-baseline-must-be-retained means a receiver that cannot place
// a delta asks for a snapshot instead, and a delta that silently omitted
// a field would leave it wrong forever rather than ask.
func Emit(pkg string, structs []Struct) ([]byte, error) {
	var buf bytes.Buffer
	if err := deltaTemplate.Execute(&buf, deltaFile{Package: pkg, Structs: structs}); err != nil {
		return nil, fmt.Errorf("codegen: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: emitted invalid Go: %w\n%s", err, buf.String())
	}
	return src, nil
}

// deltaFile is what the template renders.
type deltaFile struct {
	Package string
	Structs []Struct
}

// Bit is the presence bit of a field, which is its declaration index.
func (f Field) Bit(i int) int { return i }

// Compare is the expression that decides whether a field changed. A slice
// needs its contents compared rather than its header, and a byte slice
// converts to string to do it without a loop.
func (f Field) Compare(base, cur string) string {
	switch f.Kind {
	case KindBytes:
		return fmt.Sprintf("string(%s.%s) != string(%s.%s)", base, f.Name, cur, f.Name)
	case KindStructSlice:
		return fmt.Sprintf("!equal%s(%s.%s, %s.%s)", f.Elem, base, f.Name, cur, f.Name)
	default:
		return fmt.Sprintf("%s.%s != %s.%s", base, f.Name, cur, f.Name)
	}
}

// Append is the encoder call for one field's value.
func (f Field) Append(v string) string {
	switch f.Kind {
	case KindUint:
		return fmt.Sprintf("dst = cbor.AppendUint(dst, uint64(%s.%s))", v, f.Name)
	case KindInt:
		return fmt.Sprintf("dst = cbor.AppendInt(dst, int64(%s.%s))", v, f.Name)
	case KindBool:
		return fmt.Sprintf("dst = cbor.AppendBool(dst, bool(%s.%s))", v, f.Name)
	case KindBytes:
		return fmt.Sprintf("dst = cbor.AppendBytes(dst, []byte(%s.%s))", v, f.Name)
	case KindStructSlice:
		return fmt.Sprintf("dst = append%sSlice(dst, %s.%s)", f.Elem, v, f.Name)
	}
	return ""
}

// StructSliceElems reports the distinct element types that need a slice
// helper, so each is emitted once however many fields carry it.
func (d deltaFile) StructSliceElems() []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range d.Structs {
		for _, f := range s.Fields {
			if f.Kind == KindStructSlice && !seen[f.Elem] {
				seen[f.Elem] = true
				out = append(out, f.Elem)
			}
		}
	}
	return out
}

func lower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

var deltaTemplate = template.Must(template.New("delta").Funcs(template.FuncMap{
	"lower": lower,
}).Parse(`// Code generated by ebigent generate; DO NOT EDIT.
//
// The delta half of concept:state-synchronization. tinybind-go generates
// the codecs for the world and wire types themselves; since v0.5.21 it
// generates no diff, patch, or delta encoding, so those are the
// framework's (decision:framework-side-delta-generation) and they are
// here.

package {{.Package}}

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// DecodeLimits bounds what a decoder in this file will read. They are
// resource limits rather than format rules, so they belong to the
// deployment and not to the protocol: two peers must agree on the shape
// of a message and need agree on nothing about how large one this process
// is willing to read (data:runtime-resource-budget). Startup may lower
// them; the values here suit a snapshot.
var DecodeLimits = cbor.DecoderOptions{
	MaxContainerItems:  1 << 16,
	MaxStringBytes:     4 << 20,
	MaxInputBytes:      64 << 20,
	MaxRawMessageBytes: 64 << 20,
	RejectFloats:       true,
}

{{range .StructSliceElems}}
// equal{{.}} compares two slices element by element. A delta asks whether
// a field changed, and for a slice that is a question about contents.
func equal{{.}}(a, b []{{.}}) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// append{{.}}Slice writes the slice as one CBOR array, each element
// through its own generated codec.
func append{{.}}Slice(dst []byte, v []{{.}}) []byte {
	dst = cbor.AppendArrayHeader(dst, len(v))
	for i := range v {
		dst = v[i].AppendCBORTo(dst)
	}
	return dst
}

// read{{.}}Slice reads one CBOR array of elements into out, reusing its
// capacity so a steady state allocates nothing.
func read{{.}}Slice(r *cbor.Reader, out []{{.}}) ([]{{.}}, error) {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, &cbor.Error{Offset: int64(r.Offset()), Path: "{{.}}", Err: cbor.ErrUnexpectedToken}
	}
	out = out[:0]
	for range n {
		var e {{.}}
		raw, err := r.ReadRaw()
		if err != nil {
			return out, err
		}
		if err := e.DecodeCBORFrom(raw); err != nil {
			return out, err
		}
		out = append(out, e)
	}
	return out, nil
}
{{end}}
{{range $s := .Structs}}
// {{$s.Name}}Delta is what changed between two {{$s.Name}} values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful. The bit
// order is declaration order, so moving a field moves the wire.
type {{$s.Name}}Delta struct {
	Present uint64
{{range $i, $f := $s.Fields}}	// bit {{$i}}
	{{$f.Name}} {{$f.Type}}
{{end}}}

// Diff{{$s.Name}}Into fills d with what changed between baseline and
// current, and reports whether anything did.
func Diff{{$s.Name}}Into(d *{{$s.Name}}Delta, baseline, current {{$s.Name}}) bool {
	d.Present = 0
{{range $i, $f := $s.Fields}}	if {{$f.Compare "baseline" "current"}} {
		d.Present |= 1 << {{$i}}
		d.{{$f.Name}} = current.{{$f.Name}}
	}
{{end}}	return d.Present != 0
}

// Diff{{$s.Name}} returns what changed between baseline and current.
func Diff{{$s.Name}}(baseline, current {{$s.Name}}) {{$s.Name}}Delta {
	var d {{$s.Name}}Delta
	Diff{{$s.Name}}Into(&d, baseline, current)
	return d
}

// Apply{{$s.Name}}Delta puts d back onto v. A bit Present does not name
// leaves that field as it stands, which is what makes a delta a delta.
func Apply{{$s.Name}}Delta(v *{{$s.Name}}, d {{$s.Name}}Delta) error {
{{range $i, $f := $s.Fields}}	if d.Present&(1<<{{$i}}) != 0 {
		v.{{$f.Name}} = d.{{$f.Name}}
	}
{{end}}	return nil
}

// AppendCBORTo appends d as one CBOR array: the mask, then the values it
// names, in bit order. A field the mask omits costs nothing.
func (v {{$s.Name}}Delta) AppendCBORTo(dst []byte) []byte {
	n := 1
	for bit := range {{len $s.Fields}} {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
{{range $i, $f := $s.Fields}}	if v.Present&(1<<{{$i}}) != 0 {
		{{$f.Append "v"}}
	}
{{end}}	return dst
}

// DecodeCBORFrom reads one delta into v, and refuses anything after it:
// a trailing item means the sender and the receiver disagree about the
// shape, which concept:cbor-wire-profile cannot detect any other way.
func (v *{{$s.Name}}Delta) DecodeCBORFrom(data []byte) error {
	r, err := cbor.NewReader(data, DecodeLimits)
	if err != nil {
		return err
	}
	if err := v.decodeFrom(r); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// decodeFrom reads one delta off r.
func (v *{{$s.Name}}Delta) decodeFrom(r *cbor.Reader) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "{{$s.Name}}Delta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
{{range $i, $f := $s.Fields}}	if present&(1<<{{$i}}) != 0 {
		{{if eq $f.Kind 0}}x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.{{$f.Name}} = {{$f.Type}}(x){{else if eq $f.Kind 1}}x, err := r.ReadInt64()
		if err != nil {
			return err
		}
		v.{{$f.Name}} = {{$f.Type}}(x){{else if eq $f.Kind 2}}x, err := r.ReadBool()
		if err != nil {
			return err
		}
		v.{{$f.Name}} = {{$f.Type}}(x){{else if eq $f.Kind 3}}x, err := r.ReadBytes()
		if err != nil {
			return err
		}
		// ReadBytes borrows from the input, so the value is copied into
		// whatever capacity the field already holds: it must outlive the
		// buffer it was read from, and reusing the capacity keeps the
		// steady state allocation-free.
		v.{{$f.Name}} = append(v.{{$f.Name}}[:0], x...){{else}}xs, err := read{{$f.Elem}}Slice(r, v.{{$f.Name}})
		if err != nil {
			return err
		}
		v.{{$f.Name}} = xs{{end}}
		read++
	}
{{end}}	if read != n {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "{{$s.Name}}Delta", Err: cbor.ErrUnexpectedToken}
	}
	return nil
}
{{end}}`))
