package codegen

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"strconv"
)

// Version is the schema fingerprint of a set of wire types — the half of
// data:game-version that moves when the bytes move.
//
// It covers wire-observable shape and nothing else: type names, field
// names, field order, and how each field is carried. Regenerating with a
// newer toolchain that emits the same bytes leaves it alone, and any
// change that moves one byte moves it.
//
// It is not a version in the ordinary sense. Nobody bumps it, there is no
// ordering and no range, and the only question ever asked of it is
// whether two of them are equal (rule:game-version-must-match). The old
// toolchain derived one; v0.5.23 derives none, so this does
// (requirement:cborbind-migration).
func Version(structs []Struct) string {
	h := sha256.New()
	for _, s := range structs {
		// Lengths go in with the names so that two different splits of
		// the same characters cannot hash alike.
		writeToken(h, s.Name)
		writeToken(h, strconv.Itoa(len(s.Fields)))
		for _, f := range s.Fields {
			writeToken(h, f.Name)
			writeToken(h, f.Type)
			writeToken(h, strconv.Itoa(int(f.Kind)))
			writeToken(h, f.Elem)
		}
	}
	sum := h.Sum(nil)
	// Eight bytes is what the handshake carries and what a packet capture
	// stays readable at; a collision needs two schemas, not two builds.
	return hex.EncodeToString(sum[:8])
}

// writeToken feeds one length-prefixed token, so "ab"+"c" and "a"+"bc"
// cannot produce the same digest.
func writeToken(h interface{ Write([]byte) (int, error) }, s string) {
	var n [4]byte
	binary.BigEndian.PutUint32(n[:], uint32(len(s)))
	_, _ = h.Write(n[:])
	_, _ = h.Write([]byte(s))
}

// EmitVersion writes the fingerprint as a Go constant beside the delta
// code, so the handshake reads a constant rather than computing a hash at
// startup.
func EmitVersion(pkg string, structs []Struct) []byte {
	return fmt.Appendf(nil, `// Code generated by ebigent generate; DO NOT EDIT.

package %s

// SchemaVersion is the wire fingerprint of every type in this package —
// the half of data:game-version that moves when the bytes move.
//
// It is derived from the shapes below and covers wire-observable shape
// alone, so regenerating with a newer toolchain that emits the same bytes
// leaves it unchanged. It is compared for equality and nothing else: there
// is no ordering here and no partial compatibility to negotiate, because
// concept:cbor-wire-profile puts no field names on the wire for a
// mismatch to be noticed in (rule:game-version-must-match).
const SchemaVersion = %q
`, pkg, Version(structs))
}
