package codegen_test

import (
	"strings"
	"testing"

	"github.com/shibukawa/ebigentserver/codegen"
)

// shapes is a fixture standing in for what Read resolves, so the
// fingerprint can be exercised on one field at a time.
func shapes() []codegen.Struct {
	return []codegen.Struct{{
		Name: "World",
		Fields: []codegen.Field{
			{Name: "Tick", Type: "uint64", Kind: codegen.KindUint},
			{Name: "Cells", Type: "[]uint8", Kind: codegen.KindBytes},
			{Name: "Motes", Type: "[]Mote", Kind: codegen.KindStructSlice, Elem: "Mote"},
		},
	}}
}

// TestVersionMovesWithTheBytes covers what the fingerprint is for: any
// change that moves one byte on the wire has to move it, and nothing else
// may.
func TestVersionMovesWithTheBytes(t *testing.T) {
	base := codegen.Version(shapes())
	if len(base) != 16 {
		t.Fatalf("fingerprint %q is %d hex characters, want 16", base, len(base))
	}

	moves := map[string]func([]codegen.Struct){
		"a renamed type":  func(s []codegen.Struct) { s[0].Name = "Realm" },
		"a renamed field": func(s []codegen.Struct) { s[0].Fields[0].Name = "Step" },
		"a retyped field": func(s []codegen.Struct) {
			s[0].Fields[0].Type, s[0].Fields[0].Kind = "int64", codegen.KindInt
		},
		"a reordered field": func(s []codegen.Struct) {
			s[0].Fields[0], s[0].Fields[1] = s[0].Fields[1], s[0].Fields[0]
		},
		"a field added": func(s []codegen.Struct) {
			s[0].Fields = append(s[0].Fields, codegen.Field{Name: "Over", Type: "bool", Kind: codegen.KindBool})
		},
		"a field removed":         func(s []codegen.Struct) { s[0].Fields = s[0].Fields[:2] },
		"a changed slice element": func(s []codegen.Struct) { s[0].Fields[2].Elem = "Speck" },
	}
	for name, mut := range moves {
		t.Run(name, func(t *testing.T) {
			s := shapes()
			mut(s)
			if got := codegen.Version(s); got == base {
				t.Errorf("%s left the fingerprint at %s", name, got)
			}
		})
	}
}

// TestVersionIsStable keeps the fingerprint from drifting on its own: the
// same shapes have to hash alike across runs, or every rebuild would look
// like an incompatible one.
func TestVersionIsStable(t *testing.T) {
	if a, b := codegen.Version(shapes()), codegen.Version(shapes()); a != b {
		t.Fatalf("two runs gave %s and %s", a, b)
	}
}

// TestVersionSeparatesTokens covers the length prefixing: two shapes whose
// names concatenate the same way must not collide.
func TestVersionSeparatesTokens(t *testing.T) {
	a := []codegen.Struct{{Name: "AB", Fields: []codegen.Field{{Name: "C", Type: "uint8"}}}}
	b := []codegen.Struct{{Name: "A", Fields: []codegen.Field{{Name: "BC", Type: "uint8"}}}}
	if codegen.Version(a) == codegen.Version(b) {
		t.Fatal("two different schemas share a fingerprint")
	}
}

func TestEmitVersionCompilesToAConstant(t *testing.T) {
	src := string(codegen.EmitVersion("msg", shapes()))
	want := `const SchemaVersion = "` + codegen.Version(shapes()) + `"`
	if !strings.Contains(src, want) {
		t.Errorf("emitted source lacks %s:\n%s", want, src)
	}
	if !strings.HasPrefix(src, "// Code generated by ebigent generate; DO NOT EDIT.") {
		t.Error("the emitted file does not mark itself generated")
	}
}
