// Code generated by configbind/codegen; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:80d43fd12762c112bde266ee5f352d32f9284bf4b7b726ea5c11f0605e4b0133 self=sha256:162f2f05f14d0725239af6dbd772fb63d4bd2468a1872398f2691e65a75759b7 outputs=tinybind_gen.go,configbind_gen.go

package runconf

import (
	"fmt"
	"strconv"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerRunDefinition0()
}

func registerRunDefinition0() {
	configbind.Register[Run](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/runconf.Run",
		Prefix:   "run",
		Doc:      "Run is the [run] table. Field order is the order provenance reports",
		KnownKeys: []string{
			"run.topology",
			"run.listen",
			"run.server",
			"run.transport.enable",
			"run.time.mode",
			"run.time.scale_permille",
			"run.tuning.tick_rate",
			"run.tuning.send_rate",
			"run.tuning.snapshot_every",
			"run.tuning.history_depth",
			"run.tuning.baseline",
			"run.tuning.speculation_depth",
			"run.tuning.ack",
			"run.debug.listen",
			"run.episode.root",
			"run.episode.mode",
			"run.episode.matches",
			"run.episode.seed",
			"run.episode.agents",
		},
		Defaults: map[string]string{
			"run.topology":                 "standalone",
			"run.time.mode":                "realtime",
			"run.time.scale_permille":      "1000",
			"run.tuning.tick_rate":         "60",
			"run.tuning.send_rate":         "30",
			"run.tuning.snapshot_every":    "120",
			"run.tuning.history_depth":     "12",
			"run.tuning.baseline":          "speculative",
			"run.tuning.speculation_depth": "0",
			"run.tuning.ack":               "piggyback_only",
			"run.debug.listen":             "127.0.0.1:8932",
			"run.episode.mode":             "analysis_sampled",
			"run.episode.matches":          "1",
			"run.episode.seed":             "1",
		},
		DependsOn: map[string][]configbind.Dependency{
			"run.listen":                   {{Key: "run.topology", Op: "=", Values: []string{"listen", "dedicated"}}},
			"run.transport.enable":         {{Key: "run.topology", Op: "!=", Values: []string{"standalone"}}},
			"run.time.scale_permille":      {{Key: "run.time.mode", Op: "=", Values: []string{"scaled"}}},
			"run.tuning.speculation_depth": {{Key: "run.tuning.baseline", Op: "=", Values: []string{"bounded_speculation"}}},
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "run", Key: "topology", Help: "execution topology of this process", Enum: []string{"standalone", "listen", "dedicated", "p2p"}},
			{Prefix: "run", Key: "listen", Help: "realtime listen address as host:port"},
			{Prefix: "run", Key: "server", Help: "address of the host to join, as host:port or a url; empty discovers or hosts"},
			{Prefix: "run", Key: "transport.enable", Help: "listeners this process may open: websocket, webtransport, webrtc", Kind: cliparser.KindArray},
			{Prefix: "run", Key: "time.mode", Help: "session clock policy", Enum: []string{"realtime", "scaled", "step", "unlimited"}},
			{Prefix: "run", Key: "time.scale_permille", Help: "clock rate in thousandths, 1000 being realtime"},
			{Prefix: "run", Key: "tuning.tick_rate", Help: "simulation steps per second"},
			{Prefix: "run", Key: "tuning.send_rate", Help: "state updates per second; tick_rate must be a whole multiple"},
			{Prefix: "run", Key: "tuning.snapshot_every", Help: "full snapshot every N updates; 0 sends one only on join"},
			{Prefix: "run", Key: "tuning.history_depth", Help: "retained world versions per receiver"},
			{Prefix: "run", Key: "tuning.baseline", Help: "which retained version deltas are computed against", Enum: []string{"speculative", "confirmed_only", "bounded_speculation"}},
			{Prefix: "run", Key: "tuning.speculation_depth", Help: "unconfirmed versions bounded_speculation may speculate past the confirmed baseline"},
			{Prefix: "run", Key: "tuning.ack", Help: "how ack records reach the peer", Enum: []string{"piggyback_only", "dedicated", "delayed_piggyback"}},
			{Prefix: "run", Key: "debug.listen", Help: "dev debug endpoint address; empty disables it"},
			{Prefix: "run", Key: "episode.root", Help: "corpus root; empty records nothing"},
			{Prefix: "run", Key: "episode.mode", Help: "how much of each episode is kept", Enum: []string{"analysis_sampled", "replay_complete"}},
			{Prefix: "run", Key: "episode.matches", Help: "matches to play before exiting; 0 plays until interrupted"},
			{Prefix: "run", Key: "episode.seed", Help: "seed of the first match; each later match adds its index"},
			{Prefix: "run", Key: "episode.agents", Help: "named controller per seat: a name for every bot seat, or slot=name pairs separated by commas"},
		},
		Apply: applyRunDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "topology", Kind: configbind.ScaffoldString, Default: "standalone", Help: "execution topology of this process", Enum: []string{"standalone", "listen", "dedicated", "p2p"}},
			{Key: "listen", Kind: configbind.ScaffoldString, Help: "realtime listen address as host:port"},
			{Key: "server", Kind: configbind.ScaffoldString, Help: "address of the host to join, as host:port or a url; empty discovers or hosts"},
			{Key: "transport.enable", Kind: configbind.ScaffoldStringSlice, Help: "listeners this process may open: websocket, webtransport, webrtc"},
			{Key: "time.mode", Kind: configbind.ScaffoldString, Default: "realtime", Help: "session clock policy", Enum: []string{"realtime", "scaled", "step", "unlimited"}},
			{Key: "time.scale_permille", Kind: configbind.ScaffoldInt, Default: "1000", Help: "clock rate in thousandths, 1000 being realtime"},
			{Key: "tuning.tick_rate", Kind: configbind.ScaffoldInt, Default: "60", Help: "simulation steps per second"},
			{Key: "tuning.send_rate", Kind: configbind.ScaffoldInt, Default: "30", Help: "state updates per second; tick_rate must be a whole multiple"},
			{Key: "tuning.snapshot_every", Kind: configbind.ScaffoldInt, Default: "120", Help: "full snapshot every N updates; 0 sends one only on join"},
			{Key: "tuning.history_depth", Kind: configbind.ScaffoldInt, Default: "12", Help: "retained world versions per receiver"},
			{Key: "tuning.baseline", Kind: configbind.ScaffoldString, Default: "speculative", Help: "which retained version deltas are computed against", Enum: []string{"speculative", "confirmed_only", "bounded_speculation"}},
			{Key: "tuning.speculation_depth", Kind: configbind.ScaffoldInt, Default: "0", Help: "unconfirmed versions bounded_speculation may speculate past the confirmed baseline"},
			{Key: "tuning.ack", Kind: configbind.ScaffoldString, Default: "piggyback_only", Help: "how ack records reach the peer", Enum: []string{"piggyback_only", "dedicated", "delayed_piggyback"}},
			{Key: "debug.listen", Kind: configbind.ScaffoldString, Default: "127.0.0.1:8932", Help: "dev debug endpoint address; empty disables it"},
			{Key: "episode.root", Kind: configbind.ScaffoldString, Help: "corpus root; empty records nothing"},
			{Key: "episode.mode", Kind: configbind.ScaffoldString, Default: "analysis_sampled", Help: "how much of each episode is kept", Enum: []string{"analysis_sampled", "replay_complete"}},
			{Key: "episode.matches", Kind: configbind.ScaffoldInt, Default: "1", Help: "matches to play before exiting; 0 plays until interrupted"},
			{Key: "episode.seed", Kind: configbind.ScaffoldInt, Default: "1", Help: "seed of the first match; each later match adds its index"},
			{Key: "episode.agents", Kind: configbind.ScaffoldString, Help: "named controller per seat: a name for every bot seat, or slot=name pairs separated by commas"},
		},
	})
}

func applyRunDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Run)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Run: bad destination")
	}
	if v, ok := o.GetString("run.topology"); ok {
		switch v {
		case "standalone", "listen", "dedicated", "p2p":
		default:
			return fmt.Errorf("configbind: run.topology: %q must be one of: standalone, listen, dedicated, p2p", v)
		}
		p.Topology = v
	} else {
		p.Topology = "standalone"
	}
	if v, ok := o.GetString("run.listen"); ok {
		p.Listen = v
	}
	if v, ok := o.GetString("run.server"); ok {
		p.Server = v
	}
	if v, ok := o.GetMulti("run.transport.enable"); ok {
		p.Transport.Enable = v
	}
	if v, ok := o.GetString("run.time.mode"); ok {
		switch v {
		case "realtime", "scaled", "step", "unlimited":
		default:
			return fmt.Errorf("configbind: run.time.mode: %q must be one of: realtime, scaled, step, unlimited", v)
		}
		p.Time.Mode = v
	} else {
		p.Time.Mode = "realtime"
	}
	if v, ok := o.GetString("run.time.scale_permille"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.time.scale_permille: %w", err)
		}
		p.Time.ScalePermille = int(n)
	} else {
		p.Time.ScalePermille = 1000
	}
	if v, ok := o.GetString("run.tuning.tick_rate"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.tuning.tick_rate: %w", err)
		}
		p.Tuning.TickRate = int(n)
	} else {
		p.Tuning.TickRate = 60
	}
	if v, ok := o.GetString("run.tuning.send_rate"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.tuning.send_rate: %w", err)
		}
		p.Tuning.SendRate = int(n)
	} else {
		p.Tuning.SendRate = 30
	}
	if v, ok := o.GetString("run.tuning.snapshot_every"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.tuning.snapshot_every: %w", err)
		}
		p.Tuning.SnapshotEvery = int(n)
	} else {
		p.Tuning.SnapshotEvery = 120
	}
	if v, ok := o.GetString("run.tuning.history_depth"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.tuning.history_depth: %w", err)
		}
		p.Tuning.HistoryDepth = int(n)
	} else {
		p.Tuning.HistoryDepth = 12
	}
	if v, ok := o.GetString("run.tuning.baseline"); ok {
		switch v {
		case "speculative", "confirmed_only", "bounded_speculation":
		default:
			return fmt.Errorf("configbind: run.tuning.baseline: %q must be one of: speculative, confirmed_only, bounded_speculation", v)
		}
		p.Tuning.Baseline = v
	} else {
		p.Tuning.Baseline = "speculative"
	}
	if v, ok := o.GetString("run.tuning.speculation_depth"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.tuning.speculation_depth: %w", err)
		}
		p.Tuning.SpeculationDepth = int(n)
	} else {
		p.Tuning.SpeculationDepth = 0
	}
	if v, ok := o.GetString("run.tuning.ack"); ok {
		switch v {
		case "piggyback_only", "dedicated", "delayed_piggyback":
		default:
			return fmt.Errorf("configbind: run.tuning.ack: %q must be one of: piggyback_only, dedicated, delayed_piggyback", v)
		}
		p.Tuning.Ack = v
	} else {
		p.Tuning.Ack = "piggyback_only"
	}
	if v, ok := o.GetString("run.debug.listen"); ok {
		p.Debug.Listen = v
	} else {
		p.Debug.Listen = "127.0.0.1:8932"
	}
	if v, ok := o.GetString("run.episode.root"); ok {
		p.Episode.Root = v
	}
	if v, ok := o.GetString("run.episode.mode"); ok {
		switch v {
		case "analysis_sampled", "replay_complete":
		default:
			return fmt.Errorf("configbind: run.episode.mode: %q must be one of: analysis_sampled, replay_complete", v)
		}
		p.Episode.Mode = v
	} else {
		p.Episode.Mode = "analysis_sampled"
	}
	if v, ok := o.GetString("run.episode.matches"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.episode.matches: %w", err)
		}
		p.Episode.Matches = int(n)
	} else {
		p.Episode.Matches = 1
	}
	if v, ok := o.GetString("run.episode.seed"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.episode.seed: %w", err)
		}
		p.Episode.Seed = int(n)
	} else {
		p.Episode.Seed = 1
	}
	if v, ok := o.GetString("run.episode.agents"); ok {
		p.Episode.Agents = v
	}
	return nil
}
