// Code generated by configbind/codegen; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:f8f8430b6b2fb348c60d8808371c41fc8e71fdd8203391b9f5fe647e27d950af self=sha256:3244232723e82f15d0b9017a072d573b64c212684d9f741d4eb0c9c38933ae00 outputs=tinybind_gen.go,configbind_gen.go

package runconf

import (
	"fmt"
	"strconv"

	"github.com/shibukawa/tinybind-go/cliparser"
	"github.com/shibukawa/tinybind-go/configbind"
)

func init() {
	registerRunDefinition0()
}

func registerRunDefinition0() {
	configbind.Register[Run](configbind.Definition{
		TypeName: "github.com/shibukawa/ebigentserver/config/runconf.Run",
		Prefix:   "run",
		Doc:      "Run is the [run] table. Field order is the order provenance reports",
		KnownKeys: []string{
			"run.topology",
			"run.listen",
			"run.transport.enable",
			"run.transport.require_unreliable",
			"run.transport.require_peer_to_peer",
			"run.transport.require_browser",
			"run.sync.mode",
			"run.sync.baseline",
			"run.sync.speculation_depth",
			"run.sync.ack",
			"run.time.mode",
			"run.time.scale_permille",
			"run.slot",
			"run.episode.dir",
			"run.episode.mode",
			"run.episode.sample_percent",
			"run.debug.listen",
			"run.evaluation_version",
		},
		Defaults: map[string]string{
			"run.topology":                       "standalone",
			"run.transport.require_unreliable":   "false",
			"run.transport.require_peer_to_peer": "false",
			"run.transport.require_browser":      "false",
			"run.sync.mode":                      "server_authoritative",
			"run.sync.baseline":                  "speculative",
			"run.sync.speculation_depth":         "0",
			"run.sync.ack":                       "piggyback_only",
			"run.time.mode":                      "realtime",
			"run.time.scale_permille":            "1000",
			"run.episode.mode":                   "analysis_sampled",
			"run.episode.sample_percent":         "100",
			"run.debug.listen":                   "127.0.0.1:8932",
			"run.evaluation_version":             "1",
		},
		DependsOn: map[string][]configbind.Dependency{
			"run.listen":                         {{Key: "run.topology", Op: "=", Values: []string{"listen", "dedicated"}}},
			"run.transport.enable":               {{Key: "run.topology", Op: "!=", Values: []string{"standalone"}}},
			"run.transport.require_unreliable":   {{Key: "run.topology", Op: "!=", Values: []string{"standalone"}}},
			"run.transport.require_peer_to_peer": {{Key: "run.topology", Op: "!=", Values: []string{"standalone"}}},
			"run.transport.require_browser":      {{Key: "run.topology", Op: "!=", Values: []string{"standalone"}}},
			"run.sync.speculation_depth":         {{Key: "run.sync.baseline", Op: "=", Values: []string{"bounded_speculation"}}},
			"run.time.scale_permille":            {{Key: "run.time.mode", Op: "=", Values: []string{"scaled"}}},
			"run.episode.mode":                   {{Key: "run.episode.dir"}},
			"run.episode.sample_percent":         {{Key: "run.episode.dir"}},
		},
		Summary: map[string]string{
			"run.evaluation_version": "omit",
		},
		FlagMetas: []cliparser.FieldMeta{
			{Prefix: "run", Key: "topology", Help: "execution topology of this process"},
			{Prefix: "run", Key: "listen", Help: "realtime listen address as host:port"},
			{Prefix: "run", Key: "transport.enable", Help: "listeners this process may open: websocket, webtransport, webrtc", Kind: cliparser.KindArray},
			{Prefix: "run", Key: "transport.require_unreliable", Help: "require an unreliable datagram channel", Kind: cliparser.KindBool},
			{Prefix: "run", Key: "transport.require_peer_to_peer", Help: "require a peer to peer capable transport", Kind: cliparser.KindBool},
			{Prefix: "run", Key: "transport.require_browser", Help: "require a browser reachable transport", Kind: cliparser.KindBool},
			{Prefix: "run", Key: "sync.mode", Help: "synchronization mode"},
			{Prefix: "run", Key: "sync.baseline", Help: "which retained version deltas are computed against"},
			{Prefix: "run", Key: "sync.speculation_depth", Help: "unconfirmed versions bounded_speculation may speculate past the confirmed baseline"},
			{Prefix: "run", Key: "sync.ack", Help: "how ack records reach the peer"},
			{Prefix: "run", Key: "time.mode", Help: "session clock policy"},
			{Prefix: "run", Key: "time.scale_permille", Help: "clock rate in thousandths, 1000 being realtime"},
			{Prefix: "run", Key: "episode.dir", Help: "episode recording directory; empty disables recording"},
			{Prefix: "run", Key: "episode.mode", Help: "recording contract"},
			{Prefix: "run", Key: "episode.sample_percent", Help: "percent of sessions recorded"},
			{Prefix: "run", Key: "debug.listen", Help: "dev debug endpoint address; empty disables it"},
			{Prefix: "run", Key: "evaluation_version", Help: "evaluation signal version recorded with every episode"},
		},
		Apply: applyRunDefinition0,
		Scaffold: []configbind.ScaffoldField{
			{Key: "topology", Kind: configbind.ScaffoldString, Default: "standalone", Help: "execution topology of this process"},
			{Key: "listen", Kind: configbind.ScaffoldString, Help: "realtime listen address as host:port"},
			{Key: "transport.enable", Kind: configbind.ScaffoldStringSlice, Help: "listeners this process may open: websocket, webtransport, webrtc"},
			{Key: "transport.require_unreliable", Kind: configbind.ScaffoldBool, Default: "false", Help: "require an unreliable datagram channel"},
			{Key: "transport.require_peer_to_peer", Kind: configbind.ScaffoldBool, Default: "false", Help: "require a peer to peer capable transport"},
			{Key: "transport.require_browser", Kind: configbind.ScaffoldBool, Default: "false", Help: "require a browser reachable transport"},
			{Key: "sync.mode", Kind: configbind.ScaffoldString, Default: "server_authoritative", Help: "synchronization mode"},
			{Key: "sync.baseline", Kind: configbind.ScaffoldString, Default: "speculative", Help: "which retained version deltas are computed against"},
			{Key: "sync.speculation_depth", Kind: configbind.ScaffoldInt, Default: "0", Help: "unconfirmed versions bounded_speculation may speculate past the confirmed baseline"},
			{Key: "sync.ack", Kind: configbind.ScaffoldString, Default: "piggyback_only", Help: "how ack records reach the peer"},
			{Key: "time.mode", Kind: configbind.ScaffoldString, Default: "realtime", Help: "session clock policy"},
			{Key: "time.scale_permille", Kind: configbind.ScaffoldInt, Default: "1000", Help: "clock rate in thousandths, 1000 being realtime"},
			{Key: "slot", Kind: configbind.ScaffoldTableArray, Help: "Slot is the agent roster: which controller fills each concept:player-slot. An array of tables, so the file is its only source — element fields have no CLI option and no env var", Nested: []configbind.ScaffoldField{
				{Key: "index", Kind: configbind.ScaffoldInt, Default: "0", Help: "player slot index"},
				{Key: "kind", Kind: configbind.ScaffoldString, Default: "remote", Help: "controller kind: human, script, behavior_tree, llm, replay, remote"},
				{Key: "source", Kind: configbind.ScaffoldString, Help: "controller input: chip library, episode path, or script name"},
			}},
			{Key: "episode.dir", Kind: configbind.ScaffoldString, Help: "episode recording directory; empty disables recording"},
			{Key: "episode.mode", Kind: configbind.ScaffoldString, Default: "analysis_sampled", Help: "recording contract"},
			{Key: "episode.sample_percent", Kind: configbind.ScaffoldInt, Default: "100", Help: "percent of sessions recorded"},
			{Key: "debug.listen", Kind: configbind.ScaffoldString, Default: "127.0.0.1:8932", Help: "dev debug endpoint address; empty disables it"},
			{Key: "evaluation_version", Kind: configbind.ScaffoldInt, Default: "1", Help: "evaluation signal version recorded with every episode"},
		},
	})
}

func applyRunDefinition0(dst any, o *configbind.Overlay) error {
	p, ok := dst.(*Run)
	if !ok || p == nil {
		return fmt.Errorf("configbind: apply Run: bad destination")
	}
	if v, ok := o.GetString("run.topology"); ok {
		p.Topology = v
	} else {
		p.Topology = "standalone"
	}
	if v, ok := o.GetString("run.listen"); ok {
		p.Listen = v
	}
	if v, ok := o.GetMulti("run.transport.enable"); ok {
		p.Transport.Enable = v
	}
	if v, ok := o.GetString("run.transport.require_unreliable"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: run.transport.require_unreliable: %w", err)
		}
		p.Transport.RequireUnreliable = bb
	} else {
		p.Transport.RequireUnreliable = false
	}
	if v, ok := o.GetString("run.transport.require_peer_to_peer"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: run.transport.require_peer_to_peer: %w", err)
		}
		p.Transport.RequirePeerToPeer = bb
	} else {
		p.Transport.RequirePeerToPeer = false
	}
	if v, ok := o.GetString("run.transport.require_browser"); ok {
		bb, err := strconv.ParseBool(v)
		if err != nil {
			return fmt.Errorf("configbind: run.transport.require_browser: %w", err)
		}
		p.Transport.RequireBrowser = bb
	} else {
		p.Transport.RequireBrowser = false
	}
	if v, ok := o.GetString("run.sync.mode"); ok {
		p.Sync.Mode = v
	} else {
		p.Sync.Mode = "server_authoritative"
	}
	if v, ok := o.GetString("run.sync.baseline"); ok {
		p.Sync.Baseline = v
	} else {
		p.Sync.Baseline = "speculative"
	}
	if v, ok := o.GetString("run.sync.speculation_depth"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.sync.speculation_depth: %w", err)
		}
		p.Sync.SpeculationDepth = int(n)
	} else {
		p.Sync.SpeculationDepth = 0
	}
	if v, ok := o.GetString("run.sync.ack"); ok {
		p.Sync.Ack = v
	} else {
		p.Sync.Ack = "piggyback_only"
	}
	if v, ok := o.GetString("run.time.mode"); ok {
		p.Time.Mode = v
	} else {
		p.Time.Mode = "realtime"
	}
	if v, ok := o.GetString("run.time.scale_permille"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.time.scale_permille: %w", err)
		}
		p.Time.ScalePermille = int(n)
	} else {
		p.Time.ScalePermille = 1000
	}
	if ta1, ok := o.Get("run.slot"); ok {
		if !ta1.IsTables {
			return fmt.Errorf("configbind: run.slot: expected an array of tables ([[run.slot]])")
		}
		p.Slot = make([]Slot, len(ta1.Tables))
		for i1 := range ta1.Tables {
			if v, ok := ta1.Tables[i1].GetString("index"); ok {
				n, err := strconv.ParseInt(v, 10, 0)
				if err != nil {
					return fmt.Errorf("configbind: run.slot[%d].index: %w", i1, err)
				}
				p.Slot[i1].Index = int(n)
			} else {
				p.Slot[i1].Index = 0
			}
			if v, ok := ta1.Tables[i1].GetString("kind"); ok {
				p.Slot[i1].Kind = v
			} else {
				p.Slot[i1].Kind = "remote"
			}
			if v, ok := ta1.Tables[i1].GetString("source"); ok {
				p.Slot[i1].Source = v
			}
		}
	}
	if v, ok := o.GetString("run.episode.dir"); ok {
		p.Episode.Dir = v
	}
	if v, ok := o.GetString("run.episode.mode"); ok {
		p.Episode.Mode = v
	} else {
		p.Episode.Mode = "analysis_sampled"
	}
	if v, ok := o.GetString("run.episode.sample_percent"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.episode.sample_percent: %w", err)
		}
		p.Episode.SamplePercent = int(n)
	} else {
		p.Episode.SamplePercent = 100
	}
	if v, ok := o.GetString("run.debug.listen"); ok {
		p.Debug.Listen = v
	} else {
		p.Debug.Listen = "127.0.0.1:8932"
	}
	if v, ok := o.GetString("run.evaluation_version"); ok {
		n, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("configbind: run.evaluation_version: %w", err)
		}
		p.EvaluationVersion = int(n)
	} else {
		p.EvaluationVersion = 1
	}
	return nil
}
