// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:f8f8430b6b2fb348c60d8808371c41fc8e71fdd8203391b9f5fe647e27d950af self=sha256:a331e0dabfc81f55cd23305649d21cb66db314790bec37684827541ec28194bc outputs=tinybind_gen.go,configbind_gen.go

package runconf
