// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:9c1a4b5049ff9363c2794e1cafd18d8f135f736b26c1563481fe15cde3658d56 self=sha256:a331e0dabfc81f55cd23305649d21cb66db314790bec37684827541ec28194bc outputs=tinybind_gen.go,configbind_gen.go

package runconf
