// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:f1b52c01b820114db8254c3137d64c25103538eefc3f8c7f706f490b15da9151 self=sha256:a331e0dabfc81f55cd23305649d21cb66db314790bec37684827541ec28194bc outputs=tinybind_gen.go,configbind_gen.go

package runconf
