// Code generated by tinybind; DO NOT EDIT.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// cborWireProfile is the profile the wire codecs below were generated
// for. It is pinned here rather than taken from the caller: the two ends of
// a connection must not disagree about which profile is in use.
var cborWireProfile = cbor.Wire()

// cborWorldProfile is the profile the world codecs below were generated for.
var cborWorldProfile = cbor.World()

// CBORProtocolVersion identifies the wire shape of every codec in this file.
// It is derived from CBORSchema and covers wire-observable shape alone, so
// regenerating with a newer tinybind that emits the same bytes leaves it
// unchanged, and any change that moves one byte moves it.
const CBORProtocolVersion = "5573b857a6659d0b"

// CBORSchema is the canonical description CBORProtocolVersion digests.
const CBORSchema = `type Player world
keys int
  1 uint16
  2 uint8
  3 uint8
  4 uint8
  5 bool
  6 uint32
type TrailCell world
keys int
  1 uint32
  2 uint8
  3 uint8
  4 uint16
type TronState world
keys int
  1 uint64
  2 []struct Player
  3 []struct TrailCell
  4 uint32
  5 uint8
  6 bool
  7 uint16
type TurnInput wire
  uint32
  uint8
  uint8
`

// appendPlayerCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendPlayerCBORWorld(dst []byte, v Player) []byte {
	dst = cbor.AppendMapHeader(dst, 6)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.Dir))
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendBool(dst, bool(v.Alive))
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendUint(dst, uint64(v.DeathTick))
	return dst
}

// decodePlayerCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodePlayerCBORWorld(r *cbor.Reader, v *Player) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "Player", Err: cbor.ErrUnexpectedToken}
	}
	*v = Player{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.X = x
			}
		case 3:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Y = x
			}
		case 4:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Dir = x
			}
		case 5:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Alive = x
			}
		case 6:
			{
				x, err := r.ReadUint32()
				if err != nil {
					return err
				}
				v.DeathTick = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// appendTrailCellCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendTrailCellCBORWorld(dst []byte, v TrailCell) []byte {
	dst = cbor.AppendMapHeader(dst, 4)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.Owner))
	return dst
}

// decodeTrailCellCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeTrailCellCBORWorld(r *cbor.Reader, v *TrailCell) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TrailCell", Err: cbor.ErrUnexpectedToken}
	}
	*v = TrailCell{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint32()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.X = x
			}
		case 3:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Y = x
			}
		case 4:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.Owner = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// appendTronStateCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendTronStateCBORWorld(dst []byte, v TronState) []byte {
	dst = cbor.AppendMapHeader(dst, 7)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendArrayHeader(dst, len(v.Players))
	for i0 := range v.Players {
		dst = appendPlayerCBORWorld(dst, v.Players[i0])
	}
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendArrayHeader(dst, len(v.Trail))
	for i0 := range v.Trail {
		dst = appendTrailCellCBORWorld(dst, v.Trail[i0])
	}
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.NextTrail))
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendUint(dst, uint64(v.Alive))
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendBool(dst, bool(v.Over))
	dst = cbor.AppendUint(dst, 7)
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	return dst
}

// decodeTronStateCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeTronStateCBORWorld(r *cbor.Reader, v *TronState) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TronState", Err: cbor.ErrUnexpectedToken}
	}
	*v = TronState{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint64()
				if err != nil {
					return err
				}
				v.Tick = x
			}
		case 2:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "TronState.Players", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Players) >= n0 {
					v.Players = v.Players[:n0]
				} else {
					v.Players = make([]Player, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodePlayerCBORWorld(r, &v.Players[i0]); err != nil {
						return err
					}
				}
			}
		case 3:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "TronState.Trail", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Trail) >= n0 {
					v.Trail = v.Trail[:n0]
				} else {
					v.Trail = make([]TrailCell, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodeTrailCellCBORWorld(r, &v.Trail[i0]); err != nil {
						return err
					}
				}
			}
		case 4:
			{
				x, err := r.ReadUint32()
				if err != nil {
					return err
				}
				v.NextTrail = x
			}
		case 5:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Alive = x
			}
		case 6:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Over = x
			}
		case 7:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.Winner = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// AppendCBORTo appends v as one world-profile CBOR item, satisfying cbor.Appender.
func (v TronState) AppendCBORTo(dst []byte) []byte {
	return appendTronStateCBORWorld(dst, v)
}

// DecodeCBORFrom decodes one world-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *TronState) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeTronStateCBORWorld(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// appendTurnInputCBORWire appends v as one wire-profile CBOR item.
//
// The array is 3 long and its order is the declaration order of TurnInput.
// Both are part of the protocol: a reader counts on the position.
func appendTurnInputCBORWire(dst []byte, v TurnInput) []byte {
	dst = cbor.AppendArrayHeader(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, uint64(v.Dir))
	dst = cbor.AppendUint(dst, uint64(v.Buttons))
	return dst
}

// decodeTurnInputCBORWire decodes one wire-profile CBOR item into v.
//
// The array must be exactly 3 long. Under the wire profile a field the
// schema does not know cannot exist, so a count that disagrees is refused
// rather than read past: the two ends are running different protocols.
func decodeTurnInputCBORWire(r *cbor.Reader, v *TurnInput) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n != 3 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TurnInput", Err: cbor.ErrUnexpectedToken}
	}
	{
		x, err := r.ReadUint32()
		if err != nil {
			return err
		}
		v.Tick = x
	}
	{
		x, err := r.ReadUint8()
		if err != nil {
			return err
		}
		v.Dir = x
	}
	{
		x, err := r.ReadUint8()
		if err != nil {
			return err
		}
		v.Buttons = x
	}
	return nil
}

// AppendCBORTo appends v as one wire-profile CBOR item, satisfying cbor.Appender.
func (v TurnInput) AppendCBORTo(dst []byte) []byte {
	return appendTurnInputCBORWire(dst, v)
}

// DecodeCBORFrom decodes one wire-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *TurnInput) DecodeCBORFrom(data []byte) error {
	r := cborWireProfile.ReaderOver(data)
	if err := decodeTurnInputCBORWire(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// PlayerDelta is what changed between two Player values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type PlayerDelta struct {
	Present uint64
	// bit 0
	X uint8
	// bit 1
	Y uint8
	// bit 2
	Dir uint8
	// bit 3
	Alive bool
	// bit 4
	DeathTick uint32
}

// diffPlayerInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffPlayerInto(d *PlayerDelta, baseline, current Player) bool {
	d.Present = 0
	if baseline.X != current.X {
		d.Present |= 1 << 0
		d.X = current.X
	}
	if baseline.Y != current.Y {
		d.Present |= 1 << 1
		d.Y = current.Y
	}
	if baseline.Dir != current.Dir {
		d.Present |= 1 << 2
		d.Dir = current.Dir
	}
	if baseline.Alive != current.Alive {
		d.Present |= 1 << 3
		d.Alive = current.Alive
	}
	if baseline.DeathTick != current.DeathTick {
		d.Present |= 1 << 4
		d.DeathTick = current.DeathTick
	}
	return d.Present != 0
}

// applyPlayerDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyPlayerDelta(v *Player, d PlayerDelta) error {
	if d.Present&(1<<0) != 0 {
		v.X = d.X
	}
	if d.Present&(1<<1) != 0 {
		v.Y = d.Y
	}
	if d.Present&(1<<2) != 0 {
		v.Dir = d.Dir
	}
	if d.Present&(1<<3) != 0 {
		v.Alive = d.Alive
	}
	if d.Present&(1<<4) != 0 {
		v.DeathTick = d.DeathTick
	}
	return nil
}

// appendPlayerDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendPlayerDeltaCBOR(dst []byte, v PlayerDelta) []byte {
	n := 1
	for bit := 0; bit < 5; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.X))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Y))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Dir))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Alive))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.DeathTick))
	}
	return dst
}

// decodePlayerDeltaCBOR reads one delta into v.
func decodePlayerDeltaCBOR(r *cbor.Reader, v *PlayerDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.X = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Y = x
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Dir = x
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Alive = x
		}
		read++
	}
	if present&(1<<4) != 0 {
		{
			x, err := r.ReadUint32()
			if err != nil {
				return err
			}
			v.DeathTick = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// TrailCellDelta is what changed between two TrailCell values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type TrailCellDelta struct {
	Present uint64
	// bit 0
	X uint8
	// bit 1
	Y uint8
	// bit 2
	Owner uint16
}

// diffTrailCellInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffTrailCellInto(d *TrailCellDelta, baseline, current TrailCell) bool {
	d.Present = 0
	if baseline.X != current.X {
		d.Present |= 1 << 0
		d.X = current.X
	}
	if baseline.Y != current.Y {
		d.Present |= 1 << 1
		d.Y = current.Y
	}
	if baseline.Owner != current.Owner {
		d.Present |= 1 << 2
		d.Owner = current.Owner
	}
	return d.Present != 0
}

// applyTrailCellDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyTrailCellDelta(v *TrailCell, d TrailCellDelta) error {
	if d.Present&(1<<0) != 0 {
		v.X = d.X
	}
	if d.Present&(1<<1) != 0 {
		v.Y = d.Y
	}
	if d.Present&(1<<2) != 0 {
		v.Owner = d.Owner
	}
	return nil
}

// appendTrailCellDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendTrailCellDeltaCBOR(dst []byte, v TrailCellDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.X))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Y))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Owner))
	}
	return dst
}

// decodeTrailCellDeltaCBOR reads one delta into v.
func decodeTrailCellDeltaCBOR(r *cbor.Reader, v *TrailCellDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TrailCellDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.X = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Y = x
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadUint16()
			if err != nil {
				return err
			}
			v.Owner = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// TronStateDelta is what changed between two TronState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type TronStateDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	Players PlayerListDelta
	// bit 2
	Trail TrailCellListDelta
	// bit 3
	NextTrail uint32
	// bit 4
	Alive uint8
	// bit 5
	Over bool
	// bit 6
	Winner uint16
}

// diffTronStateInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffTronStateInto(d *TronStateDelta, baseline, current TronState) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if diffPlayerListInto(&d.Players, baseline.Players, current.Players) {
		d.Present |= 1 << 1
	}
	if diffTrailCellListInto(&d.Trail, baseline.Trail, current.Trail) {
		d.Present |= 1 << 2
	}
	if baseline.NextTrail != current.NextTrail {
		d.Present |= 1 << 3
		d.NextTrail = current.NextTrail
	}
	if baseline.Alive != current.Alive {
		d.Present |= 1 << 4
		d.Alive = current.Alive
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 5
		d.Over = current.Over
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 6
		d.Winner = current.Winner
	}
	return d.Present != 0
}

// applyTronStateDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyTronStateDelta(v *TronState, d TronStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		if err := applyPlayerListDelta(&v.Players, d.Players); err != nil {
			return err
		}
	}
	if d.Present&(1<<2) != 0 {
		if err := applyTrailCellListDelta(&v.Trail, d.Trail); err != nil {
			return err
		}
	}
	if d.Present&(1<<3) != 0 {
		v.NextTrail = d.NextTrail
	}
	if d.Present&(1<<4) != 0 {
		v.Alive = d.Alive
	}
	if d.Present&(1<<5) != 0 {
		v.Over = d.Over
	}
	if d.Present&(1<<6) != 0 {
		v.Winner = d.Winner
	}
	return nil
}

// appendTronStateDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendTronStateDeltaCBOR(dst []byte, v TronStateDelta) []byte {
	n := 1
	for bit := 0; bit < 7; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = appendPlayerListDeltaCBOR(dst, v.Players)
	}
	if v.Present&(1<<2) != 0 {
		dst = appendTrailCellListDeltaCBOR(dst, v.Trail)
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.NextTrail))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Alive))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	if v.Present&(1<<6) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	return dst
}

// decodeTronStateDeltaCBOR reads one delta into v.
func decodeTronStateDeltaCBOR(r *cbor.Reader, v *TronStateDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TronStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint64()
			if err != nil {
				return err
			}
			v.Tick = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		if err := decodePlayerListDeltaCBOR(r, &v.Players); err != nil {
			return err
		}
		read++
	}
	if present&(1<<2) != 0 {
		if err := decodeTrailCellListDeltaCBOR(r, &v.Trail); err != nil {
			return err
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadUint32()
			if err != nil {
				return err
			}
			v.NextTrail = x
		}
		read++
	}
	if present&(1<<4) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Alive = x
		}
		read++
	}
	if present&(1<<5) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Over = x
		}
		read++
	}
	if present&(1<<6) != 0 {
		{
			x, err := r.ReadUint16()
			if err != nil {
				return err
			}
			v.Winner = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// DiffTronState reports what changed between baseline and current.
//
// Use DiffTronStateInto in a loop that runs per tick: it fills a delta the caller
// retains, and reuses its collection capacity, so the steady state allocates
// nothing.
func DiffTronState(baseline, current TronState) TronStateDelta {
	var d TronStateDelta
	diffTronStateInto(&d, baseline, current)
	return d
}

// DiffTronStateInto is DiffTronState into a delta the caller owns and reuses.
func DiffTronStateInto(d *TronStateDelta, baseline, current TronState) {
	diffTronStateInto(d, baseline, current)
}

// ApplyTronStateDelta puts d back onto v.
//
// It reports an error when the delta names an entity v does not hold, which
// means v is not the baseline the delta was diffed against.
func ApplyTronStateDelta(v *TronState, d TronStateDelta) error {
	return applyTronStateDelta(v, d)
}

// AppendCBORTo appends the delta as one CBOR item, satisfying cbor.Appender.
func (v TronStateDelta) AppendCBORTo(dst []byte) []byte {
	return appendTronStateDeltaCBOR(dst, v)
}

// DecodeCBORFrom reads one delta into v, satisfying cbor.Decodable.
func (v *TronStateDelta) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeTronStateDeltaCBOR(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// PlayerListDelta is what changed in a collection of Player, keyed by ID.
//
// Present names the groups carried: bit 0 Set, bit 1 Removed, bit 2 Patched.
// The ordinary tick carries Patched alone, so an unchanged group costs a bit
// rather than an empty array.
type PlayerListDelta struct {
	Present uint64
	// Set carries an entity that arrived, or one replaced outright.
	Set []Player
	// Removed carries the identity of an entity that left.
	Removed []uint16
	// Patched carries an entity that changed, as its identity and its delta.
	Patched []PlayerPatch
	// index is scratch the diff reuses across ticks, so a steady state
	// allocates nothing after the first call. It is never encoded and never
	// ranged: every loop below walks a slice, which is what keeps the output
	// the same on two runs.
	index map[uint16]int32
}

// PlayerPatch is one changed Player: its identity, and what changed in it.
type PlayerPatch struct {
	ID    uint16
	Delta PlayerDelta
}

// diffPlayerListInto fills d with what changed between two collections of Player,
// and reports whether anything did.
//
// The order of the two slices is not compared: an entity is found by its
// identity, so a collection the game keeps in spawn order diffs the same as
// one it keeps sorted.
func diffPlayerListInto(d *PlayerListDelta, baseline, current []Player) bool {
	d.Present = 0
	d.Set = d.Set[:0]
	d.Removed = d.Removed[:0]
	d.Patched = d.Patched[:0]
	if d.index == nil {
		d.index = make(map[uint16]int32, len(baseline))
	} else {
		clear(d.index)
	}
	for i := range baseline {
		d.index[baseline[i].ID] = int32(i)
	}
	for j := range current {
		i, ok := d.index[current[j].ID]
		if !ok {
			d.Set = append(d.Set, current[j])
			continue
		}
		// Marked seen, so the sweep below reports only what did not arrive.
		d.index[current[j].ID] = -1
		// The slot is grown into rather than appended to, so the delta nested
		// inside it -- and the scratch index inside that -- is the one the last
		// tick used. Appending a fresh value here would allocate a new index map
		// per changed entity per tick, which is the whole steady state.
		if len(d.Patched) < cap(d.Patched) {
			d.Patched = d.Patched[:len(d.Patched)+1]
		} else {
			d.Patched = append(d.Patched, PlayerPatch{})
		}
		p := &d.Patched[len(d.Patched)-1]
		p.ID = current[j].ID
		if !diffPlayerInto(&p.Delta, baseline[i], current[j]) {
			d.Patched = d.Patched[:len(d.Patched)-1]
		}
	}
	for i := range baseline {
		if d.index[baseline[i].ID] >= 0 {
			d.Removed = append(d.Removed, baseline[i].ID)
		}
	}
	if len(d.Set) > 0 {
		d.Present |= 1 << 0
	}
	if len(d.Removed) > 0 {
		d.Present |= 1 << 1
	}
	if len(d.Patched) > 0 {
		d.Present |= 1 << 2
	}
	return d.Present != 0
}

// cborIndexOfPlayer finds an entity by identity, and reports -1 for one the
// collection does not hold.
func cborIndexOfPlayer(s []Player, id uint16) int {
	for i := range s {
		if s[i].ID == id {
			return i
		}
	}
	return -1
}

// cborSortPlayer puts a collection in identity order.
//
// An insertion sort, because a collection is nearly sorted already after a
// tick that changed a few entities, and because it allocates nothing and
// pulls in no import on a wasm target.
func cborSortPlayer(s []Player) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j].ID < s[j-1].ID; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// applyPlayerListDelta puts a collection delta back.
//
// Removals first, then patches, then arrivals: a patch names an entity the
// baseline held, and applying it after an arrival of the same identity would
// patch the wrong value. An identity a patch or a removal names and the
// collection does not hold means the baseline is not the one the sender
// diffed against, which is reported rather than ignored.
func applyPlayerListDelta(v *[]Player, d PlayerListDelta) error {
	if d.Present&(1<<1) != 0 {
		for _, id := range d.Removed {
			k := cborIndexOfPlayer(*v, id)
			if k < 0 {
				return &cbor.Error{Path: "Player: the delta removes an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			*v = append((*v)[:k], (*v)[k+1:]...)
		}
	}
	if d.Present&(1<<2) != 0 {
		for i := range d.Patched {
			k := cborIndexOfPlayer(*v, d.Patched[i].ID)
			if k < 0 {
				return &cbor.Error{Path: "Player: the delta patches an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			if err := applyPlayerDelta(&(*v)[k], d.Patched[i].Delta); err != nil {
				return err
			}
		}
	}
	if d.Present&(1<<0) != 0 {
		for i := range d.Set {
			k := cborIndexOfPlayer(*v, d.Set[i].ID)
			if k < 0 {
				*v = append(*v, d.Set[i])
			} else {
				(*v)[k] = d.Set[i]
			}
		}
	}
	// Identity order, so a receiver fed deltas and a sender holding the same
	// entities encode to the same bytes, which is what a replay compares.
	cborSortPlayer(*v)
	return nil
}

// appendPlayerListDeltaCBOR appends a collection delta.
//
// Only the groups Present names are written, and Patched alternates identity
// and payload in one array rather than pairing them: a byte per element, and
// a nesting level per hierarchy level.
func appendPlayerListDeltaCBOR(dst []byte, v PlayerListDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Set))
		for i := range v.Set {
			dst = appendPlayerCBORWorld(dst, v.Set[i])
		}
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Removed))
		for i := range v.Removed {
			dst = cbor.AppendUint(dst, uint64(v.Removed[i]))
		}
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Patched)*2)
		for i := range v.Patched {
			dst = cbor.AppendUint(dst, uint64(v.Patched[i].ID))
			dst = appendPlayerDeltaCBOR(dst, v.Patched[i].Delta)
		}
	}
	return dst
}

// decodePlayerListDeltaCBOR reads a collection delta.
func decodePlayerListDeltaCBOR(r *cbor.Reader, v *PlayerListDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerListDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	v.Set = v.Set[:0]
	v.Removed = v.Removed[:0]
	v.Patched = v.Patched[:0]
	read := 1
	if present&(1<<0) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			var x Player
			if err := decodePlayerCBORWorld(r, &x); err != nil {
				return err
			}
			v.Set = append(v.Set, x)
		}
		read++
	}
	if present&(1<<1) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint16(rawid)
			v.Removed = append(v.Removed, id)
		}
		read++
	}
	if present&(1<<2) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite || count%2 != 0 {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k += 2 {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint16(rawid)
			var p PlayerPatch
			p.ID = id
			if err := decodePlayerDeltaCBOR(r, &p.Delta); err != nil {
				return err
			}
			v.Patched = append(v.Patched, p)
		}
		read++
	}
	// A group this schema does not know: one item per remaining slot, which
	// is what keeps an older reader aligned when a group was appended.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// TrailCellListDelta is what changed in a collection of TrailCell, keyed by ID.
//
// Present names the groups carried: bit 0 Set, bit 1 Removed, bit 2 Patched.
// The ordinary tick carries Patched alone, so an unchanged group costs a bit
// rather than an empty array.
type TrailCellListDelta struct {
	Present uint64
	// Set carries an entity that arrived, or one replaced outright.
	Set []TrailCell
	// Removed carries the identity of an entity that left.
	Removed []uint32
	// Patched carries an entity that changed, as its identity and its delta.
	Patched []TrailCellPatch
	// index is scratch the diff reuses across ticks, so a steady state
	// allocates nothing after the first call. It is never encoded and never
	// ranged: every loop below walks a slice, which is what keeps the output
	// the same on two runs.
	index map[uint32]int32
}

// TrailCellPatch is one changed TrailCell: its identity, and what changed in it.
type TrailCellPatch struct {
	ID    uint32
	Delta TrailCellDelta
}

// diffTrailCellListInto fills d with what changed between two collections of TrailCell,
// and reports whether anything did.
//
// The order of the two slices is not compared: an entity is found by its
// identity, so a collection the game keeps in spawn order diffs the same as
// one it keeps sorted.
func diffTrailCellListInto(d *TrailCellListDelta, baseline, current []TrailCell) bool {
	d.Present = 0
	d.Set = d.Set[:0]
	d.Removed = d.Removed[:0]
	d.Patched = d.Patched[:0]
	if d.index == nil {
		d.index = make(map[uint32]int32, len(baseline))
	} else {
		clear(d.index)
	}
	for i := range baseline {
		d.index[baseline[i].ID] = int32(i)
	}
	for j := range current {
		i, ok := d.index[current[j].ID]
		if !ok {
			d.Set = append(d.Set, current[j])
			continue
		}
		// Marked seen, so the sweep below reports only what did not arrive.
		d.index[current[j].ID] = -1
		// The slot is grown into rather than appended to, so the delta nested
		// inside it -- and the scratch index inside that -- is the one the last
		// tick used. Appending a fresh value here would allocate a new index map
		// per changed entity per tick, which is the whole steady state.
		if len(d.Patched) < cap(d.Patched) {
			d.Patched = d.Patched[:len(d.Patched)+1]
		} else {
			d.Patched = append(d.Patched, TrailCellPatch{})
		}
		p := &d.Patched[len(d.Patched)-1]
		p.ID = current[j].ID
		if !diffTrailCellInto(&p.Delta, baseline[i], current[j]) {
			d.Patched = d.Patched[:len(d.Patched)-1]
		}
	}
	for i := range baseline {
		if d.index[baseline[i].ID] >= 0 {
			d.Removed = append(d.Removed, baseline[i].ID)
		}
	}
	if len(d.Set) > 0 {
		d.Present |= 1 << 0
	}
	if len(d.Removed) > 0 {
		d.Present |= 1 << 1
	}
	if len(d.Patched) > 0 {
		d.Present |= 1 << 2
	}
	return d.Present != 0
}

// cborIndexOfTrailCell finds an entity by identity, and reports -1 for one the
// collection does not hold.
func cborIndexOfTrailCell(s []TrailCell, id uint32) int {
	for i := range s {
		if s[i].ID == id {
			return i
		}
	}
	return -1
}

// cborSortTrailCell puts a collection in identity order.
//
// An insertion sort, because a collection is nearly sorted already after a
// tick that changed a few entities, and because it allocates nothing and
// pulls in no import on a wasm target.
func cborSortTrailCell(s []TrailCell) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j].ID < s[j-1].ID; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// applyTrailCellListDelta puts a collection delta back.
//
// Removals first, then patches, then arrivals: a patch names an entity the
// baseline held, and applying it after an arrival of the same identity would
// patch the wrong value. An identity a patch or a removal names and the
// collection does not hold means the baseline is not the one the sender
// diffed against, which is reported rather than ignored.
func applyTrailCellListDelta(v *[]TrailCell, d TrailCellListDelta) error {
	if d.Present&(1<<1) != 0 {
		for _, id := range d.Removed {
			k := cborIndexOfTrailCell(*v, id)
			if k < 0 {
				return &cbor.Error{Path: "TrailCell: the delta removes an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			*v = append((*v)[:k], (*v)[k+1:]...)
		}
	}
	if d.Present&(1<<2) != 0 {
		for i := range d.Patched {
			k := cborIndexOfTrailCell(*v, d.Patched[i].ID)
			if k < 0 {
				return &cbor.Error{Path: "TrailCell: the delta patches an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			if err := applyTrailCellDelta(&(*v)[k], d.Patched[i].Delta); err != nil {
				return err
			}
		}
	}
	if d.Present&(1<<0) != 0 {
		for i := range d.Set {
			k := cborIndexOfTrailCell(*v, d.Set[i].ID)
			if k < 0 {
				*v = append(*v, d.Set[i])
			} else {
				(*v)[k] = d.Set[i]
			}
		}
	}
	// Identity order, so a receiver fed deltas and a sender holding the same
	// entities encode to the same bytes, which is what a replay compares.
	cborSortTrailCell(*v)
	return nil
}

// appendTrailCellListDeltaCBOR appends a collection delta.
//
// Only the groups Present names are written, and Patched alternates identity
// and payload in one array rather than pairing them: a byte per element, and
// a nesting level per hierarchy level.
func appendTrailCellListDeltaCBOR(dst []byte, v TrailCellListDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Set))
		for i := range v.Set {
			dst = appendTrailCellCBORWorld(dst, v.Set[i])
		}
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Removed))
		for i := range v.Removed {
			dst = cbor.AppendUint(dst, uint64(v.Removed[i]))
		}
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Patched)*2)
		for i := range v.Patched {
			dst = cbor.AppendUint(dst, uint64(v.Patched[i].ID))
			dst = appendTrailCellDeltaCBOR(dst, v.Patched[i].Delta)
		}
	}
	return dst
}

// decodeTrailCellListDeltaCBOR reads a collection delta.
func decodeTrailCellListDeltaCBOR(r *cbor.Reader, v *TrailCellListDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TrailCellListDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	v.Set = v.Set[:0]
	v.Removed = v.Removed[:0]
	v.Patched = v.Patched[:0]
	read := 1
	if present&(1<<0) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "TrailCellListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			var x TrailCell
			if err := decodeTrailCellCBORWorld(r, &x); err != nil {
				return err
			}
			v.Set = append(v.Set, x)
		}
		read++
	}
	if present&(1<<1) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "TrailCellListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint32(rawid)
			v.Removed = append(v.Removed, id)
		}
		read++
	}
	if present&(1<<2) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite || count%2 != 0 {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "TrailCellListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k += 2 {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint32(rawid)
			var p TrailCellPatch
			p.ID = id
			if err := decodeTrailCellDeltaCBOR(r, &p.Delta); err != nil {
				return err
			}
			v.Patched = append(v.Patched, p)
		}
		read++
	}
	// A group this schema does not know: one item per remaining slot, which
	// is what keeps an older reader aligned when a group was appended.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}
