// Code generated by ebigent generate; DO NOT EDIT.
//
// The delta half of concept:state-synchronization. tinybind-go generates
// the codecs for the world and wire types themselves; since v0.5.21 it
// generates no diff, patch, or delta encoding, so those are the
// framework's (decision:framework-side-delta-generation) and they are
// here.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// DecodeLimits bounds what a decoder in this file will read. They are
// resource limits rather than format rules, so they belong to the
// deployment and not to the protocol: two peers must agree on the shape
// of a message and need agree on nothing about how large one this process
// is willing to read (data:runtime-resource-budget). Startup may lower
// them; the values here suit a snapshot.
var DecodeLimits = cbor.DecoderOptions{
	MaxContainerItems:  1 << 16,
	MaxStringBytes:     4 << 20,
	MaxInputBytes:      64 << 20,
	MaxRawMessageBytes: 64 << 20,
	RejectFloats:       true,
}

// equalPlayer compares two slices element by element. A delta asks whether
// a field changed, and for a slice that is a question about contents.
func equalPlayer(a, b []Player) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// appendPlayerSlice writes the slice as one CBOR array, each element
// through its own generated codec.
func appendPlayerSlice(dst []byte, v []Player) []byte {
	dst = cbor.AppendArrayHeader(dst, len(v))
	for i := range v {
		dst = v[i].AppendCBORTo(dst)
	}
	return dst
}

// readPlayerSlice reads one CBOR array of elements into out, reusing its
// capacity so a steady state allocates nothing.
func readPlayerSlice(r *cbor.Reader, out []Player) ([]Player, error) {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, &cbor.Error{Offset: int64(r.Offset()), Path: "Player", Err: cbor.ErrUnexpectedToken}
	}
	out = out[:0]
	for range n {
		var e Player
		raw, err := r.ReadRaw()
		if err != nil {
			return out, err
		}
		if err := e.DecodeCBORFrom(raw); err != nil {
			return out, err
		}
		out = append(out, e)
	}
	return out, nil
}

// equalTrailCell compares two slices element by element. A delta asks whether
// a field changed, and for a slice that is a question about contents.
func equalTrailCell(a, b []TrailCell) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// appendTrailCellSlice writes the slice as one CBOR array, each element
// through its own generated codec.
func appendTrailCellSlice(dst []byte, v []TrailCell) []byte {
	dst = cbor.AppendArrayHeader(dst, len(v))
	for i := range v {
		dst = v[i].AppendCBORTo(dst)
	}
	return dst
}

// readTrailCellSlice reads one CBOR array of elements into out, reusing its
// capacity so a steady state allocates nothing.
func readTrailCellSlice(r *cbor.Reader, out []TrailCell) ([]TrailCell, error) {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, &cbor.Error{Offset: int64(r.Offset()), Path: "TrailCell", Err: cbor.ErrUnexpectedToken}
	}
	out = out[:0]
	for range n {
		var e TrailCell
		raw, err := r.ReadRaw()
		if err != nil {
			return out, err
		}
		if err := e.DecodeCBORFrom(raw); err != nil {
			return out, err
		}
		out = append(out, e)
	}
	return out, nil
}

// TronStateDelta is what changed between two TronState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful. The bit
// order is declaration order, so moving a field moves the wire.
type TronStateDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	Players []Player
	// bit 2
	Trail []TrailCell
	// bit 3
	NextTrail uint32
	// bit 4
	Alive uint8
	// bit 5
	Over bool
	// bit 6
	Winner uint16
}

// DiffTronStateInto fills d with what changed between baseline and
// current, and reports whether anything did.
func DiffTronStateInto(d *TronStateDelta, baseline, current TronState) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if !equalPlayer(baseline.Players, current.Players) {
		d.Present |= 1 << 1
		d.Players = current.Players
	}
	if !equalTrailCell(baseline.Trail, current.Trail) {
		d.Present |= 1 << 2
		d.Trail = current.Trail
	}
	if baseline.NextTrail != current.NextTrail {
		d.Present |= 1 << 3
		d.NextTrail = current.NextTrail
	}
	if baseline.Alive != current.Alive {
		d.Present |= 1 << 4
		d.Alive = current.Alive
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 5
		d.Over = current.Over
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 6
		d.Winner = current.Winner
	}
	return d.Present != 0
}

// DiffTronState returns what changed between baseline and current.
func DiffTronState(baseline, current TronState) TronStateDelta {
	var d TronStateDelta
	DiffTronStateInto(&d, baseline, current)
	return d
}

// ApplyTronStateDelta puts d back onto v. A bit Present does not name
// leaves that field as it stands, which is what makes a delta a delta.
func ApplyTronStateDelta(v *TronState, d TronStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.Players = d.Players
	}
	if d.Present&(1<<2) != 0 {
		v.Trail = d.Trail
	}
	if d.Present&(1<<3) != 0 {
		v.NextTrail = d.NextTrail
	}
	if d.Present&(1<<4) != 0 {
		v.Alive = d.Alive
	}
	if d.Present&(1<<5) != 0 {
		v.Over = d.Over
	}
	if d.Present&(1<<6) != 0 {
		v.Winner = d.Winner
	}
	return nil
}

// AppendCBORTo appends d as one CBOR array: the mask, then the values it
// names, in bit order. A field the mask omits costs nothing.
func (v TronStateDelta) AppendCBORTo(dst []byte) []byte {
	n := 1
	for bit := range 7 {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = appendPlayerSlice(dst, v.Players)
	}
	if v.Present&(1<<2) != 0 {
		dst = appendTrailCellSlice(dst, v.Trail)
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.NextTrail))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Alive))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	if v.Present&(1<<6) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	return dst
}

// DecodeCBORFrom reads one delta into v, and refuses anything after it:
// a trailing item means the sender and the receiver disagree about the
// shape, which concept:cbor-wire-profile cannot detect any other way.
func (v *TronStateDelta) DecodeCBORFrom(data []byte) error {
	r, err := cbor.NewReader(data, DecodeLimits)
	if err != nil {
		return err
	}
	if err := v.decodeFrom(r); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// decodeFrom reads one delta off r.
func (v *TronStateDelta) decodeFrom(r *cbor.Reader) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TronStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Tick = uint64(x)
		read++
	}
	if present&(1<<1) != 0 {
		xs, err := readPlayerSlice(r, v.Players)
		if err != nil {
			return err
		}
		v.Players = xs
		read++
	}
	if present&(1<<2) != 0 {
		xs, err := readTrailCellSlice(r, v.Trail)
		if err != nil {
			return err
		}
		v.Trail = xs
		read++
	}
	if present&(1<<3) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.NextTrail = uint32(x)
		read++
	}
	if present&(1<<4) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Alive = uint8(x)
		read++
	}
	if present&(1<<5) != 0 {
		x, err := r.ReadBool()
		if err != nil {
			return err
		}
		v.Over = bool(x)
		read++
	}
	if present&(1<<6) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Winner = uint16(x)
		read++
	}
	if read != n {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TronStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	return nil
}
