// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:2f7cb18aa0844be37a936ac790421ba7a1aa213fea388674df899f1221c7e2d6 self=sha256:74f3ae053f8b7309031b04c4608d98e6520803476a961012eea9948c857113f7 outputs=tinybind_gen.go

package msg

import (
	"github.com/shibukawa/tinybind-go/cborbind"
	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

func appendTurnInputCBORArray(dst []byte, v TurnInput) []byte {
	dst = cbor.AppendArrayHeader(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, uint64(v.Dir))
	dst = cbor.AppendUint(dst, uint64(v.Buttons))
	return dst
}

func decodeTurnInputCBORArray(cr *cbor.Reader) (TurnInput, error) {
	var out TurnInput
	n, indefinite, err := cr.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite || n != 3 {
		return out, cborbind.ErrShape
	}
	{
		v, err := cr.ReadUint32()
		if err != nil {
			return out, err
		}
		out.Tick = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.Dir = v
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.Buttons = v
	}
	return out, nil
}

// AppendCBORInArrayTo appends v as CBOR, for cborbind.AppendCBORInArrayTo.
func (v TurnInput) AppendCBORInArrayTo(dst []byte) []byte {
	return appendTurnInputCBORArray(dst, v)
}

// DecodeCBORInArrayFrom decodes one CBOR value into v, for cborbind.DecodeCBORInArrayFrom.
func (v *TurnInput) DecodeCBORInArrayFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeTurnInputCBORArray(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape TurnInput declares.
func (v TurnInput) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInArrayTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape TurnInput declares.
func (v *TurnInput) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInArrayFrom(data)
}

func appendPlayerCBORMap(dst []byte, v Player) []byte {
	dst = cbor.AppendMapHeader(dst, 6)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "dir")
	dst = cbor.AppendUint(dst, uint64(v.Dir))
	dst = cbor.AppendText(dst, "alive")
	dst = cbor.AppendBool(dst, v.Alive)
	dst = cbor.AppendText(dst, "death")
	dst = cbor.AppendUint(dst, uint64(v.DeathTick))
	return dst
}

func decodePlayerCBORMap(cr *cbor.Reader) (Player, error) {
	var out Player
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "id":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "dir":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Dir = v
		case "alive":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Alive = v
		case "death":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.DeathTick = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v Player) AppendCBORInMapTo(dst []byte) []byte {
	return appendPlayerCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *Player) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodePlayerCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Player declares.
func (v Player) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Player declares.
func (v *Player) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendTrailCellCBORMap(dst []byte, v TrailCell) []byte {
	dst = cbor.AppendMapHeader(dst, 4)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendUint(dst, uint64(v.X))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendUint(dst, uint64(v.Y))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "owner")
	dst = cbor.AppendUint(dst, uint64(v.Owner))
	return dst
}

func decodeTrailCellCBORMap(cr *cbor.Reader) (TrailCell, error) {
	var out TrailCell
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.X = v
		case "y":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Y = v
		case "id":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "owner":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Owner = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v TrailCell) AppendCBORInMapTo(dst []byte) []byte {
	return appendTrailCellCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *TrailCell) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeTrailCellCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape TrailCell declares.
func (v TrailCell) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape TrailCell declares.
func (v *TrailCell) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendTronStateCBORMap(dst []byte, v TronState) []byte {
	dst = cbor.AppendMapHeader(dst, 7)
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendText(dst, "alive")
	dst = cbor.AppendUint(dst, uint64(v.Alive))
	dst = cbor.AppendText(dst, "trail")
	dst = cbor.AppendArrayHeader(dst, len(v.Trail))
	for i := range v.Trail {
		dst = appendTrailCellCBORMap(dst, v.Trail[i])
	}
	dst = cbor.AppendText(dst, "winner")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendText(dst, "players")
	dst = cbor.AppendArrayHeader(dst, len(v.Players))
	for i := range v.Players {
		dst = appendPlayerCBORMap(dst, v.Players[i])
	}
	dst = cbor.AppendText(dst, "next_trail")
	dst = cbor.AppendUint(dst, uint64(v.NextTrail))
	return dst
}

func decodeTronStateCBORMap(cr *cbor.Reader) (TronState, error) {
	var out TronState
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		case "alive":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Alive = v
		case "trail":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]TrailCell, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeTrailCellCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Trail = slice
		case "winner":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Winner = v
		case "players":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Player, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodePlayerCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Players = slice
		case "next_trail":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.NextTrail = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v TronState) AppendCBORInMapTo(dst []byte) []byte {
	return appendTronStateCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *TronState) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeTronStateCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape TronState declares.
func (v TronState) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape TronState declares.
func (v *TronState) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}
