// Code generated by ebigent generate; DO NOT EDIT.
//
// These are the codecs this package's types were asked for, and the ask
// is the call: since tinybind v0.5.23 there is no declaration to write,
// and the entry point named decides the container
// (requirement:cborbind-migration).
//
// What is asked for comes from the rule set declaration and nowhere else
// (requirement:stage-declares-its-wire). A world is a map, because only a
// map can be diffed and because the two ends may ship apart. An action is
// an array, because it is one small message with no baseline to diff
// against and both ends are rebuilt together.
//
// Nothing calls these. They are what the codec generator reads, and the
// linker drops them.

package msg

import "github.com/shibukawa/tinybind-go/cborbind"

// askTronState is the world position of a rule set: the whole value in the
// map shape.
func askTronState(dst []byte, v TronState) []byte { return cborbind.AppendCBORInMapTo(dst, v) }

func askDecodeTronState(data []byte) (TronState, error) { return cborbind.DecodeCBORInMapFrom[TronState](data) }

// askTurnInput is the action position of a rule set: the whole value in the
// array shape.
func askTurnInput(dst []byte, v TurnInput) []byte { return cborbind.AppendCBORInArrayTo(dst, v) }

func askDecodeTurnInput(data []byte) (TurnInput, error) { return cborbind.DecodeCBORInArrayFrom[TurnInput](data) }
