package analysis

import (
	"fmt"
	"io"
	"strings"
)

// WriteDuckDBSQL emits a self-contained SQL script for system:duckdb
// over the same corpus layout LoadCorpus reads. DuckDB scans the JSONL
// streams directly (data:episode-log is designed for that); the cgo
// DuckDB bindings stay out of this repository per
// rule:analysis-tooling-outside-game-process, so the handoff is a file:
// the operator runs the script in the duckdb CLI, entirely outside any
// game process.
//
// Header rows are filtered with "stream IS NULL": every header carries
// the stream column (episode.Header), and no data row does. Columns are
// declared explicitly from the episode row shapes rather than inferred,
// so a query never breaks just because a corpus happens to contain no
// rejection (or checkpoint, or ...) rows to infer the column from.
func WriteDuckDBSQL(w io.Writer, root string) error {
	esc := strings.ReplaceAll(root, "'", "''")
	var b strings.Builder

	b.WriteString(`-- Episode corpus views + example metric:balance-signals queries.
-- Generated by corpus-report for system:duckdb. Usage:
--
--   duckdb -init report.sql
--
-- or inside an existing duckdb session:  .read report.sql
--
-- Each view reads one JSONL stream of every episode directory under
-- the corpus root, with the column set declared from the episode
-- schema (episode/episode.go) so it is stable across corpora. Data
-- rows are selected with "stream IS NULL": header rows carry the
-- stream column, data rows never do. The episode column is derived
-- from each file's parent directory name. A view over a stream no
-- episode wrote (e.g. world in analysis_sampled corpora) errors at
-- query time, not at CREATE time.

`)
	// Column specs mirror the row shapes in episode/episode.go plus the
	// header's stream discriminator; absent keys read as NULL.
	streams := []struct{ name, columns string }{
		{"decisions", `stream: 'VARCHAR', tick: 'UBIGINT', slot: 'USMALLINT', agent_kind: 'VARCHAR', observation: 'JSON', action: 'JSON', evaluation: 'JSON', latency_micros: 'BIGINT'`},
		{"events", `stream: 'VARCHAR', tick: 'UBIGINT', kind: 'VARCHAR', "from": 'VARCHAR', "to": 'VARCHAR', slot: 'USMALLINT', reason: 'VARCHAR', world_hash: 'VARCHAR', action_hash: 'VARCHAR'`},
		{"outcomes", `stream: 'VARCHAR', slot: 'USMALLINT', result: 'VARCHAR', reward: 'BIGINT', duration_ticks: 'UBIGINT'`},
		{"world", `stream: 'VARCHAR', tick: 'UBIGINT', state: 'JSON'`},
	}
	for _, s := range streams {
		fmt.Fprintf(&b, `CREATE OR REPLACE VIEW %[1]s AS
SELECT regexp_extract(filename, '([^/\\]+)[/\\][^/\\]+$', 1) AS episode, *
FROM read_json('%[2]s/*/%[1]s.jsonl', format='newline_delimited', filename=true,
               columns={%[3]s})
WHERE stream IS NULL;

`, s.name, esc, s.columns)
	}

	b.WriteString(`-- metric:balance-signals: win rate by agent kind. The decisions
-- stream's slot -> agent_kind labels join each episode's outcomes.
WITH kinds AS (
    SELECT DISTINCT episode, slot, agent_kind
    FROM decisions
    WHERE agent_kind IS NOT NULL
)
SELECT k.agent_kind,
       count(*) AS outcomes,
       count(*) FILTER (WHERE o.result = 'win') AS wins,
       round(count(*) FILTER (WHERE o.result = 'win') * 1.0 / count(*), 3) AS win_rate
FROM outcomes AS o
JOIN kinds AS k USING (episode, slot)
GROUP BY k.agent_kind
ORDER BY k.agent_kind;

-- metric:episode-outcome: duration histogram, 10-tick buckets.
SELECT (duration_ticks // 10) * 10 AS bucket_start, count(*) AS episodes
FROM (SELECT DISTINCT episode, duration_ticks FROM outcomes)
GROUP BY bucket_start
ORDER BY bucket_start;

-- Validator rejection reasons, ranked.
SELECT reason, count(*) AS rejections
FROM events
WHERE kind = 'rejected'
GROUP BY reason
ORDER BY rejections DESC, reason;

-- Action rows vs observation-only deliveries.
SELECT count(*) FILTER (WHERE action IS NOT NULL) AS action_rows,
       count(*) FILTER (WHERE action IS NULL) AS observation_rows
FROM decisions;
`)

	_, err := io.WriteString(w, b.String())
	return err
}
