// Code generated by tinybind; DO NOT EDIT.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// cborWireProfile is the profile the wire codecs below were generated
// for. It is pinned here rather than taken from the caller: the two ends of
// a connection must not disagree about which profile is in use.
var cborWireProfile = cbor.Wire()

// cborWorldProfile is the profile the world codecs below were generated for.
var cborWorldProfile = cbor.World()

// CBORProtocolVersion identifies the wire shape of every codec in this file.
// It is derived from CBORSchema and covers wire-observable shape alone, so
// regenerating with a newer tinybind that emits the same bytes leaves it
// unchanged, and any change that moves one byte moves it.
const CBORProtocolVersion = "787d6000386004c1"

// CBORSchema is the canonical description CBORProtocolVersion digests.
const CBORSchema = `type Move wire
  uint8
type TTTState world
keys int
  1 bytes
  2 uint16
  3 uint16
  4 bytes
  5 uint8
  6 bool
`

// appendMoveCBORWire appends v as one wire-profile CBOR item.
//
// The array is 1 long and its order is the declaration order of Move.
// Both are part of the protocol: a reader counts on the position.
func appendMoveCBORWire(dst []byte, v Move) []byte {
	dst = cbor.AppendArrayHeader(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.Cell))
	return dst
}

// decodeMoveCBORWire decodes one wire-profile CBOR item into v.
//
// The array must be exactly 1 long. Under the wire profile a field the
// schema does not know cannot exist, so a count that disagrees is refused
// rather than read past: the two ends are running different protocols.
func decodeMoveCBORWire(r *cbor.Reader, v *Move) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n != 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "Move", Err: cbor.ErrUnexpectedToken}
	}
	{
		x, err := r.ReadUint8()
		if err != nil {
			return err
		}
		v.Cell = x
	}
	return nil
}

// AppendCBORTo appends v as one wire-profile CBOR item, satisfying cbor.Appender.
func (v Move) AppendCBORTo(dst []byte) []byte {
	return appendMoveCBORWire(dst, v)
}

// DecodeCBORFrom decodes one wire-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *Move) DecodeCBORFrom(data []byte) error {
	r := cborWireProfile.ReaderOver(data)
	if err := decodeMoveCBORWire(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// appendTTTStateCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendTTTStateCBORWorld(dst []byte, v TTTState) []byte {
	dst = cbor.AppendMapHeader(dst, 6)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendBytes(dst, []byte(v.Cells))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendUint(dst, uint64(v.Turn))
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	dst = cbor.AppendUint(dst, 4)
	dst = cbor.AppendBytes(dst, []byte(v.Line))
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendUint(dst, uint64(v.Moves))
	dst = cbor.AppendUint(dst, 6)
	dst = cbor.AppendBool(dst, bool(v.Over))
	return dst
}

// decodeTTTStateCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeTTTStateCBORWorld(r *cbor.Reader, v *TTTState) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TTTState", Err: cbor.ErrUnexpectedToken}
	}
	*v = TTTState{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.Cells = append(v.Cells[:0], x...)
			}
		case 2:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.Turn = x
			}
		case 3:
			{
				x, err := r.ReadUint16()
				if err != nil {
					return err
				}
				v.Winner = x
			}
		case 4:
			{
				x, err := r.ReadBytes()
				if err != nil {
					return err
				}
				// ReadBytes borrows from the input, so the value is copied into whatever
				// capacity the field already holds: it must outlive the buffer it was read
				// from, and reusing the capacity keeps the steady state allocation-free.
				v.Line = append(v.Line[:0], x...)
			}
		case 5:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Moves = x
			}
		case 6:
			{
				x, err := r.ReadBool()
				if err != nil {
					return err
				}
				v.Over = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// AppendCBORTo appends v as one world-profile CBOR item, satisfying cbor.Appender.
func (v TTTState) AppendCBORTo(dst []byte) []byte {
	return appendTTTStateCBORWorld(dst, v)
}

// DecodeCBORFrom decodes one world-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *TTTState) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeTTTStateCBORWorld(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// TTTStateDelta is what changed between two TTTState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type TTTStateDelta struct {
	Present uint64
	// bit 0
	Cells []uint8
	// bit 1
	Turn uint16
	// bit 2
	Winner uint16
	// bit 3
	Line []uint8
	// bit 4
	Moves uint8
	// bit 5
	Over bool
}

// diffTTTStateInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffTTTStateInto(d *TTTStateDelta, baseline, current TTTState) bool {
	d.Present = 0
	if string(baseline.Cells) != string(current.Cells) {
		d.Present |= 1 << 0
		d.Cells = current.Cells
	}
	if baseline.Turn != current.Turn {
		d.Present |= 1 << 1
		d.Turn = current.Turn
	}
	if baseline.Winner != current.Winner {
		d.Present |= 1 << 2
		d.Winner = current.Winner
	}
	if string(baseline.Line) != string(current.Line) {
		d.Present |= 1 << 3
		d.Line = current.Line
	}
	if baseline.Moves != current.Moves {
		d.Present |= 1 << 4
		d.Moves = current.Moves
	}
	if baseline.Over != current.Over {
		d.Present |= 1 << 5
		d.Over = current.Over
	}
	return d.Present != 0
}

// applyTTTStateDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyTTTStateDelta(v *TTTState, d TTTStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Cells = d.Cells
	}
	if d.Present&(1<<1) != 0 {
		v.Turn = d.Turn
	}
	if d.Present&(1<<2) != 0 {
		v.Winner = d.Winner
	}
	if d.Present&(1<<3) != 0 {
		v.Line = d.Line
	}
	if d.Present&(1<<4) != 0 {
		v.Moves = d.Moves
	}
	if d.Present&(1<<5) != 0 {
		v.Over = d.Over
	}
	return nil
}

// appendTTTStateDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendTTTStateDeltaCBOR(dst []byte, v TTTStateDelta) []byte {
	n := 1
	for bit := 0; bit < 6; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Cells))
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Turn))
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Winner))
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendBytes(dst, []byte(v.Line))
	}
	if v.Present&(1<<4) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Moves))
	}
	if v.Present&(1<<5) != 0 {
		dst = cbor.AppendBool(dst, bool(v.Over))
	}
	return dst
}

// decodeTTTStateDeltaCBOR reads one delta into v.
func decodeTTTStateDeltaCBOR(r *cbor.Reader, v *TTTStateDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "TTTStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.Cells = append(v.Cells[:0], x...)
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			x, err := r.ReadUint16()
			if err != nil {
				return err
			}
			v.Turn = x
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadUint16()
			if err != nil {
				return err
			}
			v.Winner = x
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadBytes()
			if err != nil {
				return err
			}
			// ReadBytes borrows from the input, so the value is copied into whatever
			// capacity the field already holds: it must outlive the buffer it was read
			// from, and reusing the capacity keeps the steady state allocation-free.
			v.Line = append(v.Line[:0], x...)
		}
		read++
	}
	if present&(1<<4) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Moves = x
		}
		read++
	}
	if present&(1<<5) != 0 {
		{
			x, err := r.ReadBool()
			if err != nil {
				return err
			}
			v.Over = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// DiffTTTState reports what changed between baseline and current.
//
// Use DiffTTTStateInto in a loop that runs per tick: it fills a delta the caller
// retains, and reuses its collection capacity, so the steady state allocates
// nothing.
func DiffTTTState(baseline, current TTTState) TTTStateDelta {
	var d TTTStateDelta
	diffTTTStateInto(&d, baseline, current)
	return d
}

// DiffTTTStateInto is DiffTTTState into a delta the caller owns and reuses.
func DiffTTTStateInto(d *TTTStateDelta, baseline, current TTTState) {
	diffTTTStateInto(d, baseline, current)
}

// ApplyTTTStateDelta puts d back onto v.
//
// It reports an error when the delta names an entity v does not hold, which
// means v is not the baseline the delta was diffed against.
func ApplyTTTStateDelta(v *TTTState, d TTTStateDelta) error {
	return applyTTTStateDelta(v, d)
}

// AppendCBORTo appends the delta as one CBOR item, satisfying cbor.Appender.
func (v TTTStateDelta) AppendCBORTo(dst []byte) []byte {
	return appendTTTStateDeltaCBOR(dst, v)
}

// DecodeCBORFrom reads one delta into v, satisfying cbor.Decodable.
func (v *TTTStateDelta) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeTTTStateDeltaCBOR(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}
