// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:8413144b6d9e9ae9318d427e03f25e1d849af58067fa7a92820b96b4a62c6e99 self=sha256:437643ad9248dc8a75b72c5dfae61b05605920e75e9849887f48584bfbbadc7e outputs=tinybind_gen.go

package msg

import (
	"github.com/shibukawa/tinybind-go/cborbind"
	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

func appendMoveCBORArray(dst []byte, v Move) []byte {
	dst = cbor.AppendArrayHeader(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.Cell))
	return dst
}

func decodeMoveCBORArray(cr *cbor.Reader) (Move, error) {
	var out Move
	n, indefinite, err := cr.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite || n != 1 {
		return out, cborbind.ErrShape
	}
	{
		v, err := cr.ReadUint8()
		if err != nil {
			return out, err
		}
		out.Cell = v
	}
	return out, nil
}

// AppendCBORInArrayTo appends v as CBOR, for cborbind.AppendCBORInArrayTo.
func (v Move) AppendCBORInArrayTo(dst []byte) []byte {
	return appendMoveCBORArray(dst, v)
}

// DecodeCBORInArrayFrom decodes one CBOR value into v, for cborbind.DecodeCBORInArrayFrom.
func (v *Move) DecodeCBORInArrayFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeMoveCBORArray(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Move declares.
func (v Move) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInArrayTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Move declares.
func (v *Move) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInArrayFrom(data)
}

func appendTTTStateCBORMap(dst []byte, v TTTState) []byte {
	dst = cbor.AppendMapHeader(dst, 6)
	dst = cbor.AppendText(dst, "line")
	dst = cbor.AppendArrayHeader(dst, len(v.Line))
	for i := range v.Line {
		dst = cbor.AppendUint(dst, uint64(v.Line[i]))
	}
	dst = cbor.AppendText(dst, "over")
	dst = cbor.AppendBool(dst, v.Over)
	dst = cbor.AppendText(dst, "turn")
	dst = cbor.AppendUint(dst, uint64(v.Turn))
	dst = cbor.AppendText(dst, "cells")
	dst = cbor.AppendArrayHeader(dst, len(v.Cells))
	for i := range v.Cells {
		dst = cbor.AppendUint(dst, uint64(v.Cells[i]))
	}
	dst = cbor.AppendText(dst, "moves")
	dst = cbor.AppendUint(dst, uint64(v.Moves))
	dst = cbor.AppendText(dst, "winner")
	dst = cbor.AppendUint(dst, uint64(v.Winner))
	return dst
}

func decodeTTTStateCBORMap(cr *cbor.Reader) (TTTState, error) {
	var out TTTState
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "line":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.Line = slice
		case "over":
			v, err := cr.ReadBool()
			if err != nil {
				return out, err
			}
			out.Over = v
		case "turn":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Turn = v
		case "cells":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]uint8, 0, n)
			for j := 0; j < n; j++ {
				ev0, err := cr.ReadUint8()
				if err != nil {
					return out, err
				}
				ev := ev0
				slice = append(slice, ev)
			}
			out.Cells = slice
		case "moves":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Moves = v
		case "winner":
			v, err := cr.ReadUint16()
			if err != nil {
				return out, err
			}
			out.Winner = v
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v TTTState) AppendCBORInMapTo(dst []byte) []byte {
	return appendTTTStateCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *TTTState) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeTTTStateCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape TTTState declares.
func (v TTTState) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape TTTState declares.
func (v *TTTState) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}
