// Code generated by tinybind; DO NOT EDIT.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// cborWireProfile is the profile the wire codecs below were generated
// for. It is pinned here rather than taken from the caller: the two ends of
// a connection must not disagree about which profile is in use.
var cborWireProfile = cbor.Wire()

// cborWorldProfile is the profile the world codecs below were generated for.
var cborWorldProfile = cbor.World()

// CBORProtocolVersion identifies the wire shape of every codec in this file.
// It is derived from CBORSchema and covers wire-observable shape alone, so
// regenerating with a newer tinybind that emits the same bytes leaves it
// unchanged, and any change that moves one byte moves it.
const CBORProtocolVersion = "eae7c0aeee4d3416"

// CBORSchema is the canonical description CBORProtocolVersion digests.
const CBORSchema = `type Entity world
keys int
  1 uint32
  2 self Fixed1024
  3 self Fixed1024
  4 self Fixed65536
  5 int32
type PlayerInput wire
  uint32
  self Fixed1024
  self Fixed1024
  uint16
type WorldState world
keys int
  1 uint64
  2 []struct Entity
  3 uint8
`

// appendEntityCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendEntityCBORWorld(dst []byte, v Entity) []byte {
	dst = cbor.AppendMapHeader(dst, 5)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendUint(dst, 2)
	dst = v.PosX.AppendCBORTo(dst)
	dst = cbor.AppendUint(dst, 3)
	dst = v.PosY.AppendCBORTo(dst)
	dst = cbor.AppendUint(dst, 4)
	dst = v.Vel.AppendCBORTo(dst)
	dst = cbor.AppendUint(dst, 5)
	dst = cbor.AppendInt(dst, int64(v.HP))
	return dst
}

// decodeEntityCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeEntityCBORWorld(r *cbor.Reader, v *Entity) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "Entity", Err: cbor.ErrUnexpectedToken}
	}
	*v = Entity{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint32()
				if err != nil {
					return err
				}
				v.ID = x
			}
		case 2:
			{
				raw, err := r.ReadRaw()
				if err != nil {
					return err
				}
				if err := v.PosX.DecodeCBORFrom(raw); err != nil {
					return err
				}
			}
		case 3:
			{
				raw, err := r.ReadRaw()
				if err != nil {
					return err
				}
				if err := v.PosY.DecodeCBORFrom(raw); err != nil {
					return err
				}
			}
		case 4:
			{
				raw, err := r.ReadRaw()
				if err != nil {
					return err
				}
				if err := v.Vel.DecodeCBORFrom(raw); err != nil {
					return err
				}
			}
		case 5:
			{
				x, err := r.ReadInt32()
				if err != nil {
					return err
				}
				v.HP = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// appendPlayerInputCBORWire appends v as one wire-profile CBOR item.
//
// The array is 4 long and its order is the declaration order of PlayerInput.
// Both are part of the protocol: a reader counts on the position.
func appendPlayerInputCBORWire(dst []byte, v PlayerInput) []byte {
	dst = cbor.AppendArrayHeader(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = v.MoveX.AppendCBORTo(dst)
	dst = v.MoveY.AppendCBORTo(dst)
	dst = cbor.AppendUint(dst, uint64(v.Buttons))
	return dst
}

// decodePlayerInputCBORWire decodes one wire-profile CBOR item into v.
//
// The array must be exactly 4 long. Under the wire profile a field the
// schema does not know cannot exist, so a count that disagrees is refused
// rather than read past: the two ends are running different protocols.
func decodePlayerInputCBORWire(r *cbor.Reader, v *PlayerInput) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n != 4 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "PlayerInput", Err: cbor.ErrUnexpectedToken}
	}
	{
		x, err := r.ReadUint32()
		if err != nil {
			return err
		}
		v.Tick = x
	}
	{
		raw, err := r.ReadRaw()
		if err != nil {
			return err
		}
		if err := v.MoveX.DecodeCBORFrom(raw); err != nil {
			return err
		}
	}
	{
		raw, err := r.ReadRaw()
		if err != nil {
			return err
		}
		if err := v.MoveY.DecodeCBORFrom(raw); err != nil {
			return err
		}
	}
	{
		x, err := r.ReadUint16()
		if err != nil {
			return err
		}
		v.Buttons = x
	}
	return nil
}

// AppendCBORTo appends v as one wire-profile CBOR item, satisfying cbor.Appender.
func (v PlayerInput) AppendCBORTo(dst []byte) []byte {
	return appendPlayerInputCBORWire(dst, v)
}

// DecodeCBORFrom decodes one wire-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *PlayerInput) DecodeCBORFrom(data []byte) error {
	r := cborWireProfile.ReaderOver(data)
	if err := decodePlayerInputCBORWire(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// appendWorldStateCBORWorld appends v as one world-profile CBOR item.
//
// Keys are written in the bytewise order of their encoded form, which is the
// core deterministic encoding of RFC 8949 and the order the world profile
// enforces. The order is fixed here, so two runs write the same bytes.
func appendWorldStateCBORWorld(dst []byte, v WorldState) []byte {
	dst = cbor.AppendMapHeader(dst, 3)
	dst = cbor.AppendUint(dst, 1)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendUint(dst, 2)
	dst = cbor.AppendArrayHeader(dst, len(v.Entities))
	for i0 := range v.Entities {
		dst = appendEntityCBORWorld(dst, v.Entities[i0])
	}
	dst = cbor.AppendUint(dst, 3)
	dst = cbor.AppendUint(dst, uint64(v.Phase))
	return dst
}

// decodeWorldStateCBORWorld decodes one world-profile CBOR item into v.
//
// A key this schema does not know is skipped, which is the tolerance the
// world profile exists to provide. A key it knows and the message omits
// leaves that field zero, so decoding into a reused value cannot inherit a
// field from the message before it.
func decodeWorldStateCBORWorld(r *cbor.Reader, v *WorldState) error {
	pairs, indefinite, err := r.ReadMapHeader()
	if err != nil {
		return err
	}
	if indefinite {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "WorldState", Err: cbor.ErrUnexpectedToken}
	}
	*v = WorldState{}
	for range pairs {
		key, err := r.ReadUint64()
		if err != nil {
			return err
		}
		switch key {
		case 1:
			{
				x, err := r.ReadUint64()
				if err != nil {
					return err
				}
				v.Tick = x
			}
		case 2:
			{
				n0, indefinite, err := r.ReadArrayHeader()
				if err != nil {
					return err
				}
				if indefinite {
					return &cbor.Error{Offset: int64(r.Offset()), Path: "WorldState.Entities", Err: cbor.ErrUnexpectedToken}
				}
				// The existing capacity is reused where it fits, so a value decoded into
				// repeatedly stops allocating after the first message.
				if cap(v.Entities) >= n0 {
					v.Entities = v.Entities[:n0]
				} else {
					v.Entities = make([]Entity, n0)
				}
				for i0 := 0; i0 < n0; i0++ {
					if err := decodeEntityCBORWorld(r, &v.Entities[i0]); err != nil {
						return err
					}
				}
			}
		case 3:
			{
				x, err := r.ReadUint8()
				if err != nil {
					return err
				}
				v.Phase = x
			}
		default:
			if err := r.Skip(); err != nil {
				return err
			}
		}
	}
	return nil
}

// AppendCBORTo appends v as one world-profile CBOR item, satisfying cbor.Appender.
func (v WorldState) AppendCBORTo(dst []byte) []byte {
	return appendWorldStateCBORWorld(dst, v)
}

// DecodeCBORFrom decodes one world-profile CBOR item into v, satisfying
// cbor.Decodable. data holds exactly one item and nothing after it.
func (v *WorldState) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeWorldStateCBORWorld(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// EntityDelta is what changed between two Entity values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type EntityDelta struct {
	Present uint64
	// bit 0
	PosX Fixed1024
	// bit 1
	PosY Fixed1024
	// bit 2
	Vel Fixed65536
	// bit 3
	HP int32
}

// diffEntityInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffEntityInto(d *EntityDelta, baseline, current Entity) bool {
	d.Present = 0
	if baseline.PosX != current.PosX {
		d.Present |= 1 << 0
		d.PosX = current.PosX
	}
	if baseline.PosY != current.PosY {
		d.Present |= 1 << 1
		d.PosY = current.PosY
	}
	if baseline.Vel != current.Vel {
		d.Present |= 1 << 2
		d.Vel = current.Vel
	}
	if baseline.HP != current.HP {
		d.Present |= 1 << 3
		d.HP = current.HP
	}
	return d.Present != 0
}

// applyEntityDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyEntityDelta(v *Entity, d EntityDelta) error {
	if d.Present&(1<<0) != 0 {
		v.PosX = d.PosX
	}
	if d.Present&(1<<1) != 0 {
		v.PosY = d.PosY
	}
	if d.Present&(1<<2) != 0 {
		v.Vel = d.Vel
	}
	if d.Present&(1<<3) != 0 {
		v.HP = d.HP
	}
	return nil
}

// appendEntityDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendEntityDeltaCBOR(dst []byte, v EntityDelta) []byte {
	n := 1
	for bit := 0; bit < 4; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = v.PosX.AppendCBORTo(dst)
	}
	if v.Present&(1<<1) != 0 {
		dst = v.PosY.AppendCBORTo(dst)
	}
	if v.Present&(1<<2) != 0 {
		dst = v.Vel.AppendCBORTo(dst)
	}
	if v.Present&(1<<3) != 0 {
		dst = cbor.AppendInt(dst, int64(v.HP))
	}
	return dst
}

// decodeEntityDeltaCBOR reads one delta into v.
func decodeEntityDeltaCBOR(r *cbor.Reader, v *EntityDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "EntityDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			raw, err := r.ReadRaw()
			if err != nil {
				return err
			}
			if err := v.PosX.DecodeCBORFrom(raw); err != nil {
				return err
			}
		}
		read++
	}
	if present&(1<<1) != 0 {
		{
			raw, err := r.ReadRaw()
			if err != nil {
				return err
			}
			if err := v.PosY.DecodeCBORFrom(raw); err != nil {
				return err
			}
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			raw, err := r.ReadRaw()
			if err != nil {
				return err
			}
			if err := v.Vel.DecodeCBORFrom(raw); err != nil {
				return err
			}
		}
		read++
	}
	if present&(1<<3) != 0 {
		{
			x, err := r.ReadInt32()
			if err != nil {
				return err
			}
			v.HP = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// WorldStateDelta is what changed between two WorldState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful.
type WorldStateDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	Entities EntityListDelta
	// bit 2
	Phase uint8
}

// diffWorldStateInto fills d with what changed between baseline and current,
// and reports whether anything did.
func diffWorldStateInto(d *WorldStateDelta, baseline, current WorldState) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if diffEntityListInto(&d.Entities, baseline.Entities, current.Entities) {
		d.Present |= 1 << 1
	}
	if baseline.Phase != current.Phase {
		d.Present |= 1 << 2
		d.Phase = current.Phase
	}
	return d.Present != 0
}

// applyWorldStateDelta puts d back onto v. A bit Present does not name leaves
// that field as it stands.
func applyWorldStateDelta(v *WorldState, d WorldStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		if err := applyEntityListDelta(&v.Entities, d.Entities); err != nil {
			return err
		}
	}
	if d.Present&(1<<2) != 0 {
		v.Phase = d.Phase
	}
	return nil
}

// appendWorldStateDeltaCBOR appends d as one CBOR item: the mask, then the
// values it names, in bit order.
func appendWorldStateDeltaCBOR(dst []byte, v WorldStateDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = appendEntityListDeltaCBOR(dst, v.Entities)
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Phase))
	}
	return dst
}

// decodeWorldStateDeltaCBOR reads one delta into v.
func decodeWorldStateDeltaCBOR(r *cbor.Reader, v *WorldStateDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "WorldStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		{
			x, err := r.ReadUint64()
			if err != nil {
				return err
			}
			v.Tick = x
		}
		read++
	}
	if present&(1<<1) != 0 {
		if err := decodeEntityListDeltaCBOR(r, &v.Entities); err != nil {
			return err
		}
		read++
	}
	if present&(1<<2) != 0 {
		{
			x, err := r.ReadUint8()
			if err != nil {
				return err
			}
			v.Phase = x
		}
		read++
	}
	// A bit this schema does not know: one item per remaining slot.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}

// DiffWorldState reports what changed between baseline and current.
//
// Use DiffWorldStateInto in a loop that runs per tick: it fills a delta the caller
// retains, and reuses its collection capacity, so the steady state allocates
// nothing.
func DiffWorldState(baseline, current WorldState) WorldStateDelta {
	var d WorldStateDelta
	diffWorldStateInto(&d, baseline, current)
	return d
}

// DiffWorldStateInto is DiffWorldState into a delta the caller owns and reuses.
func DiffWorldStateInto(d *WorldStateDelta, baseline, current WorldState) {
	diffWorldStateInto(d, baseline, current)
}

// ApplyWorldStateDelta puts d back onto v.
//
// It reports an error when the delta names an entity v does not hold, which
// means v is not the baseline the delta was diffed against.
func ApplyWorldStateDelta(v *WorldState, d WorldStateDelta) error {
	return applyWorldStateDelta(v, d)
}

// AppendCBORTo appends the delta as one CBOR item, satisfying cbor.Appender.
func (v WorldStateDelta) AppendCBORTo(dst []byte) []byte {
	return appendWorldStateDeltaCBOR(dst, v)
}

// DecodeCBORFrom reads one delta into v, satisfying cbor.Decodable.
func (v *WorldStateDelta) DecodeCBORFrom(data []byte) error {
	r := cborWorldProfile.ReaderOver(data)
	if err := decodeWorldStateDeltaCBOR(&r, v); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// EntityListDelta is what changed in a collection of Entity, keyed by ID.
//
// Present names the groups carried: bit 0 Set, bit 1 Removed, bit 2 Patched.
// The ordinary tick carries Patched alone, so an unchanged group costs a bit
// rather than an empty array.
type EntityListDelta struct {
	Present uint64
	// Set carries an entity that arrived, or one replaced outright.
	Set []Entity
	// Removed carries the identity of an entity that left.
	Removed []uint32
	// Patched carries an entity that changed, as its identity and its delta.
	Patched []EntityPatch
	// index is scratch the diff reuses across ticks, so a steady state
	// allocates nothing after the first call. It is never encoded and never
	// ranged: every loop below walks a slice, which is what keeps the output
	// the same on two runs.
	index map[uint32]int32
}

// EntityPatch is one changed Entity: its identity, and what changed in it.
type EntityPatch struct {
	ID    uint32
	Delta EntityDelta
}

// diffEntityListInto fills d with what changed between two collections of Entity,
// and reports whether anything did.
//
// The order of the two slices is not compared: an entity is found by its
// identity, so a collection the game keeps in spawn order diffs the same as
// one it keeps sorted.
func diffEntityListInto(d *EntityListDelta, baseline, current []Entity) bool {
	d.Present = 0
	d.Set = d.Set[:0]
	d.Removed = d.Removed[:0]
	d.Patched = d.Patched[:0]
	if d.index == nil {
		d.index = make(map[uint32]int32, len(baseline))
	} else {
		clear(d.index)
	}
	for i := range baseline {
		d.index[baseline[i].ID] = int32(i)
	}
	for j := range current {
		i, ok := d.index[current[j].ID]
		if !ok {
			d.Set = append(d.Set, current[j])
			continue
		}
		// Marked seen, so the sweep below reports only what did not arrive.
		d.index[current[j].ID] = -1
		// The slot is grown into rather than appended to, so the delta nested
		// inside it -- and the scratch index inside that -- is the one the last
		// tick used. Appending a fresh value here would allocate a new index map
		// per changed entity per tick, which is the whole steady state.
		if len(d.Patched) < cap(d.Patched) {
			d.Patched = d.Patched[:len(d.Patched)+1]
		} else {
			d.Patched = append(d.Patched, EntityPatch{})
		}
		p := &d.Patched[len(d.Patched)-1]
		p.ID = current[j].ID
		if !diffEntityInto(&p.Delta, baseline[i], current[j]) {
			d.Patched = d.Patched[:len(d.Patched)-1]
		}
	}
	for i := range baseline {
		if d.index[baseline[i].ID] >= 0 {
			d.Removed = append(d.Removed, baseline[i].ID)
		}
	}
	if len(d.Set) > 0 {
		d.Present |= 1 << 0
	}
	if len(d.Removed) > 0 {
		d.Present |= 1 << 1
	}
	if len(d.Patched) > 0 {
		d.Present |= 1 << 2
	}
	return d.Present != 0
}

// cborIndexOfEntity finds an entity by identity, and reports -1 for one the
// collection does not hold.
func cborIndexOfEntity(s []Entity, id uint32) int {
	for i := range s {
		if s[i].ID == id {
			return i
		}
	}
	return -1
}

// cborSortEntity puts a collection in identity order.
//
// An insertion sort, because a collection is nearly sorted already after a
// tick that changed a few entities, and because it allocates nothing and
// pulls in no import on a wasm target.
func cborSortEntity(s []Entity) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j].ID < s[j-1].ID; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// applyEntityListDelta puts a collection delta back.
//
// Removals first, then patches, then arrivals: a patch names an entity the
// baseline held, and applying it after an arrival of the same identity would
// patch the wrong value. An identity a patch or a removal names and the
// collection does not hold means the baseline is not the one the sender
// diffed against, which is reported rather than ignored.
func applyEntityListDelta(v *[]Entity, d EntityListDelta) error {
	if d.Present&(1<<1) != 0 {
		for _, id := range d.Removed {
			k := cborIndexOfEntity(*v, id)
			if k < 0 {
				return &cbor.Error{Path: "Entity: the delta removes an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			*v = append((*v)[:k], (*v)[k+1:]...)
		}
	}
	if d.Present&(1<<2) != 0 {
		for i := range d.Patched {
			k := cborIndexOfEntity(*v, d.Patched[i].ID)
			if k < 0 {
				return &cbor.Error{Path: "Entity: the delta patches an entity this baseline does not hold", Err: cbor.ErrUnexpectedToken}
			}
			if err := applyEntityDelta(&(*v)[k], d.Patched[i].Delta); err != nil {
				return err
			}
		}
	}
	if d.Present&(1<<0) != 0 {
		for i := range d.Set {
			k := cborIndexOfEntity(*v, d.Set[i].ID)
			if k < 0 {
				*v = append(*v, d.Set[i])
			} else {
				(*v)[k] = d.Set[i]
			}
		}
	}
	// Identity order, so a receiver fed deltas and a sender holding the same
	// entities encode to the same bytes, which is what a replay compares.
	cborSortEntity(*v)
	return nil
}

// appendEntityListDeltaCBOR appends a collection delta.
//
// Only the groups Present names are written, and Patched alternates identity
// and payload in one array rather than pairing them: a byte per element, and
// a nesting level per hierarchy level.
func appendEntityListDeltaCBOR(dst []byte, v EntityListDelta) []byte {
	n := 1
	for bit := 0; bit < 3; bit++ {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Set))
		for i := range v.Set {
			dst = appendEntityCBORWorld(dst, v.Set[i])
		}
	}
	if v.Present&(1<<1) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Removed))
		for i := range v.Removed {
			dst = cbor.AppendUint(dst, uint64(v.Removed[i]))
		}
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendArrayHeader(dst, len(v.Patched)*2)
		for i := range v.Patched {
			dst = cbor.AppendUint(dst, uint64(v.Patched[i].ID))
			dst = appendEntityDeltaCBOR(dst, v.Patched[i].Delta)
		}
	}
	return dst
}

// decodeEntityListDeltaCBOR reads a collection delta.
func decodeEntityListDeltaCBOR(r *cbor.Reader, v *EntityListDelta) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "EntityListDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	v.Set = v.Set[:0]
	v.Removed = v.Removed[:0]
	v.Patched = v.Patched[:0]
	read := 1
	if present&(1<<0) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "EntityListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			var x Entity
			if err := decodeEntityCBORWorld(r, &x); err != nil {
				return err
			}
			v.Set = append(v.Set, x)
		}
		read++
	}
	if present&(1<<1) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "EntityListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k++ {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint32(rawid)
			v.Removed = append(v.Removed, id)
		}
		read++
	}
	if present&(1<<2) != 0 {
		count, indefinite, err := r.ReadArrayHeader()
		if err != nil {
			return err
		}
		if indefinite || count%2 != 0 {
			return &cbor.Error{Offset: int64(r.Offset()), Path: "EntityListDelta", Err: cbor.ErrUnexpectedToken}
		}
		for k := 0; k < count; k += 2 {
			rawid, err := r.ReadUint64()
			if err != nil {
				return err
			}
			id := uint32(rawid)
			var p EntityPatch
			p.ID = id
			if err := decodeEntityDeltaCBOR(r, &p.Delta); err != nil {
				return err
			}
			v.Patched = append(v.Patched, p)
		}
		read++
	}
	// A group this schema does not know: one item per remaining slot, which
	// is what keeps an older reader aligned when a group was appended.
	for ; read < n; read++ {
		if err := r.Skip(); err != nil {
			return err
		}
	}
	return nil
}
