// Code generated by ebigent generate; DO NOT EDIT.
//
// The delta half of concept:state-synchronization. tinybind-go generates
// the codecs for the world and wire types themselves; since v0.5.21 it
// generates no diff, patch, or delta encoding, so those are the
// framework's (decision:framework-side-delta-generation) and they are
// here.

package msg

import "github.com/shibukawa/tinygodriver/encoding/cbor"

// DecodeLimits bounds what a decoder in this file will read. They are
// resource limits rather than format rules, so they belong to the
// deployment and not to the protocol: two peers must agree on the shape
// of a message and need agree on nothing about how large one this process
// is willing to read (data:runtime-resource-budget). Startup may lower
// them; the values here suit a snapshot.
var DecodeLimits = cbor.DecoderOptions{
	MaxContainerItems:  1 << 16,
	MaxStringBytes:     4 << 20,
	MaxInputBytes:      64 << 20,
	MaxRawMessageBytes: 64 << 20,
	RejectFloats:       true,
}

// equalEntity compares two slices element by element. A delta asks whether
// a field changed, and for a slice that is a question about contents.
func equalEntity(a, b []Entity) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// appendEntitySlice writes the slice as one CBOR array, each element
// through its own generated codec.
func appendEntitySlice(dst []byte, v []Entity) []byte {
	dst = cbor.AppendArrayHeader(dst, len(v))
	for i := range v {
		dst = v[i].AppendCBORTo(dst)
	}
	return dst
}

// readEntitySlice reads one CBOR array of elements into out, reusing its
// capacity so a steady state allocates nothing.
func readEntitySlice(r *cbor.Reader, out []Entity) ([]Entity, error) {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, &cbor.Error{Offset: int64(r.Offset()), Path: "Entity", Err: cbor.ErrUnexpectedToken}
	}
	out = out[:0]
	for range n {
		var e Entity
		raw, err := r.ReadRaw()
		if err != nil {
			return out, err
		}
		if err := e.DecodeCBORFrom(raw); err != nil {
			return out, err
		}
		out = append(out, e)
	}
	return out, nil
}

// WorldStateDelta is what changed between two WorldState values.
//
// Present names the fields carried: bit n is set when field n of the list
// below changed, and every other field holds nothing meaningful. The bit
// order is declaration order, so moving a field moves the wire.
type WorldStateDelta struct {
	Present uint64
	// bit 0
	Tick uint64
	// bit 1
	Entities []Entity
	// bit 2
	Phase uint8
}

// DiffWorldStateInto fills d with what changed between baseline and
// current, and reports whether anything did.
func DiffWorldStateInto(d *WorldStateDelta, baseline, current WorldState) bool {
	d.Present = 0
	if baseline.Tick != current.Tick {
		d.Present |= 1 << 0
		d.Tick = current.Tick
	}
	if !equalEntity(baseline.Entities, current.Entities) {
		d.Present |= 1 << 1
		d.Entities = current.Entities
	}
	if baseline.Phase != current.Phase {
		d.Present |= 1 << 2
		d.Phase = current.Phase
	}
	return d.Present != 0
}

// DiffWorldState returns what changed between baseline and current.
func DiffWorldState(baseline, current WorldState) WorldStateDelta {
	var d WorldStateDelta
	DiffWorldStateInto(&d, baseline, current)
	return d
}

// ApplyWorldStateDelta puts d back onto v. A bit Present does not name
// leaves that field as it stands, which is what makes a delta a delta.
func ApplyWorldStateDelta(v *WorldState, d WorldStateDelta) error {
	if d.Present&(1<<0) != 0 {
		v.Tick = d.Tick
	}
	if d.Present&(1<<1) != 0 {
		v.Entities = d.Entities
	}
	if d.Present&(1<<2) != 0 {
		v.Phase = d.Phase
	}
	return nil
}

// AppendCBORTo appends d as one CBOR array: the mask, then the values it
// names, in bit order. A field the mask omits costs nothing.
func (v WorldStateDelta) AppendCBORTo(dst []byte) []byte {
	n := 1
	for bit := range 3 {
		if v.Present&(1<<uint(bit)) != 0 {
			n++
		}
	}
	dst = cbor.AppendArrayHeader(dst, n)
	dst = cbor.AppendUint(dst, v.Present)
	if v.Present&(1<<0) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Tick))
	}
	if v.Present&(1<<1) != 0 {
		dst = appendEntitySlice(dst, v.Entities)
	}
	if v.Present&(1<<2) != 0 {
		dst = cbor.AppendUint(dst, uint64(v.Phase))
	}
	return dst
}

// DecodeCBORFrom reads one delta into v, and refuses anything after it:
// a trailing item means the sender and the receiver disagree about the
// shape, which concept:cbor-wire-profile cannot detect any other way.
func (v *WorldStateDelta) DecodeCBORFrom(data []byte) error {
	r, err := cbor.NewReader(data, DecodeLimits)
	if err != nil {
		return err
	}
	if err := v.decodeFrom(r); err != nil {
		return err
	}
	if !r.Done() {
		return cbor.ErrExtraneousData
	}
	return nil
}

// decodeFrom reads one delta off r.
func (v *WorldStateDelta) decodeFrom(r *cbor.Reader) error {
	n, indefinite, err := r.ReadArrayHeader()
	if err != nil {
		return err
	}
	if indefinite || n < 1 {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "WorldStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	present, err := r.ReadUint64()
	if err != nil {
		return err
	}
	v.Present = present
	read := 1
	if present&(1<<0) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Tick = uint64(x)
		read++
	}
	if present&(1<<1) != 0 {
		xs, err := readEntitySlice(r, v.Entities)
		if err != nil {
			return err
		}
		v.Entities = xs
		read++
	}
	if present&(1<<2) != 0 {
		x, err := r.ReadUint64()
		if err != nil {
			return err
		}
		v.Phase = uint8(x)
		read++
	}
	if read != n {
		return &cbor.Error{Offset: int64(r.Offset()), Path: "WorldStateDelta", Err: cbor.ErrUnexpectedToken}
	}
	return nil
}
