// Code generated by tinybind; DO NOT EDIT.
// tinybind:generated v1 inputs=sha256:b5ffa4ad8933a85663683b2238309600a72007b739c3730ab07e5f53b22bf93e self=sha256:54889cce9e2a03dab4a76903d54ae715b3e2f4600d1c0ca5dcc8528a67b9d7e7 outputs=tinybind_gen.go

package msg

import (
	"github.com/shibukawa/tinybind-go/cborbind"
	"github.com/shibukawa/tinygodriver/encoding/cbor"
)

func appendPlayerInputCBORArray(dst []byte, v PlayerInput) []byte {
	dst = cbor.AppendArrayHeader(dst, 4)
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendInt(dst, int64(v.MoveX))
	dst = cbor.AppendInt(dst, int64(v.MoveY))
	dst = cbor.AppendUint(dst, uint64(v.Buttons))
	return dst
}

func decodePlayerInputCBORArray(cr *cbor.Reader) (PlayerInput, error) {
	var out PlayerInput
	n, indefinite, err := cr.ReadArrayHeader()
	if err != nil {
		return out, err
	}
	if indefinite || n != 4 {
		return out, cborbind.ErrShape
	}
	{
		v, err := cr.ReadUint32()
		if err != nil {
			return out, err
		}
		out.Tick = v
	}
	{
		v, err := cr.ReadInt()
		if err != nil {
			return out, err
		}
		out.MoveX = Fixed1024(v)
	}
	{
		v, err := cr.ReadInt()
		if err != nil {
			return out, err
		}
		out.MoveY = Fixed1024(v)
	}
	{
		v, err := cr.ReadUint16()
		if err != nil {
			return out, err
		}
		out.Buttons = v
	}
	return out, nil
}

// AppendCBORInArrayTo appends v as CBOR, for cborbind.AppendCBORInArrayTo.
func (v PlayerInput) AppendCBORInArrayTo(dst []byte) []byte {
	return appendPlayerInputCBORArray(dst, v)
}

// DecodeCBORInArrayFrom decodes one CBOR value into v, for cborbind.DecodeCBORInArrayFrom.
func (v *PlayerInput) DecodeCBORInArrayFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodePlayerInputCBORArray(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape PlayerInput declares.
func (v PlayerInput) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInArrayTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape PlayerInput declares.
func (v *PlayerInput) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInArrayFrom(data)
}

func appendEntityCBORMap(dst []byte, v Entity) []byte {
	dst = cbor.AppendMapHeader(dst, 5)
	dst = cbor.AppendText(dst, "x")
	dst = cbor.AppendInt(dst, int64(v.PosX))
	dst = cbor.AppendText(dst, "y")
	dst = cbor.AppendInt(dst, int64(v.PosY))
	dst = cbor.AppendText(dst, "hp")
	dst = cbor.AppendInt(dst, int64(v.HP))
	dst = cbor.AppendText(dst, "id")
	dst = cbor.AppendUint(dst, uint64(v.ID))
	dst = cbor.AppendText(dst, "vel")
	dst = cbor.AppendInt(dst, int64(v.Vel))
	return dst
}

func decodeEntityCBORMap(cr *cbor.Reader) (Entity, error) {
	var out Entity
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "x":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.PosX = Fixed1024(v)
		case "y":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.PosY = Fixed1024(v)
		case "hp":
			v, err := cr.ReadInt32()
			if err != nil {
				return out, err
			}
			out.HP = v
		case "id":
			v, err := cr.ReadUint32()
			if err != nil {
				return out, err
			}
			out.ID = v
		case "vel":
			v, err := cr.ReadInt()
			if err != nil {
				return out, err
			}
			out.Vel = Fixed65536(v)
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v Entity) AppendCBORInMapTo(dst []byte) []byte {
	return appendEntityCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *Entity) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeEntityCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape Entity declares.
func (v Entity) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape Entity declares.
func (v *Entity) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}

func appendWorldStateCBORMap(dst []byte, v WorldState) []byte {
	dst = cbor.AppendMapHeader(dst, 3)
	dst = cbor.AppendText(dst, "tick")
	dst = cbor.AppendUint(dst, uint64(v.Tick))
	dst = cbor.AppendText(dst, "phase")
	dst = cbor.AppendUint(dst, uint64(v.Phase))
	dst = cbor.AppendText(dst, "entities")
	dst = cbor.AppendArrayHeader(dst, len(v.Entities))
	for i := range v.Entities {
		dst = appendEntityCBORMap(dst, v.Entities[i])
	}
	return dst
}

func decodeWorldStateCBORMap(cr *cbor.Reader) (WorldState, error) {
	var out WorldState
	pairs, indefinite, err := cr.ReadMapHeader()
	if err != nil {
		return out, err
	}
	if indefinite {
		return out, cborbind.ErrShape
	}
	for i := 0; i < pairs; i++ {
		key, err := cr.ReadTextBytes()
		if err != nil {
			return out, err
		}
		switch string(key) {
		case "tick":
			v, err := cr.ReadUint64()
			if err != nil {
				return out, err
			}
			out.Tick = v
		case "phase":
			v, err := cr.ReadUint8()
			if err != nil {
				return out, err
			}
			out.Phase = v
		case "entities":
			n, indef, err := cr.ReadArrayHeader()
			if err != nil || indef {
				return out, err
			}
			slice := make([]Entity, 0, n)
			for j := 0; j < n; j++ {
				ev, err := decodeEntityCBORMap(cr)
				if err != nil {
					return out, err
				}
				slice = append(slice, ev)
			}
			out.Entities = slice
		default:
			if err := cr.Skip(); err != nil {
				return out, err
			}
		}
	}
	return out, nil
}

// AppendCBORInMapTo appends v as CBOR, for cborbind.AppendCBORInMapTo.
func (v WorldState) AppendCBORInMapTo(dst []byte) []byte {
	return appendWorldStateCBORMap(dst, v)
}

// DecodeCBORInMapFrom decodes one CBOR value into v, for cborbind.DecodeCBORInMapFrom.
func (v *WorldState) DecodeCBORInMapFrom(data []byte) error {
	cr := cbor.ReaderOver(data, cbor.DecoderOptions{})
	got, err := decodeWorldStateCBORMap(&cr)
	if err != nil {
		return err
	}
	*v = got
	return nil
}

// AppendCBORTo satisfies cbor.Appender through the one shape WorldState declares.
func (v WorldState) AppendCBORTo(dst []byte) []byte {
	return v.AppendCBORInMapTo(dst)
}

// DecodeCBORFrom satisfies cbor.Decodable through the one shape WorldState declares.
func (v *WorldState) DecodeCBORFrom(data []byte) error {
	return v.DecodeCBORInMapFrom(data)
}
